import test from 'node:test';import assert from 'node:assert/strict';
import {STORES,command,normalizeHoldings} from '../src/local-domain.js';
import {migrateAccess,projectState,mergeScope} from '../src/access-model.js';
import {expireAccess} from '../src/access-domain.js';
import {hasPermission,PROFILE_PERMISSIONS} from '../src/permissions.js';
const seed=()=>{const all=Object.fromEntries(STORES.map(k=>[k,[]]));migrateAccess(all);const s=projectState(all,'local-institution','local-admin');normalizeHoldings(s);return {all,s};};
const person=(s,cargo='Docente',profile='docente')=>command(s,'local-admin','person.save',{name:'Persona '+cargo,cargo,accessProfile:profile,status:'active'});
function refresh(s){s.patrons=s.memberships.map(m=>({...s.people.find(p=>p.id===m.personId),...m,id:m.personId,mainAdmin:s.institutions[0].mainAdminId===m.personId}));}
test('cargo, identity and profile stay separate through grant, expiry, reactivation and promotion',()=>{const {s}=seed(),p=person(s);refresh(s);const g=command(s,'local-admin','grant.add',{userId:p.id,permission:'catalog.create',expiresAt:'2031-01-01T18:00:00Z',note:'Inventario'});let u=s.patrons.find(p2=>p2.id===p.id);assert.equal(u.cargo,'Docente');assert.ok(hasPermission(u,'catalog.create',s.grants));expireAccess(s,Date.parse('2031-01-01T18:00:01Z'));assert.equal(hasPermission(u,'catalog.create',s.grants),false);assert.equal(s.activity.filter(x=>x.type==='permission.expired').length,1);expireAccess(s,Date.parse('2031-01-01T18:00:02Z'));assert.equal(s.activity.filter(x=>x.type==='permission.expired').length,1);command(s,'local-admin','person.save',{...u,cargo:'Vicedirector/a',accessProfile:'autoridad'});assert.equal(s.people.filter(x=>x.id===p.id).length,1);assert.equal(s.grants[0].id,g.id);});
test('self escalation, max delegation and owner deactivation are rejected',()=>{const {s}=seed();const teacher=person(s);refresh(s);assert.throws(()=>command(s,teacher.id,'grant.add',{userId:teacher.id,permission:'catalog.create'}));assert.throws(()=>command(s,'local-admin','grant.add',{userId:'local-admin',permission:'catalog.create'}),/propios/);assert.throws(()=>command(s,'local-admin','grant.add',{userId:teacher.id,permission:'catalog.clear'}),/no se delega/);assert.throws(()=>command(s,'local-admin','person.save',{id:'local-admin',name:'Yo',cargo:'Director/a',accessProfile:'autoridad'}),/propio/);assert.throws(()=>command(s,'local-admin','person.save',{...s.patrons[0],status:'inactive'}));});
test('library can delegate operational rights but cannot create new authorities or grant management',()=>{const {s}=seed();const librarian=person(s,'Bibliotecario/a','biblioteca'),teacher=person(s);refresh(s);command(s,librarian.id,'grant.add',{userId:teacher.id,permission:'contents.manage'});assert.throws(()=>command(s,librarian.id,'grant.add',{userId:teacher.id,permission:'permissions.manage'}));assert.throws(()=>command(s,librarian.id,'person.save',{...teacher,cargo:'Director/a',accessProfile:'autoridad'}));assert.ok(!PROFILE_PERMISSIONS.autoridad.includes('catalog.create'));});
test('scope preserves other institutions and rejects colliding entity ids; grants never cross',()=>{const {all,s}=seed(),p=person(s);refresh(s);command(s,'local-admin','grant.add',{userId:p.id,permission:'catalog.create'});mergeScope(all,s,'local-institution');all.institutions.push({id:'B',name:'B',mainAdminId:'other'});all.memberships.push({id:'mb',personId:p.id,institutionId:'B',cargo:'Docente',accessProfile:'docente',status:'active'});const b=projectState(all,'B',p.id);assert.equal(b.grants.length,0);assert.equal(hasPermission(b.patrons[0],'catalog.create',s.grants),false);assert.equal(b.patrons[0].id,p.id);const original=JSON.stringify(all.memberships);mergeScope(all,b,'B');assert.equal(all.memberships.length,3);assert.ok(all.memberships.some(m=>m.institutionId==='local-institution'&&m.personId===p.id));});
test('substitution expires and suspension ends without deleting person or history',()=>{const {s}=seed(),p=person(s);refresh(s);command(s,'local-admin','person.save',{...p,status:'active',expiresAt:'2020-01-01T00:00:00Z'});expireAccess(s);assert.equal(s.memberships.find(m=>m.personId===p.id).status,'inactive');assert.ok(s.people.some(x=>x.id===p.id));refresh(s);command(s,'local-admin','person.save',{...p,status:'suspended',expiresAt:'2020-01-01T00:00:00Z'});expireAccess(s);assert.equal(s.memberships.find(m=>m.personId===p.id).status,'active');});
test('delegated people editor cannot create library administrators through invitations',()=>{const {s}=seed(),teacher=person(s);refresh(s);command(s,'local-admin','grant.add',{userId:teacher.id,permission:'users.manage'});command(s,'local-admin','grant.add',{userId:teacher.id,permission:'people.invite'});assert.throws(()=>command(s,teacher.id,'person.invite',{name:'Escalada',cargo:'Bibliotecario/a',accessProfile:'biblioteca'}),/autoridad/);});
