const {setup,fixture,assert,noOverflow,base}=require('./ui-helpers.cjs');
(async()=>{
 const {page,context,go,finish}=await setup();await fixture(page);
 // Only the OCR provider is replaced; acquisition, persistence and proposal extraction are real.
 await context.route('**/src/ocr-provider.js?*',r=>r.fulfill({contentType:'text/javascript',body:`export const ocrProvider={recognize:async(image,{signal,onProgress})=>{onProgress({progress:.5});if(window.ocrWait)return new Promise((_,reject)=>signal.addEventListener('abort',()=>reject(new DOMException('cancelled','AbortError')),{once:true}));return {text:window.ocrText||'',confidence:55,engine:'Deterministic test provider'};}};`}));
 await go('agregar');await page.getByRole('link',{name:'Usar una foto',exact:true}).click();await page.locator('#assist-file').waitFor({state:'attached'});
 const image=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=800;c.height=1000;const x=c.getContext('2d');x.fillStyle='white';x.fillRect(0,0,800,1000);x.fillStyle='black';x.font='32px sans-serif';x.fillText('CUENTOS DE LA SELVA',40,100);return c.toDataURL('image/png').split(',')[1];});
 const upload=async text=>{await page.evaluate(t=>window.ocrText=t,text);await page.locator('#assist-file').setInputFiles({name:'portada.png',mimeType:'image/png',buffer:Buffer.from(image,'base64')});await page.locator('#assist-preview').waitFor();};
 const recognize=async()=>{await page.locator('[data-assist=recognize]').click();await page.getByText(/Propuestas listas/).waitFor();};
 await upload('Cuentos de la selva\nAutor: Horacio Quiroga\nEditorial: Prueba\nISBN: 9505470630\nISBN: 9780140328721');
 await page.locator('[data-assist=rotate]').click();await page.waitForFunction(()=>{const e=document.querySelector('#assist-preview');return e&&e.naturalWidth>e.naturalHeight;});
 await recognize();assert.equal(await page.locator('[data-field=isbn]').count(),2);
 const title=page.locator('[data-field=title]').first();await title.locator('[data-assist=accept]').click();await page.locator('[data-field=title][data-decision=accepted]').waitFor();
 const author=page.locator('[data-field=author]').first();await author.locator('textarea').fill('Horacio Quiroga (revisado)');await author.getByRole('button',{name:'Guardar edición'}).click();await page.locator('[data-field=author][data-decision=edited]').waitFor();
 await page.locator('[data-field=publisher] [data-assist=reject]').click();await page.locator('[data-field=publisher][data-decision=rejected]').waitFor();
 assert.equal(await page.evaluate(async()=> (await(await import('./src/storage.js?v=20261010-rc1')).readState()).books.length),0);
 for(const width of [320,390,768,1440])for(const theme of ['light','dark']){await page.setViewportSize({width,height:900});await page.evaluate(t=>document.documentElement.dataset.theme=t,theme);await noOverflow(page,'assistance '+width+' '+theme);if(width===390)await page.screenshot({path:'qa/assistance-'+theme+'.png',fullPage:true});}
 await page.locator('[data-field=isbn]').filter({hasText:'9789505470631'}).locator('[data-assist=lookup]').click();await page.getByText('Las fuentes agregaron propuestas. Revisá las diferencias antes de aceptar.',{exact:true}).waitFor();assert.ok(await page.locator('[data-field=title]').count()>1);
 await page.locator('[data-assist=apply]').click();await page.locator('#book-form').waitFor();assert.equal(await page.locator('[name=title]').inputValue(),'Cuentos de la selva');assert.equal(await page.locator('[name=author]').inputValue(),'Horacio Quiroga (revisado)');assert.equal(await page.locator('[name=publisher]').inputValue(),'');
 await page.getByRole('button',{name:'Guardar en el catálogo',exact:true}).click();await page.locator('.record-page').waitFor();const bookId=new URL(page.url()).hash.split('/')[1];
 await page.getByRole('link',{name:'Asistir con foto'}).click();await page.locator('#assist-kind').selectOption('index');await upload('Índice\nLa tortuga gigante — Horacio Quiroga .... 12\nLas medias de los flamencos .... 23\nUna fila equivocada .... 40');await recognize();
 await page.locator('[data-field=contentEntries]').last().locator('[data-assist=reject]').click();await page.locator('[data-field=contentEntries][data-decision=rejected]').waitFor();await page.locator('[data-assist=accept-contents]').click();await page.waitForFunction(()=>document.querySelectorAll('[data-field=contentEntries][data-decision=accepted]').length===2);await page.locator('[data-assist=apply]').click();await page.locator('.record-page').waitFor();
 let book=await page.evaluate(async id=>(await(await import('./src/storage.js?v=20261010-rc1')).readState()).books.find(b=>b.id===id),bookId);assert.equal(book.contentEntries.length,2);assert.equal(book.exemplars.length,1);assert.equal(book.enrichment.history.length,2);
 // Newspaper flow creates content suggestions and a literal date, no invented topic.
 await go('asistencia/nueva');await page.locator('#assist-kind').selectOption('newspaper-front');await upload('El Diario\n12 de mayo de 1944\nLas tropas aliadas avanzan en Europa');await recognize();for(const field of ['title','publication','publicationDate','materialType']){await page.locator('[data-field='+field+'] [data-assist=accept]').first().click();await page.locator('[data-field='+field+'][data-decision=accepted]').waitFor();}await page.locator('[data-assist=accept-contents]').click();await page.locator('[data-field=contentEntries][data-decision=accepted]').waitFor();assert.ok(!(await page.locator('#assist-proposals').innerText()).includes('Segunda Guerra Mundial'));await page.locator('[data-assist=apply]').click();await page.locator('#book-form').waitFor();assert.equal(await page.locator('[name=materialType]').inputValue(),'diario');await page.getByRole('button',{name:'Guardar en el catálogo',exact:true}).click();await page.locator('.record-page').waitFor();
 // Journey recovery stays on the same queue item and never creates a ghost book.
 const target=await page.evaluate(async()=>{const st=await import('./src/storage.js?v=20261010-rc1'),j=await st.execute('cataloging.start',{}),i=await st.execute('cataloging.capture',{sessionId:j.id,raw:'ilegible'});return {session:j.id,item:i.id};});
 await go('jornada-catalogacion/'+target.session+'/cola');await page.getByRole('link',{name:'Resolver con foto'}).click();await page.locator('#assist-kind').waitFor();await upload('Libro antiguo sin código');await recognize();await page.locator('[data-field=title] [data-assist=accept]').click();await page.locator('[data-field=title][data-decision=accepted]').waitFor();await page.locator('[data-assist=apply]').click();await page.locator('[data-status=ready-new]').waitFor();assert.equal(await page.evaluate(async()=> (await(await import('./src/storage.js?v=20261010-rc1')).readState()).books.length),2);
 // Missing-metadata item is resolved via a chosen OCR ISBN and bibliographic proposals.
 const missing=await page.evaluate(async sessionId=>{const st=await import('./src/storage.js?v=20261010-rc1'),i=await st.execute('cataloging.capture',{sessionId,raw:'9780306406157'});await st.execute('cataloging.metadata',{sessionId,itemId:i.id,revision:i.revision,book:null});return i.id;},target.session);
 await go('jornada-catalogacion/'+target.session+'/cola');await page.locator('[data-status=metadata-missing]').getByRole('link',{name:'Resolver con foto'}).click();await page.locator('#assist-kind').selectOption('copyright-page');await upload('Página legal\nISBN 9505470630');await recognize();await page.locator('[data-field=isbn] [data-assist=lookup]').click();await page.getByText('Las fuentes agregaron propuestas. Revisá las diferencias antes de aceptar.',{exact:true}).waitFor();await page.locator('[data-field=title]').filter({hasText:'El Hobbit'}).locator('[data-assist=accept]').click();await page.locator('[data-field=title][data-decision=accepted]').waitFor();await page.locator('[data-field=isbn] [data-assist=accept]').first().click();await page.locator('[data-field=isbn][data-decision=accepted]').waitFor();await page.locator('[data-assist=apply]').click();await page.locator('[data-queue-item="'+missing+'"][data-status=ready-new]').waitFor();
 // Cancellation leaves only an active photo, no OCR text or applied metadata.
 await go('asistencia/nueva');await upload('Texto cancelado');await page.evaluate(()=>window.ocrWait=true);await page.locator('[data-assist=recognize]').click();await page.getByText('Leyendo texto… 50%',{exact:true}).waitFor();await page.locator('[data-assist=cancel]').click();await page.getByText('Procesamiento cancelado. La foto sigue disponible.',{exact:true}).waitFor();assert.equal(await page.locator('[data-proposal]').count(),0);
 await page.reload();await page.locator('#assist-preview').waitFor();const state=await page.evaluate(async()=> (await import('./src/storage.js?v=20261010-rc1')).readState());assert.ok(state.assistanceSessions.some(a=>a.status==='active'&&a.image));
 const archive=await page.evaluate(async()=>JSON.stringify(await(await import('./src/storage.js?v=20261010-rc1')).exportArchive()));
 await page.evaluate(async archive=>{const st=await import('./src/storage.js?v=20261010-rc1'),{JsonBackupProvider}=await import('./src/imports.js?v=20261010-rc1');await st.restoreArchive(JsonBackupProvider.parse(archive));},archive);await page.reload();await page.locator('#assist-preview').waitFor();
 await page.evaluate(async()=>{const st=await import('./src/storage.js?v=20261010-rc1'),reader=await st.execute('person.save',{name:'Lector sin permisos',cargo:'Estudiante',accessProfile:'lector',status:'active'});st.setActorId(reader.id);});await go('asistencia');await page.getByRole('heading',{name:'Acceso no habilitado'}).waitFor();
 await finish();console.log('PASS assistance: photo, decisions, index, newspaper, ISBN sources, journey, cancellation, persistence and responsive themes');
})().catch(e=>{console.error(e);process.exit(1);});

