import test from 'node:test';import assert from 'node:assert/strict';
import {extractIdentifiers,parseIndex,proposeFromOCR,suggestKeywords,confirmedPatch} from '../src/assistance.js';
import {STORES,command,normalizeHoldings} from '../src/local-domain.js';
import {validateBook,searchBooks} from '../src/catalog.js';
import {validateAssistanceBackup} from '../src/assistance-domain.js';
const image='data:image/jpeg;base64,/9j/AAAA';
function seed(){const s=Object.fromEntries(STORES.map(k=>[k,[]]));s.patrons=[{id:'admin',role:'bibliotecario',active:true},{id:'reader',role:'alumno',active:true}];normalizeHoldings(s);return s;}
const run=(s,type,data={})=>command(s,'admin','assistance.'+type,data);
const setup=(s,options={},text='Cuentos de la selva\nAutor: Horacio Quiroga')=>{const a=run(s,'start',options);run(s,'image',{id:a.id,image,captureKind:options.captureKind||'cover',materialType:options.materialType||'libro'});run(s,'recognized',{id:a.id,revision:a.revision,text,confidence:58});return a;};
const accept=(s,a,field,value)=>{const p=a.proposals.find(p=>p.field===field&&(value===undefined||p.value===value));assert.ok(p,field);run(s,'decide',{id:a.id,proposalId:p.id,status:'accepted'});return p;};
test('ISBN checksums, canonical equivalence, multiple candidates and OCR letters are never silently repaired',()=>{const ids=extractIdentifiers('ISBN: 950-547-063-0\nISBN-13: 9789505470631\nISBN 9780140328721\nISBN: 950547O630\nISBN 1234567890');assert.deepEqual(ids.isbn,['9789505470631','9780140328721']);assert.ok(ids.invalid.includes('950547O630'));assert.ok(!extractIdentifiers('950547O630').isbn.length);assert.throws(()=>confirmedPatch({},[{field:'isbn',value:'950547O630',status:'edited'}]),/inválido/);});
test('ISSN, DOI and safe URLs are detected without opening links',()=>{const ids=extractIdentifiers('ISSN 0317-8471\nDOI: 10.1000/182\nhttps://example.org/material.\nhttp://user:password@example.org/');assert.deepEqual(ids.issn,['0317-8471']);assert.deepEqual(ids.doi,['10.1000/182']);assert.deepEqual(ids.url,['https://example.org/material']);assert.deepEqual(extractIdentifiers('texto sin identificadores').isbn,[]);});
test('index parses page ranges and visible author, without creating child records',()=>{const rows=parseIndex('Índice\nLa tortuga gigante — Horacio Quiroga .... 12\nLas medias de los flamencos  23-26\nOtro cuento');assert.equal(rows.length,3);assert.equal(rows[0].title,'La tortuga gigante');assert.equal(rows[0].author,'Horacio Quiroga');assert.equal(rows[0].page,'12');assert.equal(rows[1].page,'23-26');assert.equal(rows[2].author,'');assert.match(rows[0].source,/OCR/);});
test('newspaper suggestions use literal words, real dates and no imagined historical topics',()=>{const p=proposeFromOCR('El Diario\n12 de mayo de 1944\nLas tropas aliadas avanzan en Europa',{captureKind:'newspaper-front',knownSubjects:['Segunda Guerra Mundial','Europa']});assert.ok(p.proposals.some(p=>p.field==='publicationDate'&&p.value==='1944-05-12'));assert.ok(p.proposals.some(p=>p.field==='contentEntries'));assert.ok(!JSON.stringify(p).includes('Segunda Guerra Mundial'));assert.ok(!suggestKeywords('para desde sobre tienen estas libro').length);assert.doesNotThrow(()=>proposeFromOCR('Diario\n99/99/2026',{captureKind:'newspaper-front'}));});
test('recognition and decisions persist without changing a book; apply merges selected contents only',()=>{const s=seed();s.books.push(validateBook({title:'Antología',copies:1,contents:['Contenido anterior']}));normalizeHoldings(s);const before=structuredClone(s.books),a=setup(s,{target:'material',materialId:s.books[0].id,captureKind:'index'},'Índice\nLa tortuga gigante .... 12\nOtro cuento .... 30');assert.deepEqual(s.books,before);const first=accept(s,a,'contentEntries');run(s,'decide',{id:a.id,proposalId:first.id,status:'edited',value:{...first.value,title:'La tortuga gigante (revisado)'}});const other=a.proposals.filter(p=>p.field==='contentEntries')[1];run(s,'decide',{id:a.id,proposalId:other.id,status:'rejected'});assert.deepEqual(s.books,before);run(s,'apply',{id:a.id,confirmed:true});assert.equal(s.books.length,1);assert.equal(s.books[0].contentEntries.length,2);assert.deepEqual(s.books[0].exemplars,before[0].exemplars);assert.equal(searchBooks(s.books,'tortuga').length,1);assert.equal(a.image,'');assert.equal(a.text,'');assert.equal(s.books[0].enrichment.history.length,1);assert.equal(s.books[0].sources.length,0);run(s,'apply',{id:a.id,confirmed:true});assert.equal(s.books[0].contentEntries.length,2);});
test('new assisted draft requires confirmation and remains outside catalog',()=>{const s=seed(),a=setup(s);accept(s,a,'title');accept(s,a,'author');assert.throws(()=>run(s,'apply',{id:a.id}),/Confirmá/);const result=run(s,'apply',{id:a.id,confirmed:true});assert.equal(result.result.draft.title,'Cuentos de la selva');assert.equal(s.books.length,0);assert.equal(result.result.draft.enrichment.history[0].proposals.length,2);});
test('invalid journey item can become manually reviewed without inventing an ISBN',()=>{const s=seed(),j=command(s,'admin','cataloging.start'),i=command(s,'admin','cataloging.capture',{sessionId:j.id,raw:'unreadable'}),a=setup(s,{target:'item',sessionId:j.id,itemId:i.id});accept(s,a,'title');run(s,'apply',{id:a.id,confirmed:true});assert.equal(i.status,'ready-new');assert.equal(i.isbn,'');assert.ok(i.manualReviewed);assert.equal(s.books.length,0);});
test('stale target, closed journey and expired permissions block changes',()=>{const s=seed();s.books.push(validateBook({title:'Antes',copies:0}));const a=setup(s,{target:'material',materialId:s.books[0].id});accept(s,a,'title');s.books[0].title='Cambio posterior';assert.throws(()=>run(s,'apply',{id:a.id,confirmed:true}),/Cambió/);assert.equal(s.books[0].title,'Cambio posterior');assert.throws(()=>command(s,'reader','assistance.start',{}),/permiso/);});
test('source metadata is proposed, not automatically accepted, and selected provenance stays bibliographic',()=>{const s=seed(),a=setup(s,{},'Cuentos\nISBN 9505470630');const p=a.proposals.find(p=>p.field==='isbn');run(s,'sources',{id:a.id,revision:a.revision,proposalId:p.id,book:{title:'El Hobbit',isbn:'9505470630',sources:['Open Library'],fieldSources:{title:'Open Library'},sourceRecords:[{source:'Open Library'}]}});assert.ok(a.proposals.every(p=>p.status==='proposed'));accept(s,a,'title','El Hobbit');const r=run(s,'apply',{id:a.id,confirmed:true});assert.equal(r.result.draft.fieldSources.title,'Open Library');assert.equal(s.books.length,0);});
test('backup preserves active assistance while discard removes photo and unconfirmed personal text',()=>{const s=seed(),a=setup(s);validateAssistanceBackup(JSON.parse(JSON.stringify(s.assistanceSessions)));run(s,'discard',{id:a.id});assert.equal(a.image,'');assert.equal(a.text,'');assert.equal(a.proposals.length,0);const bad={...a,image:'https://external/photo'};assert.throws(()=>validateAssistanceBackup([bad]),/inválida/);});
test('selecting a second scalar candidate rejects the first explicitly and low confidence stays visible',()=>{const s=seed(),a=setup(s,{},'Primera línea\nTítulo: Título explícito');const first=accept(s,a,'title','Primera línea'),second=accept(s,a,'title','Título explícito');assert.equal(first.status,'rejected');assert.equal(second.status,'accepted');assert.equal(second.confidence,58);});

test('school production does not propose student author names or arbitrary name keywords',()=>{const p=proposeFromOCR('Proyecto del aula\nAutor: Nombre Apellido\nNuestro cuento — Nombre Apellido 12',{captureKind:'index',materialType:'produccion',knownSubjects:['Proyecto']});assert.ok(!p.proposals.some(p=>p.field==='author'));assert.ok(p.proposals.filter(p=>p.field==='contentEntries').every(p=>!p.value.author));assert.ok(p.proposals.filter(p=>p.field==='subjects').every(p=>p.value==='Proyecto'));});
test('content-only grant cannot apply title edits, and stale OCR response cannot overwrite review',()=>{const s=seed();s.books.push(validateBook({title:'Antología',copies:0}));s.grants.push({id:'grant',userId:'reader',permission:'contents.manage',active:true,expiresAt:'2099-01-01'});const a=setup(s,{target:'material',materialId:s.books[0].id,captureKind:'index'},'Índice\nCuento .... 2');const revision=a.revision;accept(s,a,'contentEntries');run(s,'recognized',{id:a.id,revision,text:'Late wrong title'});assert.equal(a.proposals.find(p=>p.field==='contentEntries').status,'accepted');command(s,'reader','assistance.apply',{id:a.id,confirmed:true});assert.equal(s.books[0].contentEntries.length,1);const b=setup(s,{target:'material',materialId:s.books[0].id});accept(s,b,'title');assert.throws(()=>command(s,'reader','assistance.apply',{id:b.id,confirmed:true}),/permiso/);assert.equal(s.books[0].title,'Antología');});

test('magazine and document proposals keep only explicit publication data and identifiers',()=>{const magazine=proposeFromOCR('Revista Ciencia\nISSN 0317-8471\nVolumen: 12\nNúmero: 4\n10/05/2024\nLos bosques de nuestra región',{captureKind:'magazine-cover'}).proposals;for(const [field,value] of [['publication','Revista Ciencia'],['issn','0317-8471'],['volume','12'],['issueNumber','4'],['publicationDate','2024-05-10']])assert.ok(magazine.some(p=>p.field===field&&p.value===value),field);const doc=proposeFromOCR('Plan de lectura\nOrganismo: Biblioteca Escolar\nDocumento: 24/2024\nhttps://example.org/plan\nDOI: 10.1000/182',{captureKind:'document'}).proposals;assert.ok(doc.some(p=>p.field==='issuingBody'&&p.value==='Biblioteca Escolar'));assert.ok(doc.some(p=>p.field==='documentNumber'&&p.value==='24/2024'));assert.ok(!doc.some(p=>p.field==='author'));assert.ok(doc.some(p=>p.field==='resourceUrl'));});
