import test from 'node:test';
import assert from 'node:assert/strict';
import {STORES,command,normalizeHoldings} from '../src/local-domain.js';
import {catalogingCommand,classifyCapture,planCataloging,catalogingSummary,validateCatalogingBackup} from '../src/cataloging.js';
import {validateBook} from '../src/catalog.js';
import {canonicalISBN} from '../src/isbn.js';
import {JsonBackupProvider} from '../src/imports.js';
const isbn='9505470630',isbn2='9780140328721';
function seed(){const s=Object.fromEntries(STORES.map(k=>[k,[]]));s.patrons=[{id:'admin',name:'Biblioteca',role:'bibliotecario',active:true},{id:'teacher',name:'Docente',role:'docente',active:true}];normalizeHoldings(s);return s;}
const run=(s,type,data={},actor='admin')=>command(s,actor,'cataloging.'+type,data);
const session=s=>s.catalogingSessions[0];
function capture(s,raw=isbn){return run(s,'capture',{sessionId:session(s).id,raw});}
function metadata(s,item,title='El Hobbit',extra={}){return run(s,'metadata',{sessionId:session(s).id,itemId:item.id,revision:item.revision,book:{title,isbn:item.isbn,...extra}});}
function batch(s,ids= session(s).items.filter(i=>i.status!=='incorporated').map(i=>i.id)){const j=session(s),p=planCataloging(s,j,ids);return {sessionId:j.id,ids,signature:p.signature,batchId:crypto.randomUUID()};}
test('one active session survives serialization and cancellation preserves catalog and trace',()=>{const s=seed(),j=run(s,'start');assert.equal(run(s,'start').id,j.id);capture(s);const resumed=JSON.parse(JSON.stringify(s));assert.equal(run(resumed,'start').id,j.id);const before=JSON.stringify(s.books);assert.throws(()=>run(s,'cancel',{sessionId:j.id}),/Confirmá/);run(s,'cancel',{sessionId:j.id,confirmed:true});assert.equal(JSON.stringify(s.books),before);assert.equal(j.captures.length,1);assert.equal(j.status,'cancelled');assert.notEqual(run(s,'start').id,j.id);validateCatalogingBackup(s.catalogingSessions);});
test('equivalent ISBN captures create one edition and several copies only after incorporation',()=>{const s=seed();run(s,'start');const item=capture(s);capture(s,canonicalISBN(isbn));capture(s,'950-547-063-0');assert.equal(session(s).items.length,1);assert.equal(item.quantity,3);assert.equal(s.books.length,0);metadata(s,item);assert.equal(item.status,'ready-new');const data=batch(s);run(s,'incorporate',data);run(s,'incorporate',data);assert.equal(s.books.length,1);assert.equal(s.books[0].exemplars.length,3);assert.equal(new Set(s.books[0].exemplars.map(e=>e.internalCode)).size,3);assert.deepEqual(catalogingSummary(session(s)),{captures:3,newEditions:1,newCopies:3,addedCopies:0,duplicatesAvoided:2,pending:0,missing:0,invalid:0});});
test('existing edition preserves bibliography and previous copies; AB sequence grows beyond six digits',()=>{const s=seed();s.books.push(validateBook({title:'Original',isbn,copies:1}));normalizeHoldings(s);const existing=structuredClone(s.books[0]);s.settings.find(x=>x.id==='local').sequence=1000000;run(s,'start');const item=capture(s,canonicalISBN(isbn));assert.equal(item.status,'existing-edition');run(s,'common',{sessionId:session(s).id,ids:[item.id],common:{location:'Sala A',condition:'Regular',quantity:2}});run(s,'incorporate',batch(s));assert.equal(s.books.length,1);assert.equal(s.books[0].title,'Original');assert.deepEqual(s.books[0].exemplars[0],existing.exemplars[0]);assert.deepEqual(s.books[0].exemplars.slice(1).map(e=>e.internalCode),['AB-1000000','AB-1000001']);assert.ok(s.books[0].exemplars.slice(1).every(e=>e.location==='Sala A'&&e.condition==='Regular'));assert.equal(catalogingSummary(session(s)).addedCopies,2);});
test('same work needs an explicit decision and source conflicts never invent metadata',()=>{const s=seed();s.books.push(validateBook({title:'El Hobbit',author:'Tolkien',isbn,copies:0}));normalizeHoldings(s);run(s,'start');const item=capture(s,isbn2);metadata(s,item,'El Hobbit',{author:'Tolkien'});assert.equal(item.status,'same-work');assert.throws(()=>batch(s),/pendientes/);run(s,'review',{sessionId:session(s).id,itemId:item.id,fields:item.draft,quantity:1,resolution:'link-work',workId:s.books[0].workId});run(s,'incorporate',batch(s));assert.equal(s.books[0].workId,s.books[1].workId);assert.notEqual(s.books[0].editionId,s.books[1].editionId);assert.equal(classifyCapture([],{source:'manual',isbn,draft:{title:'Fuentes distintas',conflicts:[{field:'title'}]}}).status,'needs-review');});
test('invalid and missing metadata stay out of catalog; unsafe common fields are rejected',()=>{const s=seed();run(s,'start');assert.equal(capture(s,'not an isbn').status,'invalid');const item=capture(s);run(s,'metadata',{sessionId:session(s).id,itemId:item.id,book:null});assert.equal(item.status,'metadata-missing');assert.throws(()=>batch(s),/pendientes/);assert.throws(()=>run(s,'common',{sessionId:session(s).id,ids:[item.id],common:{title:'Overwrite'}}),/físicos/);assert.equal(s.books.length,0);});
test('preview detects changes; permission failure rolls back the whole batch',()=>{const s=seed();run(s,'start');const a=capture(s);metadata(s,a);const b=capture(s,isbn2);metadata(s,b,'Matilda');const old=batch(s);capture(s);assert.throws(()=>run(s,'incorporate',old),/Cambió/);s.grants.push({id:'g',userId:'teacher',permission:'catalog.create',active:true});const current=batch(s),before=JSON.stringify(s);assert.throws(()=>run(s,'incorporate',current,'teacher'),/permiso/);assert.equal(JSON.stringify(s),before);s.grants.push({id:'h',userId:'teacher',permission:'holdings.create',active:true,expiresAt:'2099-01-01'});run(s,'incorporate',current,'teacher');assert.equal(s.books.length,2);assert.equal(s.patrons[1].role,'docente');});
test('grant for holdings allows only adding copies, and expired grants do not permit capture',()=>{const s=seed();s.books.push(validateBook({title:'Existing',isbn,copies:0}));normalizeHoldings(s);s.grants.push({id:'h',userId:'teacher',permission:'holdings.create',active:true,expiresAt:'2099-01-01'});run(s,'start',{},'teacher');capture(s);run(s,'incorporate',batch(s),'teacher');const i=capture(s,isbn2);metadata(s,i,'New title');assert.throws(()=>run(s,'incorporate',batch(s),'teacher'),/permiso/);s.grants[0].expiresAt='2000-01-01';assert.throws(()=>run(s,'capture',{sessionId:session(s).id,raw:isbn},'teacher'),/permiso/);});
test('MARC001 with conflicting ISBN requires manual correction, reimport never duplicates origin copies',()=>{const s=seed();s.books.push(validateBook({title:'Original',isbn,identifiers:{marc001:'001'},copies:0}));normalizeHoldings(s);assert.equal(classifyCapture(s.books,{source:'marc',isbn:isbn2,draft:{title:'Different',isbn:isbn2,identifiers:{marc001:'001'}}}).status,'needs-review');run(s,'start');const draft={title:'Original',isbn,identifiers:{marc001:'001'},copies:1,exemplars:[{inventoryCode:'INV-1',condition:'Bueno'}]};run(s,'import',{sessionId:session(s).id,entries:[{draft}]});run(s,'import',{sessionId:session(s).id,entries:[{draft}]});assert.equal(session(s).items[0].quantity,1);run(s,'incorporate',batch(s));run(s,'import',{sessionId:session(s).id,entries:[{draft}]});assert.equal(planCataloging(s,session(s),[session(s).items[1].id]).newCopies,0);run(s,'incorporate',batch(s));assert.equal(s.books[0].exemplars.length,1);});
test('backup accepts persistent sessions and rejects malformed items; old backup stays compatible',()=>{const s=seed();run(s,'start');capture(s);const archive={...s,app:'asistente-bibliotecario',version:4};assert.equal(JsonBackupProvider.parse(JSON.stringify(archive)).catalogingSessions.length,1);delete archive.catalogingSessions;assert.deepEqual(JsonBackupProvider.parse(JSON.stringify(archive)).catalogingSessions,[]);session(s).items[0].quantity=-1;assert.throws(()=>validateCatalogingBackup(s.catalogingSessions),/inválido/);});
test('configured common locations resolve hierarchy and no holdings.edit grant is needed for new copies',()=>{const s=seed();s.libraryLocations=[{id:'sec',name:'Lectura',type:'sector'},{id:'sh',name:'A',type:'shelving',parentId:'sec'},{id:'sl',name:'1',type:'shelf',parentId:'sh'}];run(s,'start');const i=capture(s);metadata(s,i);run(s,'common',{sessionId:session(s).id,ids:[i.id],common:{locationId:'sl'}});run(s,'incorporate',batch(s));assert.equal(s.books[0].exemplars[0].physicalLocation.shelfId,'sl');});

test('similar records require review, and explicit distinct edition preserves source provenance',()=>{const s=seed();s.books.push(validateBook({title:'Historia del arte moderno europeo',author:'Autora',isbn,copies:0}));run(s,'start');const i=capture(s,isbn2);metadata(s,i,'Historia del arte moderno',{author:'Autora',sources:['Open Library'],fieldSources:{title:'Open Library'},sourceRecords:[{source:'Open Library',data:{title:'Original'}}]});assert.equal(i.status,'similar');run(s,'review',{sessionId:session(s).id,itemId:i.id,fields:{title:'Historia del arte moderno'},quantity:1,resolution:'new'});run(s,'incorporate',batch(s));assert.equal(s.books[1].sourceRecords.length,1);assert.equal(s.books[1].fieldSources.title,'Open Library');});
test('exceptions after an earlier row was processed still roll back every row and sequence',()=>{const s=seed();run(s,'start');metadata(s,capture(s),'Hobbit');metadata(s,capture(s,isbn2),'Matilda');const data=batch(s),before=JSON.stringify(s);let count=0;assert.throws(()=>catalogingCommand(s,'admin','incorporate',data,{audit:()=>{},normalizeHoldings:state=>{normalizeHoldings(state);if(++count===2)throw new Error('Injected storage failure');}}),/Injected/);assert.equal(JSON.stringify(s),before);});

test('correcting an ISBN updates the grouping key for subsequent scans',()=>{const s=seed();run(s,'start');const i=capture(s);run(s,'review',{sessionId:session(s).id,itemId:i.id,fields:{isbn:isbn2,title:'Matilda'},quantity:1,resolution:'new'});capture(s,isbn2);assert.equal(i.quantity,2);capture(s,isbn);assert.equal(session(s).items.length,2);assert.equal(i.quantity,2);});
