const {setup,fixture,lookup,save,noOverflow,assert,base,fs}=require('./ui-helpers.cjs');
(async()=>{
 const {page,go,finish}=await setup({deviceScaleFactor:1});await fixture(page);
 // Public page is a separate experience and never initializes the catalog DB.
 await page.addInitScript(()=>{window.dbOpens=0;const open=IDBFactory.prototype.open;IDBFactory.prototype.open=function(...args){window.dbOpens++;return open.apply(this,args);};});
 await page.goto(base);await page.locator('.landing-hero').waitFor();assert.equal(await page.evaluate(()=>window.dbOpens),0);assert.equal(await page.locator('.sidebar').count(),0);
 for(const theme of ['light','dark']){await page.evaluate(t=>document.documentElement.dataset.theme=t,theme);for(const width of [320,360,390,430,768,1440]){await page.setViewportSize({width,height:900});await noOverflow(page,`landing ${theme} ${width}`);await page.screenshot({path:`qa/landing-${theme}-${width}.png`,fullPage:true});}}
 await page.setViewportSize({width:390,height:844});await page.locator('#menu-toggle').click();assert.equal(await page.locator('#menu-toggle').getAttribute('aria-expanded'),'true');await page.locator('#resources-menu-toggle').click();await page.locator('#resources-menu a[href="#recursos"]').click();assert.equal(await page.locator('#menu-toggle').getAttribute('aria-expanded'),'false');await page.locator('[data-theme-toggle]').click();const theme=await page.evaluate(()=>document.documentElement.dataset.theme);await go('inicio');assert.equal(await page.evaluate(()=>document.documentElement.dataset.theme),theme);assert.equal(await page.locator('.hero').count(),0);
 await go('agregar');await lookup(page);await page.locator('#confirm-isbn').click();assert.equal(await page.locator('.bibliographic-fields').getAttribute('open'),null);await page.locator('[name=copies]').fill('2');await save(page);const hash=new URL(page.url()).hash.slice(1);
 await page.locator('#photo-copy').selectOption({index:1});const copyId=await page.locator('#photo-copy').inputValue();await page.locator('.copy-editor summary').click();await page.locator('#copy-form [name=location]').fill('Sala docente');await page.locator('#copy-form [name=inventoryCode]').fill('ESC-002');await page.getByRole('button',{name:'Guardar ejemplar',exact:true}).click();await page.getByText('Ejemplar actualizado.',{exact:true}).waitFor();await page.reload();await page.locator('#copy-form').waitFor({state:'attached'});await page.locator('#photo-copy').selectOption(copyId);assert.equal(await page.locator('#copy-form [name=location]').inputValue(),'Sala docente');
 const makeFile=async color=>{const bytes=await page.evaluate(color=>{const c=document.createElement('canvas');c.width=120;c.height=180;const x=c.getContext('2d');x.fillStyle=color;x.fillRect(0,0,120,180);return c.toDataURL('image/png').split(',')[1];},color);return {name:'copy.png',mimeType:'image/png',buffer:Buffer.from(bytes,'base64')};};
 const upload=async file=>{const chooser=page.waitForEvent('filechooser');await page.getByRole('button',{name:'Elegir archivo'}).click();await(await chooser).setFiles(file);};
 await upload(await makeFile('#3981F7'));await page.locator('.photo-thumbnail').waitFor();const original=await page.locator('.photo-thumbnail img').getAttribute('src');await upload(await makeFile('#51C6FB'));await page.locator('#confirm-cancel').click();assert.equal(await page.locator('.photo-thumbnail img').getAttribute('src'),original);
 await upload(await makeFile('#51C6FB'));await page.locator('#confirm-accept').click();await page.waitForFunction(old=>document.querySelector('.photo-thumbnail img')?.src!==old,original);
 await page.getByRole('button',{name:'Borrar fotografía',exact:true}).click();await page.locator('#confirm-cancel').click();assert.equal(await page.locator('.photo-thumbnail').count(),1);await page.getByRole('button',{name:'Borrar fotografía',exact:true}).click();await page.locator('#confirm-accept').click();await page.locator('.photo-thumbnail').waitFor({state:'detached'});
 await upload(await makeFile('#3981F7'));await page.locator('.photo-thumbnail').waitFor();await page.getByRole('button',{name:'Eliminar ejemplar',exact:true}).click();await page.locator('#confirm-accept').click();await page.waitForFunction(()=>document.querySelectorAll('#photo-copy option').length===1);assert.equal(await page.locator('.photo-thumbnail').count(),0);
 await page.getByRole('button',{name:'Eliminar ejemplar',exact:true}).click();await page.locator('#confirm-accept').click();await page.waitForFunction(()=>document.querySelectorAll('#photo-copy option').length===0);await page.reload();await page.locator('.record-page').waitFor();assert.equal(await page.locator('#photo-copy option').count(),0);assert.ok(await page.getByRole('button',{name:'Sacar foto'}).isDisabled());
 await page.evaluate(async()=>{const db=await import('./src/storage.js?v=20261010-4');await db.execute('onboarding.library',{libraryName:'Biblioteca',responsible:'self'});});await go('inicio');await page.locator('#home-query').fill('Hobbit');await page.locator('#home-search button').click();await page.locator('.book-card').waitFor();assert.equal(await page.locator('.book-card').count(),1);
 await page.goto(base+'#'+hash);await page.locator('.record-page').waitFor();assert.ok(page.url().includes('app.html#ficha/'));
 await finish();console.log('PASS: public/app separation without DB access on landing, responsive public light/dark, mobile menu, shared theme, assisted form, individual copy edit, photo replacement/deletion/cancel, last-copy deletion preserving edition, search-first home, legacy links.');
})().catch(e=>{console.error(e);process.exit(1)});
