const {setup,save,assert,base,noOverflow}=require('./ui-helpers.cjs');
(async()=>{const {page,go,finish}=await setup({deviceScaleFactor:1});
 await go('agregar');await page.getByRole('button',{name:'No puedo usar la cámara'}).click();await page.getByRole('button',{name:'Incorporar manualmente'}).click();await page.locator('[name=title]').fill('Libro de circulación');await page.locator('[name=copies]').fill('2');await save(page);
 await go('usuarios');await page.locator('[data-access-form="person.save"] [name=name]').fill('Docente suplente');await page.locator('[data-access-form="person.save"] [name=course]').fill('5° B');await page.locator('[data-access-form="person.save"] button').click();await page.getByRole('link',{name:'Editar persona'}).last().waitFor();
 const state=()=>page.evaluate(async()=>await(await import('./src/storage.js?v=20261010-1')).readState());let s=await state(),teacher=s.patrons.find(u=>u.name==='Docente suplente'),book=s.books[0],copy=book.exemplars[0];assert.match(copy.internalCode,/^AB-\d{6}$/);
 await page.locator('#app-menu-toggle').click();await page.locator('#local-actor').selectOption(teacher.id);await page.getByRole('heading',{name:'Acceso no habilitado'}).waitFor();await page.goto(base+'app.html#agregar');await page.getByRole('heading',{name:'Acceso no habilitado'}).waitFor();
 await page.locator('#app-menu-toggle').click();await page.locator('#local-actor').selectOption('local-admin');await go('permisos/'+teacher.id);await page.locator('[data-access-form="grant.add"] [name=permission]').selectOption('catalog.create');await page.locator('[data-access-form="grant.add"] button').click();await page.getByRole('button',{name:'Revocar permiso'}).waitFor();await go('permisos/'+teacher.id);await page.locator('[data-access-form="grant.add"] [name=permission]').selectOption('holdings.create');await page.locator('[data-access-form="grant.add"] button').click();await page.getByText('Guardado en este navegador.',{exact:true}).waitFor();
 await go('ejemplar/'+copy.id);await page.locator('#local-copy [name=sector]').fill('Infantil');await page.locator('#local-copy [name=shelving]').fill('Estantería 3');await page.locator('#local-copy [name=shelf]').fill('Estante B');await page.locator('#local-copy button').click();await page.getByText('Operación guardada.',{exact:true}).waitFor();await page.reload();await page.locator('#local-copy').waitFor();assert.equal(await page.locator('[name=shelf]').inputValue(),'Estante B');
 await go('circulacion/'+copy.id);assert.equal(await page.locator('#local-loan [name=exemplarId]').inputValue(),copy.id);await page.locator('#local-loan [name=patronId]').selectOption(teacher.id);await page.locator('#local-loan [name=dueAt]').fill('2030-12-01');await page.locator('#local-loan button').click();await page.getByRole('button',{name:'Registrar devolución'}).waitFor();await page.reload();await page.getByRole('button',{name:'Registrar devolución'}).waitFor();
 assert.equal((await state()).loans.filter(l=>l.status==='loaned').length,1);const blocked=await page.evaluate(async()=>{const m=await import('./src/storage.js?v=20261010-1');const s=await m.readState();try{await m.deleteBook(s.books[0].id);return false;}catch(e){return e.message;}});assert.match(blocked,/devolución/);
 await page.getByRole('button',{name:'Registrar devolución'}).click();await page.waitForFunction(()=>!document.querySelector('#local-return'));
 await page.locator('#local-reserve [name=bookId]').selectOption(book.id);await page.locator('#local-reserve [name=patronId]').selectOption(teacher.id);await page.locator('#local-reserve button').click();await page.locator('#local-reservation').waitFor();await page.locator('#local-reservation [name=exemplarId]').selectOption(copy.id);await page.locator('#local-reservation button').click();await page.getByRole('button',{name:'Lista para retirar',exact:true}).click();await page.getByRole('button',{name:'Retirar y prestar'}).waitFor();const reserveForm=page.locator('form').filter({has:page.getByRole('button',{name:'Retirar y prestar'})});await reserveForm.locator('[name=dueAt]').fill('2030-12-01');await reserveForm.locator('button').click();await page.getByRole('button',{name:'Registrar devolución'}).click();await page.waitForFunction(()=>!document.querySelector('#local-return'));assert.equal((await state()).reservations[0].status,'collected');
 await go('etiquetas/'+copy.id);await page.locator('.label-qr svg').waitFor();await page.locator('.label-bars rect').first().waitFor();const decoded=await page.evaluate(async()=>{const qr=document.querySelector('.label-qr svg');const image=new Image();image.src='data:image/svg+xml;base64,'+btoa(new XMLSerializer().serializeToString(qr));await image.decode();const detector=await(await import('./src/labels.js?v=20261010-1')).internalDetector();return (await detector.detect(image))[0]?.rawValue;});assert.equal(decoded,copy.internalCode);
 const barcode=await page.evaluate(async()=>{const svg=document.querySelector('.label-bars'),image=new Image();image.src='data:image/svg+xml;base64,'+btoa(new XMLSerializer().serializeToString(svg));await image.decode();return (await(await(await import('./src/labels.js?v=20261010-1')).internalDetector()).detect(image))[0]?.rawValue;});assert.equal(barcode,copy.internalCode);
 const linked=await page.evaluate(async()=>{const m=await import('./src/storage.js?v=20261010-1'),s=await m.readState(),original=s.books[0],second={...structuredClone(original),id:'second-edition',editionId:'second-edition',isbn:'',publisher:'Otra editorial',exemplars:[]};await m.saveBook(second);second.title='Obra compartida';await m.saveBook(second);return (await m.readState()).books.map(b=>({title:b.title,workId:b.workId,copies:b.exemplars.length}));});assert.equal(linked[0].title,'Obra compartida');assert.equal(linked[0].workId,linked[1].workId);assert.equal(linked[0].copies,2);assert.equal(linked[1].copies,0);

 // Competing writes from two module calls serialize within IDB.
 const results=await page.evaluate(async({id,patronId})=>{const m=await import('./src/storage.js?v=20261010-1');return (await Promise.allSettled([m.execute('loan.create',{exemplarId:id,patronId,dueAt:'2030-12-01'}),m.execute('loan.create',{exemplarId:id,patronId,dueAt:'2030-12-01'})])).map(r=>r.status);},{id:copy.id,patronId:teacher.id});assert.deepEqual(results.sort(),['fulfilled','rejected']);
 await go('circulacion');await page.getByRole('button',{name:'Registrar devolución'}).click();await page.waitForFunction(()=>!document.querySelector('#local-return'));
 const archive=await page.evaluate(async()=>await(await import('./src/storage.js?v=20261010-1')).exportArchive());assert.equal(archive.version,5);assert.equal(archive.loans.length,3);await page.evaluate(async raw=>{const m=await import('./src/storage.js?v=20261010-1'),p=await import('./src/imports.js?v=20261010-1');await m.clearCatalog();await m.restoreArchive(p.JsonBackupProvider.parse(JSON.stringify(raw)));},archive);await page.reload();await page.getByRole('heading',{name:'Circulación',exact:true}).waitFor();assert.equal((await state()).books[0].exemplars[0].internalCode,copy.internalCode);
 for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:900});for(const route of ['usuarios','permisos/'+teacher.id,'circulacion','organizacion','actividad','ejemplar/'+copy.id,'etiquetas/'+copy.id]){await go(route);await noOverflow(page,width+' '+route);}}
 await finish();console.log('PASS local users, granular permissions, copy locations, circulation, reservations, concurrent loan guard, QR and Code128 decode, shared work editions, full backup restore and responsive screens');
})().catch(e=>{console.error(e);process.exit(1)});
