const {setup,save,assert,base}=require('./ui-helpers.cjs');
(async()=>{
 const {page,go,finish}=await setup();await page.route(base+'seed-migration',r=>r.fulfill({contentType:'text/html',body:'<!doctype html><title>Migration fixture</title>'}));await page.goto(base+'seed-migration');
 const original={id:'existing-book',title:'El Hobbit',author:'J.R.R. Tolkien',isbn:'9505470630',copies:1,category:'Otros',location:'Estante del usuario',condition:'Regular',contents:[],sources:['Open Library'],subjects:['Fantasy','Novels'],schemaVersion:2,workId:'existing-work',editionId:'existing-edition',exemplars:[{id:'existing-copy',location:'Estante del usuario',condition:'Regular'}],createdAt:'2026-10-04T18:00:00Z'};
 await page.evaluate(book=>new Promise((resolve,reject)=>{const r=indexedDB.open('asistente-bibliotecario',1);r.onupgradeneeded=()=>r.result.createObjectStore('books',{keyPath:'id'});r.onsuccess=()=>{const db=r.result,tx=db.transaction('books','readwrite');tx.objectStore('books').put(book);tx.oncomplete=()=>{db.close();resolve();};tx.onerror=()=>reject(tx.error);};}),original);
 await go('ficha/existing-book');await page.locator('.record-page').waitFor();await page.getByRole('link',{name:'Editar registro',exact:true}).click();assert.equal(await page.locator('[name=category]').inputValue(),'Novela');await save(page);
 const books=await page.evaluate(async()=>{const s=await import('./src/storage.js?v=20261010-7');return await s.getBooks();});assert.equal(books[0].id,original.id);assert.equal(books[0].exemplars[0].id,'existing-copy');assert.equal(books[0].location,original.location);assert.equal(books[0].sourceSubjects.length,original.subjects.length);assert.equal(books[0].workId,original.workId);
 await finish();console.log('PASS: IndexedDB v1 migration preserves existing record, work and copy IDs, location and original subjects.');
})().catch(e=>{console.error(e);process.exit(1)});
