const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict');const fs=require('node:fs');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'msedge'});const context=await browser.newContext({viewport:{width:390,height:844},acceptDownloads:true});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('https://www.googleapis.com/books/v1/**',r=>r.fulfill({json:{}}));await page.route('https://openlibrary.org/api/books?**',r=>r.fulfill({json:(()=>{const d=JSON.parse(fs.readFileSync('tests/fixtures/hobbit.json','utf8').replace(/^\uFEFF/,''));d['ISBN:9789505470631']=d['ISBN:9505470630'];return d;})()}));
 await page.addInitScript(()=>{
  Object.defineProperty(window,'BarcodeDetector',{value:undefined,configurable:true});
  navigator.mediaDevices.getUserMedia=async()=>{
   window.cameraCalls=(window.cameraCalls||0)+1;
   const L=['0001101','0011001','0010011','0111101','0100011','0110001','0101111','0111011','0110111','0001011'];const G=['0100111','0110011','0011011','0100001','0011101','0111001','0000101','0010001','0001001','0010111'];const P=['LLLLLL','LLGLGG','LLGGLG','LLGGGL','LGLLGG','LGGLLG','LGGGLL','LGLGLG','LGLGGL','LGGLGL'];const value='9789505470631';
   let bits='101';for(let i=1;i<=6;i++)bits+=(P[Number(value[0])][i-1]==='L'?L:G)[Number(value[i])];bits+='01010';for(let i=7;i<13;i++)bits+=L[Number(value[i])].split('').map(b=>b==='0'?'1':'0').join('');bits+='101';
   const canvas=document.createElement('canvas');canvas.width=720;canvas.height=360;const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,720,360);ctx.fillStyle='#000';[...bits].forEach((b,i)=>{if(b==='1')ctx.fillRect(75+i*6,30,6,300);});
   const stream=canvas.captureStream(10);window.testStream=stream;window.testCanvas=canvas;return stream;
  };
 });
 await page.goto('http://127.0.0.1:4173');await page.getByRole('button',{name:'Agregar mi primer libro'}).click();await page.getByRole('button',{name:'Escanear con cámara'}).click();await page.getByRole('button',{name:'Confirmar libro',exact:true}).waitFor({timeout:15000});
 assert.equal(await page.locator('#isbn-query').inputValue(),'9789505470631');assert.equal(await page.evaluate(()=>window.cameraCalls),1);assert.ok(await page.evaluate(()=>window.testStream.getTracks().every(t=>t.readyState==='ended')));
 // The ISBN-13 scan route uses the same edition; fixture lookup keyed with 10-digit form below.
 await page.locator('#isbn-query').fill('950-547-063-0');await page.getByRole('button',{name:'Buscar ISBN',exact:true}).click();await page.getByRole('button',{name:'Confirmar libro',exact:true}).waitFor();
 assert.equal(await page.locator('#lookup-result > .subject-chips span').count(),4);await page.getByRole('button',{name:'Confirmar libro',exact:true}).click();assert.equal(await page.locator('[name=category]').inputValue(),'Novela');assert.equal(await page.locator('#optional-contents').getAttribute('open'),null);await page.locator('[name=copies]').fill('2');await page.getByRole('button',{name:'Guardar libro',exact:true}).click();await page.getByRole('button',{name:'Ver El Hobbit / The Hobbit',exact:true}).click();
 await page.getByRole('button',{name:'Ampliar portada',exact:true}).click();assert.ok((await page.locator('#large-image').getAttribute('src')).includes('1052113'));await page.getByRole('button',{name:'Cerrar imagen'}).click();
 const img=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=220;c.height=300;const x=c.getContext('2d');x.fillStyle='#63865b';x.fillRect(0,0,220,300);x.fillStyle='white';x.font='20px sans-serif';x.fillText('Ejemplar de prueba',12,150);return c.toDataURL('image/png').split(',')[1];});fs.writeFileSync('qa/test-copy.png',Buffer.from(img,'base64'));
 // File chooser button selects a specific physical copy, not a generic cover.
 await page.locator('#photo-copy').selectOption({index:1});const chooser=page.waitForEvent('filechooser');await page.getByRole('button',{name:'Elegir foto',exact:true}).click();await (await chooser).setFiles('qa/test-copy.png');await page.getByRole('button',{name:'Ampliar foto de tu ejemplar'}).waitFor();await page.getByRole('button',{name:'Ampliar foto de tu ejemplar'}).click();assert.ok((await page.locator('#large-image').getAttribute('src')).startsWith('data:image/jpeg;base64,'));await page.getByRole('button',{name:'Cerrar imagen'}).click();
 await page.locator('#photo-copy').selectOption({index:0});assert.equal(await page.locator('.photo-thumbnail').count(),0);await page.locator('#detail button.close').click();await page.reload();await page.getByRole('button',{name:'Ver El Hobbit / The Hobbit',exact:true}).click();await page.locator('#photo-copy').selectOption({index:1});await page.getByRole('button',{name:'Ampliar foto de tu ejemplar'}).waitFor();
 for(const width of [320,390,740,1440]){await page.setViewportSize({width,height:900});assert.ok(await page.locator('#detail').evaluate(e=>e.scrollWidth<=e.clientWidth),`overflow ${width}`);await page.screenshot({path:`qa/detail-v2-${width}.png`});}
 await page.locator('#detail button.close').click();await page.goto('http://127.0.0.1:4173/#biblioteca');const dl=page.waitForEvent('download');await page.getByRole('button',{name:'Exportar respaldo'}).click();await (await dl).saveAs('qa/photo-backup.json');const backup=JSON.parse(fs.readFileSync('qa/photo-backup.json'));assert.equal(backup.version,3);assert.equal(backup.photos.length,1);assert.equal(backup.photos[0].id,backup.books[0].exemplars[1].id);
 await page.getByRole('button',{name:'Ver El Hobbit / The Hobbit'}).click();page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Eliminar libro'}).click();await page.getByText('Tu primera historia empieza acá').waitFor();assert.equal(await page.evaluate(async()=>{const s=await import('/src/storage.js?v=20261004-2');return (await s.getPhotos()).length;}),0);
 page.once('dialog',d=>d.accept());await page.locator('#import-file').setInputFiles('qa/photo-backup.json');await page.getByRole('button',{name:'Ver El Hobbit / The Hobbit'}).click();await page.locator('#photo-copy').selectOption({index:1});await page.getByRole('button',{name:'Ampliar foto de tu ejemplar'}).waitFor();assert.deepEqual(errors,[]);await browser.close();console.log('PASS: real ZXing EAN decoding without BarcodeDetector, camera cleanup, Hobbit Spanish topics/category, optional index, cover zoom, per-copy photo compression/persistence/backup/restore/delete, 320-1440px.');
})().catch(e=>{console.error(e);process.exit(1)});
