const {setup,fixture,lookup,save,assert,fs}=require('./ui-helpers.cjs');
(async()=>{
 const {page,go,finish}=await setup();await fixture(page);
 // Real ZXing decoder sees a generated EAN-13, through both video and file paths.
 await page.addInitScript(()=>{
  Object.defineProperty(window,'BarcodeDetector',{value:undefined,configurable:true});
  window.makeBarcode=()=>{const L=['0001101','0011001','0010011','0111101','0100011','0110001','0101111','0111011','0110111','0001011'],G=['0100111','0110011','0011011','0100001','0011101','0111001','0000101','0010001','0001001','0010111'],P=['LLLLLL','LLGLGG','LLGGLG','LLGGGL','LGLLGG','LGGLLG','LGGGLL','LGLGLG','LGLGGL','LGGLGL'],v='9789505470631';let bits='101';for(let i=1;i<=6;i++)bits+=(P[Number(v[0])][i-1]==='L'?L:G)[Number(v[i])];bits+='01010';for(let i=7;i<13;i++)bits+=L[Number(v[i])].split('').map(b=>b==='0'?'1':'0').join('');bits+='101';const c=document.createElement('canvas');c.width=720;c.height=360;const x=c.getContext('2d');x.fillStyle='white';x.fillRect(0,0,720,360);x.fillStyle='black';[...bits].forEach((b,i)=>{if(b==='1')x.fillRect(75+i*6,30,6,300);});return c;};
  if(navigator.mediaDevices&&HTMLCanvasElement.prototype.captureStream)navigator.mediaDevices.getUserMedia=async()=>{const c=window.makeBarcode();window.testCanvas=c;window.testStream=c.captureStream(10);return window.testStream;};
 });
 await go('agregar');if(process.env.TEST_ENGINE!=='webkit'){await page.locator('#scan-start').click();await page.locator('#confirm-isbn').waitFor();assert.equal(await page.locator('#isbn-query').inputValue(),'9789505470631');assert.ok(await page.evaluate(()=>window.testStream.getTracks().every(t=>t.readyState==='ended')));}else console.log('SKIP: live video unavailable in Windows WebKit; image decoding remains tested.');
 const png=await page.evaluate(()=>window.makeBarcode().toDataURL('image/png').split(',')[1]);fs.writeFileSync('qa/barcode.png',Buffer.from(png,'base64'));
 await go('agregar');const barcodeChooser=page.waitForEvent('filechooser');await page.getByRole('button',{name:'No puedo usar la cámara'}).click();await page.locator('#scan-photo').click();await(await barcodeChooser).setFiles('qa/barcode.png');await page.locator('#confirm-isbn').waitFor();assert.equal(await page.locator('#isbn-query').inputValue(),'9789505470631');await page.locator('#confirm-isbn').click();await page.locator('[name=copies]').fill('2');await save(page);
 await page.getByRole('button',{name:'Ampliar portada bibliográfica'}).click();assert.ok((await page.locator('#large-image').getAttribute('src')).includes('covers.openlibrary.org'));await page.getByRole('button',{name:'Cerrar imagen'}).click();
 await page.locator('#photo-copy').selectOption({index:1});const chooser=page.waitForEvent('filechooser');await page.getByRole('button',{name:'Elegir archivo'}).click();await(await chooser).setFiles('qa/barcode.png');await page.locator('.photo-thumbnail').waitFor();await page.locator('.photo-thumbnail').click();assert.ok((await page.locator('#large-image').getAttribute('src')).startsWith('data:image/jpeg'));await page.getByRole('button',{name:'Cerrar imagen'}).click();
 await page.reload();await page.locator('.record-page').waitFor();assert.equal(await page.locator('.photo-thumbnail').count(),0);await page.locator('#photo-copy').selectOption({index:1});await page.locator('.photo-thumbnail').waitFor();
 await page.getByRole('link',{name:'Editar registro',exact:true}).click();await page.locator('[name=copies]').fill('1');await page.getByRole('button',{name:'Guardar en el catálogo'}).click();await page.locator('#confirm-cancel').click();assert.equal(await page.locator('#book-form').count(),1);await page.locator('[name=copies]').fill('2');await save(page);
 await go('biblioteca');const dl=page.waitForEvent('download');await page.getByRole('button',{name:'Exportar',exact:false}).click();await(await dl).saveAs('qa/photo-backup.json');const archive=JSON.parse(fs.readFileSync('qa/photo-backup.json'));assert.equal(archive.photos.length,1);assert.equal(archive.photos[0].id,archive.books[0].exemplars[1].id);
 await page.locator('.book-card').click();await page.getByRole('button',{name:'Eliminar registro',exact:true}).click();await page.locator('#confirm-accept').click();await page.locator('.empty').waitFor();assert.equal(await page.evaluate(async()=>{const s=await import('./src/storage.js?v=20261010-1');return(await s.getPhotos()).length;}),0);
 await page.locator('#import-file').setInputFiles('qa/photo-backup.json');await page.locator('#confirm-accept').click();await page.locator('.book-card').click();await page.locator('#photo-copy').selectOption({index:1});await page.locator('.photo-thumbnail').waitFor();
 await finish();console.log('PASS: ZXing image decoding, scan-to-save, cover viewer, per-copy photo persistence/backup/restore/deletion, copy reduction confirmation. Live video and track cleanup also checked when supported.');
})().catch(e=>{console.error(e);process.exit(1)});
