const {setup,assert,base,noOverflow}=require('./ui-helpers.cjs');
(async()=>{const {page,finish}=await setup({deviceScaleFactor:1,isMobile:false,hasTouch:false});await page.addInitScript(()=>{window.dbOpens=0;const original=IDBFactory.prototype.open;IDBFactory.prototype.open=function(...a){window.dbOpens++;return original.apply(this,a);};});
for(const theme of ['light','dark'])for(const width of [320,390,768,1440]){
 await page.setViewportSize({width,height:900});await page.goto(base);await page.evaluate(t=>document.documentElement.dataset.theme=t,theme);await page.evaluate(()=>document.fonts.ready);await page.locator('.hero-screen img:visible').evaluate(i=>i.decode());await noOverflow(page,'public '+width+' '+theme);assert.equal(await page.evaluate(()=>window.dbOpens),0);assert.equal(await page.locator('main h1').count(),1);
 await page.screenshot({path:`qa/product-hero-${theme}-${width}.png`});
 if(width<=1080){await page.locator('#menu-toggle').click();assert.equal(await page.locator('main').evaluate(el=>el.inert),true);assert.ok(await page.locator('#menu-backdrop').isVisible());await page.keyboard.press('Tab');assert.ok(await page.evaluate(()=>document.querySelector('.site-header').contains(document.activeElement)));await page.locator('#site-nav a[href="#como-funciona"]').click();await page.waitForFunction(()=>{const y=document.querySelector('#como-funciona').getBoundingClientRect().top;return y>=80&&y<170;});assert.equal(await page.locator('#menu-toggle').getAttribute('aria-expanded'),'false');assert.equal(await page.locator('main').evaluate(el=>el.inert),false);}
 else{await page.locator('#product-menu-toggle').click();assert.ok(await page.locator('#product-menu').isVisible());await page.waitForTimeout(300);await page.screenshot({path:`qa/product-menu-${theme}.png`});await page.keyboard.press('Escape');assert.equal(await page.locator('#product-menu-toggle').getAttribute('aria-expanded'),'false');assert.ok(await page.locator('#product-menu-toggle').evaluate(el=>el===document.activeElement));await page.locator('#product-menu-toggle').click();await page.locator('#product-menu a[href="#catalogacion"]').click();assert.equal(await page.locator('main').evaluate(el=>el.inert),false);}
 for(const section of ['#como-funciona','#producto','#funcionalidades','#escuelas','#celular','#impacto','#recursos','.site-footer']){await page.locator(section).scrollIntoViewIfNeeded();await page.waitForTimeout(80);await noOverflow(page,section+' '+width+' '+theme);}await page.waitForTimeout(1050);
 const numbers=await page.locator('[data-count]').allTextContents();assert.deepEqual(numbers,['1','8','12','3']);assert.ok(await page.locator('.demo-label').innerText().then(t=>t.includes('NO SON CIFRAS DE USO REAL')));
 if(width===390||width===1440){for(const [label,selector] of [['mosaic','#como-funciona'],['story','#catalogacion'],['mobile','#celular'],['footer','.site-footer']]){await page.locator(selector).scrollIntoViewIfNeeded();await page.waitForTimeout(700);await page.screenshot({path:`qa/product-${label}-${theme}-${width}.png`});}}
 assert.equal(await page.evaluate(()=>window.dbOpens),0);
}
await page.setViewportSize({width:1440,height:900});await page.goto(base);await page.locator('.feature-list details[data-screen=holdings] summary').first().click();await page.waitForFunction(()=>document.querySelector('.feature-visual img').getAttribute('src').includes('holdings'));await page.locator('.feature-visual img:visible').evaluate(i=>i.decode());assert.equal(await page.locator('.feature-list details[open]').count(),1);await page.locator('.feature-visual [data-preview]').click();await page.locator('#product-preview-dialog').waitFor();await page.locator('#preview-image').evaluate(i=>i.decode());assert.ok(await page.locator('#preview-image').getAttribute('src').then(v=>v.includes('holdings')));await page.keyboard.press('Escape');assert.equal(await page.locator('#product-preview-dialog').isVisible(),false);
await page.locator('.footer-columns a[href="#privacidad"]').last().click();assert.equal(await page.locator('#privacidad').getAttribute('open'),'');await page.locator('#menu-toggle').isHidden();await page.setViewportSize({width:390,height:844});await page.locator('#menu-toggle').click();await page.keyboard.press('Escape');assert.equal(await page.locator('#menu-backdrop').isVisible(),false);await page.locator('#menu-toggle').click();await page.setViewportSize({width:1440,height:900});assert.equal(await page.locator('main').evaluate(el=>el.inert),false);
await page.emulateMedia({reducedMotion:'reduce'});assert.equal(await page.evaluate(()=>getComputedStyle(document.documentElement).scrollBehavior),'auto');assert.ok(await page.locator('[data-reveal]').first().evaluate(el=>getComputedStyle(el).opacity==='1'));await finish();console.log('PASS public product layout, themes/responsive, sticky/blur menus, focus/Escape/inert, disclosures, previews, honest counters, reduced motion and no catalog access');})().catch(e=>{console.error(e);process.exit(1)});
