const {setup,save,assert,base}=require('./ui-helpers.cjs');
(async()=>{const{page,go,finish}=await setup({deviceScaleFactor:1});
 await go('agregar');assert.equal(await page.locator('#recognition-fallback').isVisible(),false);assert.equal(await page.locator('[name=materialType]').count(),0);
 await page.getByRole('button',{name:'No puedo usar la cámara'}).click();await page.getByRole('button',{name:'Ingresar un código',exact:true}).click();await page.locator('#isbn-query').fill('0378-5955');await page.locator('#isbn-search').click();await page.locator('#review-recognized').click();assert.equal(await page.locator('[name=issn]').inputValue(),'0378-5955');assert.equal(await page.locator('[name=isbn]').inputValue(),'');
 await page.locator('[name=materialType]').selectOption('diario');await page.locator('[name=title]').fill('Primera plana del archivo');await page.locator('[name=publication]').fill('El diario escolar');await page.locator('[name=publicationDate]').fill('1945-05-09');await page.locator('[name=edition]').fill('120');await page.locator('[name=subjects]').fill('Segunda Guerra Mundial');await page.locator('.optional-section summary').click();await page.locator('[name=contents]').fill('La paz en Europa\nSuplemento histórico');await page.locator('textarea[name=description]').fill('Edición conservada por la escuela.');await save(page);await page.reload();await page.locator('.record-page').waitFor();
 const state=()=>page.evaluate(async()=>await(await import('./src/storage.js?v=20261010-7')).readState());let s=await state();assert.equal(s.books[0].publicationDate,'1945-05-09');assert.equal(s.books[0].exemplars.length,1);assert.equal(s.books[0].contents.length,2);
 await go('biblioteca');await page.locator('#search').fill('Segunda Guerra Mundial');await page.getByRole('heading',{name:'Primera plana del archivo'}).waitFor();
 // QR is a carrier: read an actual QR image through the acquisition decoder.
 await page.addScriptTag({url:base+'vendor/qrcode-generator-1.4.4.js'});const decoded=await page.evaluate(async()=>{const qr=qrcode(0,'M');qr.addData('https://escuela.example/proyecto');qr.make();const svg=qr.createSvgTag({cellSize:5,margin:20});return await(await import('./src/scanner.js?v=20261010-7')).scanMaterialFromFile(new File([svg],'codigo.svg',{type:'image/svg+xml'}));});assert.equal(decoded,'https://escuela.example/proyecto');
 await go('agregar');await page.getByRole('button',{name:'No puedo usar la cámara'}).click();await page.getByRole('button',{name:'Ingresar un código',exact:true}).click();await page.locator('#isbn-query').fill(decoded);await page.locator('#isbn-search').click();await page.locator('#review-recognized').click();assert.equal(await page.locator('[name=materialType]').inputValue(),'digital');assert.equal(await page.locator('[name=copies]').inputValue(),'0');await page.locator('[name=title]').fill('Memoria del aula');await page.locator('[name=subjects]').fill('Segunda Guerra Mundial');await save(page);s=await state();assert.equal(s.books.find(b=>b.title==='Memoria del aula').exemplars.length,0);
 const archive=await page.evaluate(async()=>await(await import('./src/storage.js?v=20261010-7')).exportArchive());assert.equal(archive.books.find(b=>b.materialType==='diario').issn,'0378-5955');
 for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:1000});await go('agregar');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
 await finish();console.log('PASS camera-first entry, ISSN review, newspaper persistence/theme search, actual QR URL decode, digital zero-copy record and full backup');
})().catch(e=>{console.error(e);process.exit(1)});
