// Capture the real application in an isolated browser. Never seed a user's browser.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const fs=require('node:fs');
(async()=>{
 fs.mkdirSync('assets/product',{recursive:true});
 const browser=await chromium.launch({channel:'msedge',headless:true});
 const context=await browser.newContext({viewport:{width:1280,height:900},deviceScaleFactor:1});const page=await context.newPage();
 await page.route('https://covers.openlibrary.org/**',r=>{const name=new URL(r.request().url()).pathname.split('/').pop().replace('.svg','');if(!['selva','principito','aula'].includes(name))return r.abort();return r.fulfill({contentType:'image/svg+xml',body:fs.readFileSync('assets/illustrated-covers/'+name+'.svg','utf8')});});
 await page.goto('http://127.0.0.1:4173/app.html#inicio');await page.locator('[data-access-route=inicio]').waitFor();
 const ids=await page.evaluate(async()=>{const db=await import('./src/storage.js?v=20261010-7'),{validateBook}=await import('./src/catalog.js?v=20261010-7');await db.execute('settings.save',{institutionName:'Escuela del Encuentro · Demo',libraryName:'Biblioteca del Encuentro'});await db.execute('onboarding.library',{libraryName:'Biblioteca del Encuentro',responsible:'self'});await db.execute('onboarding.finish',{});const person=await db.execute('person.save',{name:'Docente de demostración',cargo:'Docente',accessProfile:'docente',status:'active'});
 const input=[['Cuentos de la selva','Horacio Quiroga','libro','Cuentos',['Animales','Naturaleza','Amistad'],['La tortuga gigante','Las medias de los flamencos'],2,'selva'],['El principito','Antoine de Saint-Exupéry','libro','Otros',['Amistad','Viajes'],[],2,'principito'],['Historias de nuestra escuela','Producción de estudiantes','produccion','Otros',['Memoria','Escuela'],[],2,'aula'],['Atlas de la naturaleza','Equipo de Ciencias','libro','Otros',['Naturaleza','Ambiente'],[],2,''],['Revista de ciencias','Archivo escolar','revista','Otros',['Ambiente','Agua'],[],1,''],['Diario del archivo escolar','Hemeroteca escolar','diario','Otros',['Historia','Segunda Guerra Mundial'],['Noticias de 1945'],1,''],['Guía del huerto escolar','Equipo docente','documento','Otros',['Huerta','Ambiente'],[],2,''],['Biblioteca de sonidos','Proyecto de aula','digital','Otros',['Música','Sonidos'],[],0,'']];const ids=[];for(const [title,author,materialType,category,subjects,contents,copies,art]of input){const book=validateBook({title,author,materialType,category,subjects,contents,copies,location:'Literatura · Estante 3',description:'Material de demostración para explorar el catálogo escolar. Datos de ejemplo, sin información de personas reales.'});await db.saveBook(book);ids.push({id:book.id,art});}const s=await db.readState();for(const b of s.books.slice(0,2))await db.execute('loan.create',{exemplarId:b.exemplars[0].id,patronId:person.id,dueAt:'2030-12-01'});await db.execute('reservation.create',{bookId:s.books[2].id,patronId:person.id});return ids;});
 // Illustrative covers are local project artwork, applied only to capture fixtures.
 await page.evaluate(async ids=>{const db=await import('./src/storage.js?v=20261010-7');await db.mutate(s=>{for(const entry of ids){const b=s.books.find(b=>b.id===entry.id);if(entry.art)b.cover='https://covers.openlibrary.org/'+entry.art+'.svg';}});},ids);
 await page.reload();await page.locator('[data-access-route=inicio]').waitFor();
 async function route(hash,selector){await page.goto('http://127.0.0.1:4173/app.html#'+hash);await page.locator(selector).first().waitFor();await page.evaluate(()=>document.fonts.ready);}
 async function shot(name){for(const theme of ['light','dark']){await page.evaluate(t=>document.documentElement.dataset.theme=t,theme);await page.screenshot({path:'assets/product/'+name+'-'+theme+'.jpg',type:'jpeg',quality:88,animations:'disabled'});}}
 await route('biblioteca','#search');await shot('catalog');
 await page.locator('#search').fill('animales');await page.waitForTimeout(250);await shot('search');
 await route('agregar','#scan-start');await page.route('https://www.googleapis.com/books/v1/**',r=>r.fulfill({json:{}}));await page.route('https://openlibrary.org/api/books?**',r=>r.fulfill({json:JSON.parse(fs.readFileSync('tests/fixtures/hobbit.json','utf8').replace(/^\uFEFF/,''))}));await page.getByRole('button',{name:'No puedo usar la cámara'}).click();await page.getByRole('button',{name:'Ingresar un código',exact:true}).click();await page.locator('#isbn-query').fill('9505470630');await page.locator('#isbn-search').click();await page.locator('#confirm-isbn').waitFor();await page.locator('#confirm-isbn').click();await page.locator('#book-form').waitFor();await shot('scan');
 await route('ficha/'+ids[0].id,'.record-page');await page.getByText('Contenidos indexados (2)',{exact:true}).click();await shot('record');
 await route('ejemplares','.holdings-list');await shot('holdings');
 await route('circulacion','#local-loan');await shot('circulation');
 await route('usuarios','[data-access-route=usuarios]');await shot('people');
 await page.setViewportSize({width:390,height:844});await route('agregar','#scan-start');await shot('mobile');
 await route('biblioteca','#search');await shot('mobile-catalog');
 fs.writeFileSync('assets/product/demo.json',JSON.stringify({kind:'demonstration',institutions:1,materials:8,holdings:12,circulation:3,notice:'Datos ficticios del escenario utilizado para las capturas; no son estadísticas de uso real.'},null,2)+'\n');
 await browser.close();console.log('Captured nine real screens, light/dark, in an isolated demonstration context.');
})().catch(e=>{console.error(e);process.exit(1)});
