import {migrateAccess,projectState,mergeScope} from '../access-model.js?v=20261009-8';
import {expireAccess,logAccess} from '../access-domain.js?v=20261009-8';
import {suggestProfile} from '../permissions.js?v=20261009-8';
import {STORES,normalizeHoldings,config,command,audit,ensureRemovable,activeLoan,activeReservation,expireReservations} from '../local-domain.js?v=20261009-8';
import {requirePermission} from '../permissions.js?v=20261009-8';
let institutionId='local-institution';try{institutionId=sessionStorage.getItem('ab-institution')||institutionId;}catch{}
export const getInstitutionId=()=>institutionId;
export function setInstitutionId(id){institutionId=id;try{sessionStorage.setItem('ab-institution',id);}catch{}}
let database,actorId='local-admin';try{actorId=sessionStorage.getItem('ab-actor')||actorId;}catch{}
export const getActorId=()=>actorId;
export function setActorId(id){actorId=id;try{sessionStorage.setItem('ab-actor',id);}catch{}}
export function openDatabase(){return new Promise((resolve,reject)=>{const request=indexedDB.open('asistente-bibliotecario',6);request.onupgradeneeded=()=>{const db=request.result;for(const name of STORES)if(!db.objectStoreNames.contains(name)){const st=db.createObjectStore(name,{keyPath:'id'});if(name==='photos')st.createIndex('bookId','bookId');}};request.onerror=()=>reject(request.error);request.onblocked=()=>reject(new Error('Cerrá otras pestañas de la biblioteca y volvé a intentar.'));request.onsuccess=async()=>{database=request.result;database.onversionchange=()=>database.close();try{await mutate(s=>{expireAccess(s);expireReservations(s,actorId);});resolve();}catch(error){reject(error);}};});}
// All related reads and writes share one readwrite transaction; concurrent tabs serialize.
export function rawMutate(reducer){return new Promise((resolve,reject)=>{const tx=database.transaction(STORES,'readwrite'),s={};let pending=STORES.length,result,failure;tx.oncomplete=()=>resolve(result);tx.onabort=()=>reject(failure||tx.error||new Error('No se pudo guardar la operación.'));tx.onerror=()=>{};for(const name of STORES){const r=tx.objectStore(name).getAll();r.onsuccess=()=>{s[name]=r.result;if(--pending)return;try{result=reducer(s);for(const name of STORES){const st=tx.objectStore(name);st.clear();for(const record of s[name])st.put(record);}}catch(error){failure=error;tx.abort();}};}});}
export function readAll(){return new Promise((resolve,reject)=>{const tx=database.transaction(STORES,'readonly'),s={};for(const name of STORES){const r=tx.objectStore(name).getAll();r.onsuccess=()=>s[name]=r.result;}tx.oncomplete=()=>resolve(s);tx.onabort=()=>reject(tx.error);tx.onerror=()=>reject(tx.error);});}
export function mutate(reducer){const iid=institutionId;return rawMutate(all=>{migrateAccess(all);if(!all.institutions.some(i=>i.id===iid))throw new Error('Institución inexistente.');const s=projectState(all,iid,actorId);expireAccess(s);const result=reducer(s);normalizeHoldings(s);mergeScope(all,s,iid);return result;});}
export async function readState(){return projectState(await readAll(),institutionId,actorId);}
export async function createInstitution(d){const result=await rawMutate(all=>{migrateAccess(all);if(!String(d.institutionName||'').trim()||!String(d.name||'').trim()||!String(d.cargo||'').trim())throw new Error('Completá institución, nombre y cargo.');const id=crypto.randomUUID(),person=d.personId?all.people.find(p=>p.id===d.personId):null;if(d.personId&&d.personId!==actorId)throw new Error('Solo podés vincular tu identidad actual.');const p=person||{id:crypto.randomUUID(),name:String(d.name).trim().slice(0,160),email:''};if(!person)all.people.push(p);all.institutions.push({id,name:String(d.institutionName).trim().slice(0,160),jurisdiction:d.jurisdiction,type:d.type,locality:String(d.locality||'').slice(0,160),mainAdminId:p.id,status:'active',createdAt:new Date().toISOString()});all.memberships.push({id:crypto.randomUUID(),personId:p.id,institutionId:id,cargo:String(d.cargo).slice(0,160),accessProfile:suggestProfile(d.cargo),status:'active',initialAdmin:true});all.settings.push({id:'config:'+id,institutionId:id,institutionName:d.institutionName,libraryName:'Biblioteca de '+d.institutionName,libraryId:crypto.randomUUID(),collectionId:crypto.randomUUID(),sequence:1,onboardingStep:1});const scoped=projectState(all,id,p.id);normalizeHoldings(scoped);logAccess(scoped,'institution.created',p.id,{userId:p.id});mergeScope(all,scoped,id);return {id,personId:p.id};});setActorId(result.personId);setInstitutionId(result.id);return result;}
export const execute=(type,data)=>mutate(s=>command(s,actorId,type,data));
const read=async name=>(await readState())[name];
export const getBooks=()=>read('books');export const getLoans=()=>read('loans');export const getReservations=()=>read('reservations');export const getPatrons=()=>read('patrons');export const getActivity=()=>read('activity');
function putBook(s,book,importing=false){Object.assign(book,{institutionId:config(s).institutionId,libraryId:config(s).libraryId,collectionId:config(s).collectionId});const old=s.books.find(b=>b.id===book.id);const shared=s.books.find(b=>b.id!==book.id&&b.workId===book.workId);const workFields=['title','subtitle','author','authors','subjects','contents','description'];if(shared&&(!old||old.workId!==book.workId))for(const key of workFields)book[key]=structuredClone(shared[key]);requirePermission(s,actorId,old?'catalog.edit':'catalog.create');const oldIds=new Set(old?.exemplars?.map(e=>e.id)||[]);const added=(book.exemplars||[]).filter(e=>!oldIds.has(e.id));const removed=(old?.exemplars||[]).filter(e=>!book.exemplars.some(n=>n.id===e.id));if(added.length)requirePermission(s,actorId,'holdings.create');if(removed.length)requirePermission(s,actorId,'holdings.edit');ensureRemovable(s,removed.map(e=>e.id));
 for(const e of book.exemplars||[]){const previous=old?.exemplars?.find(p=>p.id===e.id);if(previous){if(['lost','withdrawn'].includes(e.status)&&e.status!==previous.status)ensureRemovable(s,[e.id]);e.internalCode=previous.internalCode;if(!importing&&['location','condition','status','inventoryCode','physicalLocation'].some(key=>JSON.stringify(e[key])!==JSON.stringify(previous[key])))requirePermission(s,actorId,'holdings.edit');}}if(old)s.books.splice(s.books.indexOf(old),1,book);else s.books.push(book);for(const sibling of s.books)if(sibling.id!==book.id&&sibling.workId===book.workId){for(const key of workFields)sibling[key]=structuredClone(book[key]);sibling.updatedAt=new Date().toISOString();}s.photos=s.photos.filter(p=>p.bookId!==book.id||book.exemplars.some(e=>e.id===p.id));audit(s,old?'material.updated':'material.created',actorId,{bookId:book.id,title:book.title});for(const e of added)audit(s,'holding.created',actorId,{bookId:book.id,exemplarId:e.id});for(const e of removed)audit(s,'holding.deleted',actorId,{bookId:book.id,exemplarId:e.id});}
export const saveBook=book=>mutate(s=>putBook(s,structuredClone(book)));
export const deleteBook=id=>mutate(s=>{requirePermission(s,actorId,'catalog.delete');const b=s.books.find(b=>b.id===id);if(!b)return;ensureRemovable(s,b.exemplars.map(e=>e.id));if(s.reservations.some(r=>r.bookId===id&&activeReservation(r)))throw new Error('Cancelá las reservas pendientes antes de eliminar el registro.');s.books=s.books.filter(b=>b.id!==id);s.photos=s.photos.filter(p=>p.bookId!==id);audit(s,'material.deleted',actorId,{bookId:id,title:b.title});for(const e of b.exemplars)audit(s,'holding.deleted',actorId,{bookId:id,exemplarId:e.id});});
export const clearCatalog=()=>mutate(s=>{requirePermission(s,actorId,'catalog.clear');if(s.loans.some(activeLoan)||s.reservations.some(activeReservation))throw new Error('Cerrá préstamos y reservas pendientes antes de vaciar el catálogo.');s.books=[];s.photos=[];audit(s,'catalog.cleared',actorId);});
export const mergeBooks=(books,photos=[],type='backup.imported')=>mutate(s=>{for(let book of structuredClone(books)){if(type==='aguapey.imported'){const old=s.books.find(b=>(book.identifiers?.marc001&&b.importedFrom&&b.identifiers?.marc001===book.identifiers.marc001)||(book.isbn&&b.isbn===book.isbn));if(old){const incoming=book.exemplars.filter(e=>!e.inventoryCode||!old.exemplars.some(x=>x.inventoryCode===e.inventoryCode));book={...old,exemplars:[...old.exemplars,...incoming]};}}putBook(s,book,true);}for(const photo of photos){s.photos=s.photos.filter(p=>p.id!==photo.id);s.photos.push(photo);}audit(s,type,actorId,{count:books.length});});
export const getPhotos=async bookId=>(await read('photos')).filter(p=>!bookId||p.bookId===bookId);
export const savePhoto=photo=>mutate(s=>{requirePermission(s,actorId,'holdings.edit');if(!s.books.some(b=>b.id===photo.bookId&&b.exemplars.some(e=>e.id===photo.id)))throw new Error('Ejemplar inexistente.');s.photos=s.photos.filter(p=>p.id!==photo.id);s.photos.push(photo);audit(s,'photo.saved',actorId,{exemplarId:photo.id});});
export const deletePhoto=id=>mutate(s=>{requirePermission(s,actorId,'holdings.edit');s.photos=s.photos.filter(p=>p.id!==id);audit(s,'photo.deleted',actorId,{exemplarId:id});});
export const deleteExemplar=(bookId,id)=>mutate(s=>{requirePermission(s,actorId,'holdings.edit');ensureRemovable(s,[id]);const b=s.books.find(b=>b.id===bookId);if(!b)throw new Error('Registro inexistente.');b.exemplars=b.exemplars.filter(e=>e.id!==id);s.photos=s.photos.filter(p=>p.id!==id);audit(s,'holding.deleted',actorId,{bookId,exemplarId:id});});
// Legacy service entry points may not bypass the operation/permission rules.
export const savePatron=data=>execute('user.save',data);
export const saveLoan=()=>Promise.reject(new Error('Usá el flujo de préstamo o devolución.'));
export const saveReservation=()=>Promise.reject(new Error('Usá el flujo de reservas.'));
export const appendActivity=entry=>mutate(s=>{requirePermission(s,actorId,'reports.view');audit(s,entry.type,actorId,entry);});
export const exportArchive=async()=>{const s=await readState();requirePermission(s,actorId,'sensitive.export');delete s.availableInstitutions;s.people=s.people.filter(p=>s.memberships.some(m=>m.personId===p.id));return {app:'asistente-bibliotecario',version:5,exportedAt:new Date().toISOString(),...s};};
export async function restoreArchive(archive){if(archive.version===5&&archive.institutions[0]?.id!==institutionId){const current=institutionId;const restored=await rawMutate(all=>{migrateAccess(all);const scope=projectState(all,current,actorId);requirePermission(scope,actorId,'sensitive.export');const iid=archive.institutions[0].id;if(all.institutions.some(i=>i.id===iid))throw new Error('Seleccioná la institución de este respaldo antes de reemplazarla.');const incoming=structuredClone(archive);incoming.institutionId=iid;incoming.people=[...all.people.filter(p=>!incoming.people.some(v=>v.id===p.id)),...incoming.people];normalizeHoldings(incoming);audit(incoming,'backup.restored',actorId);mergeScope(all,incoming,iid);return {iid,owner:incoming.institutions[0].mainAdminId};});setInstitutionId(restored.iid);setActorId(restored.owner);return;}return mutate(s=>{requirePermission(s,actorId,'sensitive.export');requirePermission(s,actorId,'catalog.clear');if(archive.version===5&&archive.institutions[0]?.id!==s.institutionId)throw new Error('Restaurá este respaldo desde su institución de origen.');if(s.loans.some(activeLoan)||s.reservations.some(activeReservation))throw new Error('Cerrá las operaciones pendientes antes de restaurar un respaldo completo.');const maxSequence=config(s).sequence;const preservedPeople=s.people;const originalConfig={...config(s)};for(const name of STORES)s[name]=structuredClone(archive[name]||[]);if(archive.version===4){migrateAccess(s);config(s).institutionId=originalConfig.institutionId;config(s).libraryId=originalConfig.libraryId;config(s).collectionId=originalConfig.collectionId;s.institutions[0].id=originalConfig.institutionId;for(const m of s.memberships)m.institutionId=originalConfig.institutionId;}s.people=[...preservedPeople.filter(p=>!s.people.some(v=>v.id===p.id)),...s.people];normalizeHoldings(s);config(s).sequence=Math.max(maxSequence||1,config(s).sequence);audit(s,'backup.restored',actorId);});}

export async function expireDueReservations(){const state=await readState();if(state.grants.some(g=>g.active!==false&&g.expiresAt&&Date.parse(g.expiresAt)<=Date.now())||state.memberships.some(m=>['active','suspended'].includes(m.status)&&m.expiresAt&&Date.parse(m.expiresAt)<=Date.now())||state.reservations.some(r=>activeReservation(r)&&r.expiresAt&&Date.parse(r.expiresAt)<=Date.now()))await mutate(s=>expireReservations(s,'system'));}
