import {readState,execute,createInstitution,getActorId,setInstitutionId,getInstitutionId} from './storage.js?v=20261006-2';
import {PROFILES,CARGOS,LABELS,RESTRICTED,hasPermission,isEnabled,suggestProfile} from './permissions.js?v=20261006-2';
import {config,activeLoan,activeReservation} from './local-domain.js?v=20261006-2';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const options=(values,selected='')=>values.map(([v,label])=>`<option value="${esc(v)}" ${v===selected?'selected':''}>${esc(label)}</option>`).join('');
const field=(label,name,value='',type='text',extra='')=>`<label>${label}<input name="${name}" value="${esc(value)}" type="${type}" ${extra}></label>`;
const select=(label,name,values,value='')=>`<label>${label}<select name="${name}">${options(values,value)}</select></label>`;
const button=(route,label)=>`<a class="button secondary" href="#${esc(route)}">${label}</a>`;
const form=(kind,body,label='Guardar')=>`<form class="local-form" data-access-form="${kind}">${body}<p class="error" role="alert"></p><button class="button ${kind.startsWith('institution.')?'danger':'primary'}">${label}</button></form>`;
const panel=(title,body)=>`<section class="panel settings-panel local-panel"><h2>${title}</h2>${body}</section>`;
const cargo=value=>select('Cargo en la institución','cargo',CARGOS.map(v=>[v,v]),CARGOS.includes(value)?value:'Otro')+field('Si elegiste Otro, escribí el cargo','customCargo',CARGOS.includes(value)?'':value);
const dt=v=>{if(!v)return '';const d=new Date(v);return new Date(+d-d.getTimezoneOffset()*60000).toISOString().slice(0,16);};
const date=v=>v?new Date(v).toLocaleString('es-AR'):'Permanente';
const TEACHER_DISCOVERY="<section class=\"teacher-discovery\" aria-labelledby=\"teacher-title\"><div class=\"section-heading\"><div><span class=\"eyebrow\">LECTURAS QUE SE COMPARTEN</span><h2 id=\"teacher-title\">De docente a docente</h2><p>Estas propuestas se incorporarán en una próxima etapa. Las tarjetas muestran ejemplos visuales de futuras recomendaciones.</p></div><span class=\"future-pill\">Próximamente · Espacio escolar</span></div><div class=\"teacher-grid\"><article class=\"teacher-card\"><figure class=\"teacher-cover\"><img src=\"./assets/illustrated-covers/selva.svg\" alt=\"Portada ilustrativa: cuentos de la selva\" width=\"240\" height=\"340\" loading=\"lazy\"><figcaption>Ejemplo visual · No es un destacado real</figcaption></figure><h3>Más reservados</h3><p>Los materiales más elegidos por docentes de tu escuela. Se mostrarán cuando haya reservas registradas.</p></article><article class=\"teacher-card\"><figure class=\"teacher-cover\"><img src=\"./assets/illustrated-covers/principito.svg\" alt=\"Portada ilustrativa: el pequeño explorador\" width=\"240\" height=\"340\" loading=\"lazy\"><figcaption>Ejemplo visual · No es un destacado real</figcaption></figure><h3>Cuentos destacados</h3><p>Lecturas recomendadas por la biblioteca y docentes, con el motivo de la elección y la experiencia en el aula.</p></article><article class=\"teacher-card\"><figure class=\"teacher-cover\"><img src=\"./assets/illustrated-covers/aula.svg\" alt=\"Portada ilustrativa: historias para compartir\" width=\"240\" height=\"340\" loading=\"lazy\"><figcaption>Ejemplo visual · No es un destacado real</figcaption></figure><h3>Ideas para tu grado</h3><p>Qué lectura sirvió para qué grado, tema o proyecto, según experiencias compartidas por docentes.</p></article></div></section>";
let refresh,draft={},knownPeople=[];try{draft=JSON.parse(sessionStorage.getItem('ab-registration-draft')||'{}');}catch{}
export function initAccessUI(onRefresh){refresh=onRefresh;
 document.addEventListener('change',async e=>{if(e.target.name==='existingPerson'){const f=e.target.form,p=knownPeople.find(p=>p.id===e.target.value);f.querySelector('[name=id]').value=p?.id||'';f.querySelector('[name=name]').value=p?.name||'';f.querySelector('[name=email]').value=p?.email||'';}if(e.target.name==='responsible'){const group=e.target.form.querySelector('[data-responsible-other]');group.hidden=e.target.value!=='other';for(const input of group.querySelectorAll('[name=name],[name=email]'))input.required=!group.hidden;}if(e.target.name==='cargo'){const input=e.target.form.querySelector('[name=customCargo]');input.closest('label').hidden=e.target.value!=='Otro';input.required=e.target.value==='Otro';}if(e.target.id==='institution-context'){setInstitutionId(e.target.value);location.hash='#inicio';await refresh(true);}if(e.target.name==='cargo'){const f=e.target.closest('form'),p=f?.querySelector('[name=accessProfile]');if(p)p.value=suggestProfile(e.target.value);}if(e.target.name==='duration'){const input=e.target.form.querySelector('[name=expiresAt]');input.required=e.target.value==='temporary';input.disabled=e.target.value!=='temporary';if(input.disabled)input.value='';}});
 document.addEventListener('submit',async e=>{const f=e.target.closest('[data-access-form]');if(!f)return;e.preventDefault();const submit=f.querySelector('button'),error=f.querySelector('.error');submit.disabled=true;error.textContent='';try{const d=Object.fromEntries(new FormData(f)),kind=f.dataset.accessForm;if(d.cargo==='Otro')d.cargo=d.customCargo;for(const key of ['startsAt','expiresAt'])if(d[key])d[key]=new Date(d[key]).toISOString();
 if(kind==='register-school'){draft=d;sessionStorage.setItem('ab-registration-draft',JSON.stringify(d));location.hash='#registro/persona';return;}
 if(kind==='register-person'){await createInstitution({...draft,...d});sessionStorage.removeItem('ab-registration-draft');draft={};location.hash='#bienvenida/biblioteca';await refresh(true);return;}
 if(kind==='finish'){await execute('onboarding.finish',{});location.hash=d.next==='scan'?'#agregar':'#inicio';await refresh();return;}
 if(kind==='onboarding.library'){await execute(kind,d);location.hash='#bienvenida/equipo';await refresh();return;}
 if(kind==='institution.transfer'||kind==='institution.disable'){if(!confirm('Esta acción cambia la administración o desactiva los accesos. ¿Confirmás?'))return;}
 await execute(kind,d);await refresh();document.querySelector('#access-feedback')?.append(document.createTextNode('Guardado en este navegador.'));
 }catch(errorValue){error.textContent=errorValue.message;}finally{submit.disabled=false;}});
 document.addEventListener('click',async e=>{const b=e.target.closest('[data-access-command]');if(!b)return;try{if(b.dataset.accessCommand==='grant.revoke'&&!confirm('¿Revocar este permiso adicional?'))return;await execute(b.dataset.accessCommand,{id:b.dataset.id,bookId:b.dataset.bookId});await refresh();}catch(error){const feedback=document.querySelector('#access-feedback');if(feedback)feedback.textContent=error.message;}});
}
export function updateInstitutionSelector(s){const el=document.querySelector('#institution-context');if(el)el.innerHTML=options(s.availableInstitutions.map(i=>[i.id,i.name]),getInstitutionId());}
export async function renderAccess(route){const [base,id]=route.split('/');if(!['registro','bienvenida','usuarios','permisos','organizacion','inicio','temas','guardados','inventario'].includes(base))return false;
 const s=await readState(),actor=s.patrons.find(p=>p.id===getActorId()),can=p=>hasPermission(actor,p,s.grants),c=config(s);updateInstitutionSelector(s);let title='',html='';
 knownPeople=s.people;
 const localNotice='<p class="notice">Prototipo local: datos guardados en este navegador, sin cuentas en servidor ni envío de correos. El selector de personas simula identidades; no es un inicio de sesión seguro.</p>';
 if(base==='registro'){title='Registrar mi escuela';html=localNotice;if(id==='persona'&&draft.institutionName){html+=panel('Ahora contanos quién sos dentro de la institución.',form('register-person',field('Nombre y apellido','name',actor?.name==='Responsable local'?'':actor?.name,'text','required maxlength="160"')+cargo('Docente')+(actor?select('Identidad local','personId',[['','Crear una persona local'],[actor.id,'Vincular mi persona actual a esta institución']]):'')+'<p><strong>Administrador inicial</strong><br>Esto te permite terminar de configurar la institución e incorporar a otras personas. Después vas a poder compartir o transferir esta responsabilidad.</p>','Crear espacio de la institución')+button('registro','Volver'));}else html+=panel('Empecemos por tu institución.',form('register-school',field('Nombre de la institución','institutionName',draft.institutionName,'text','required maxlength="160"')+select('Jurisdicción','jurisdiction',['Provincia de Buenos Aires','Ciudad Autónoma de Buenos Aires','Otra'].map(x=>[x,x]),draft.jurisdiction)+select('Tipo de institución','type',['Inicial','Primaria','Secundaria','Técnica','Especial','Superior','Universidad / Facultad','Otra'].map(x=>[x,x]),draft.type)+field('Localidad','locality',draft.locality,'text','required maxlength="160"'),'Continuar'));}
 if(base==='bienvenida'){title='Tu institución, paso a paso';html=localNotice;if(!actor?.mainAdmin)html+=panel('Configuración inicial','La administración inicial completa este paso.');else if(id==='biblioteca')html+=panel('1 · Configuremos la biblioteca.',form('onboarding.library',field('Nombre de la biblioteca','libraryName',c.libraryName,'text','required')+select('¿La biblioteca tiene una persona responsable?','responsible',[['self','Soy yo'],['other','Otra persona'],['later','Todavía no']])+'<div data-responsible-other hidden><p>Si es otra persona, completá estos datos. Quedará como Invitación pendiente; no se enviará correo.</p>'+field('Nombre de la persona responsable','name')+field('Correo','email','','email')+cargo('Bibliotecario/a')+'</div>','Continuar'));else if(id==='equipo')html+=panel('2 · Sumá a quienes van a usar la plataforma.','<p>No necesitás cargar a toda la escuela ahora. Podés hacerlo más adelante.</p>'+personForm({},{invite:true})+button('bienvenida/listo','Continuar')+s.invitations.map(i=>`<p>Invitación pendiente · ${esc(s.people.find(p=>p.id===i.personId)?.name)}</p>`).join(''));else html+=panel('3 · Empezá con lo que ya tenés.',form('finish',select('Elegí cómo continuar','next',[['scan','Escanear primer material'],['explore','Explorar la plataforma primero']]),'Comenzar')+'<p>No hace falta incorporar materiales ahora. Al escanear, primero intentamos reconocer y después preguntamos.</p>');}
 if(base==='usuarios'){title='Personas';const person=s.patrons.find(p=>p.id===id);html=localNotice+panel('Equipo de la institución',s.patrons.map(p=>`<article class="holding-row"><div><strong>${esc(p.name)}</strong><p>Cargo en la institución: ${esc(p.cargo)}</p><p>Acceso en la plataforma: ${esc(PROFILES[p.accessProfile]||'Sin perfil')} · ${esc(({active:'Activa',inactive:'Inactiva',suspended:'Suspendida temporalmente',pending:'Invitación pendiente'})[p.status])}${p.mainAdmin?' · Administración principal':''}</p><small>Vinculación: ${date(p.startsAt)} → ${date(p.expiresAt)}</small></div><div>${can('users.manage')?button('usuarios/'+p.id,'Editar persona'):''}${p.status==='pending'&&can('people.validate')?`<button class="button secondary" data-access-command="person.validate" data-id="${p.id}">Validar persona</button>`:''}${can('permissions.manage')||can('permissions.revoke')?button('permisos/'+p.id,'Gestionar acceso'):''}</div></article>`).join('')+button('usuarios','Agregar persona'))+(can('users.manage')?panel(person?'Actualizar persona y vinculación':'Agregar persona',personForm(person||{})+'<p>Actualizar cargo conserva la persona y su historial. El perfil sugerido cambia con el cargo. Revisá sus permisos adicionales: no se eliminan automáticamente.</p>'):'')+(can('people.invite')?panel('Invitar persona',personForm({},{invite:true})):'' )+(can('profiles.manage')?panel('Actualizar perfil de acceso',form('profile.save',select('Persona','id',s.patrons.filter(p=>p.id!==actor.id).map(p=>[p.id,p.name]))+select('Perfil de acceso','accessProfile',Object.entries(PROFILES)))):'');}
 if(base==='permisos'){title='Gestionar acceso';const target=s.patrons.find(p=>p.id===id)||s.patrons.find(p=>p.id!==actor.id);html=panel('Permisos adicionales','<p>El cargo no cambia. El permiso solo vale en esta institución. Los vencimientos se aplican por fecha y hora del dispositivo.</p>'+(!target?'<p>Agregá otra persona primero.</p>':can('permissions.manage')?form('grant.add',select('Persona','userId',s.patrons.filter(p=>p.id!==actor.id).map(p=>[p.id,p.name+' · '+p.cargo]),target.id)+select('Permiso','permission',Object.entries(LABELS).filter(([p])=>!RESTRICTED.includes(p)))+select('Duración','duration',[['permanent','Permanente'],['temporary','Temporal']])+field('Desde (opcional)','startsAt','','datetime-local')+field('Hasta: fecha y hora','expiresAt','','datetime-local','disabled')+field('Motivo','note','','text','placeholder="Jornada de catalogación, inventario, suplencia…"'),'Otorgar permiso'):''))+panel('Historial de permisos',s.grants.filter(g=>!id||g.userId===id).map(g=>`<article class="holding-row"><div><strong>${esc(s.patrons.find(p=>p.id===g.userId)?.name)} · ${esc(LABELS[g.permission])}</strong><p>${g.expiredAt?'Vencido':g.active?'Vigente o programado':'Revocado'} · ${date(g.startsAt)} → ${date(g.expiresAt)}</p><p>${esc(g.note)}</p></div>${g.active&&can('permissions.revoke')?`<button class="button danger" data-access-command="grant.revoke" data-id="${g.id}">Revocar permiso</button>`:''}</article>`).join('')||'<p>No hay permisos adicionales.</p>');}
 if(base==='organizacion'){title='Institución';html=localNotice+panel(esc(c.institutionName),form('settings.save',(can('institution.edit')?field('Nombre de la institución','institutionName',c.institutionName,'text','required'):'')+(can('library.configure')?field('Nombre de la biblioteca','libraryName',c.libraryName,'text','required'):''))+button('registro','Registrar otra institución'));if(can('policy.configure'))html+=panel('Políticas de préstamo',form('settings.save',select('Permitir reservas','allowReservations',[['true','Sí'],['false','No']],String(c.policy?.allowReservations!==false))+select('Permitir una renovación si no hay reservas ni atraso','allowRenewals',[['false','No'],['true','Sí']],String(c.policy?.allowRenewals===true))+select('Habilitar préstamos a Personal Institucional','allowStaffLoans',[['false','No'],['true','Sí']],String(c.policy?.allowStaffLoans===true))+field('Días de renovación','loanDays',c.policy?.loanDays||14,'number','min="1" max="90"')));if(actor.mainAdmin)html+=`<section class="panel settings-panel danger-zone"><h2>Zona de peligro</h2><p>Transferir la administración principal quita tu responsabilidad especial. Desactivar la institución suspende todos sus accesos sin borrar historial.</p>${form('institution.transfer',select('Nueva administración principal','userId',s.patrons.filter(p=>p.id!==actor.id&&isEnabled(p)).map(p=>[p.id,p.name]))+field('Confirmá escribiendo el nombre de la institución','confirm','','text','required'),'Transferir administración')}${form('institution.disable',field('Confirmá el nombre de la institución','confirm','','text','required'),'Desactivar institución')}</section>`;}
 if(base==='inicio'){title=c.institutionName;const own=s.loans.filter(l=>l.patron.id===actor.id&&activeLoan(l)),res=s.reservations.filter(r=>r.patron.id===actor.id&&activeReservation(r)),profile=actor.accessProfile;html=`<p>${esc(actor.name)} · Cargo: ${esc(actor.cargo)} · Acceso: ${esc(PROFILES[profile]||'Sin perfil')}${actor.mainAdmin?' · Administración inicial/principal':''}</p>`;if(c.onboardingStep&&actor.mainAdmin)html+=panel('Terminá de configurar tu institución',button('bienvenida/'+(c.onboardingStep===1?'biblioteca':'equipo'),'Continuar configuración'));
 if(profile==='autoridad')html+=panel('Resumen institucional',`<p>${s.patrons.length} personas · ${s.books.length} materiales · ${s.loans.filter(activeLoan).length} préstamos activos</p><div class="button-row">${button('usuarios','Personas y accesos')}${button('actividad','Actividad')}${button('organizacion','Configuración')}${button('biblioteca','Supervisar biblioteca')}</div>`);
 else{html+=panel(profile==='lector'?'Buscá en la biblioteca':'¿Qué estás buscando?',`<form id="home-search" class="home-search"><label>Palabras, frases, temas o contenidos<input id="home-query" name="query" type="search" placeholder="Por ejemplo: Segunda Guerra Mundial"></label><button class="button primary">Buscar materiales</button></form>`);if(profile==='biblioteca')html+=panel('Resumen de biblioteca',`<p>${s.books.length} materiales · ${s.books.reduce((n,b)=>n+b.exemplars.length,0)} ejemplares · ${s.loans.filter(activeLoan).length} préstamos activos</p><p>${s.grants.filter(g=>isEnabled(g)&&g.expiresAt).length} permisos temporales activos · ${s.invitations.filter(i=>i.status==='pending').length} invitaciones pendientes</p><div class="button-row">${button('agregar','Incorporar material')}${button('circulacion','Préstamos y reservas')}${button('usuarios','Equipo')}${button('inventario','Inventario y ejemplares')}</div>`);else html+=panel('Mi biblioteca',`<p>${own.length} préstamos activos · ${res.length} reservas</p><div class="button-row">${button('circulacion','Mis préstamos y reservas')}${button('guardados','Materiales guardados')}${button('temas','Explorar temas')}</div><p>Las recomendaciones y novedades personalizadas se incorporarán en una etapa futura.</p>`);}
 if(profile==='docente')html+=TEACHER_DISCOVERY;
 const extra=s.grants.find(g=>g.userId===actor.id&&g.permission==='catalog.create'&&isEnabled(g));if(can('catalog.create')&&profile!=='biblioteca')html+=panel(extra?.expiresAt?'Tenés un permiso temporal para incorporar materiales.':'Podés incorporar materiales.',`${extra?.expiresAt?'<p>Hasta '+date(extra.expiresAt)+'</p>':''}${button('agregar','Incorporar material')}`);
 if(can('holdings.create')||can('holdings.edit')||can('inventory.manage'))html+=panel('Ejemplares e inventario',button('inventario','Gestionar ejemplares'));
 if(can('topics.manage')||can('contents.manage'))html+=panel('Contenido y temas',button('temas','Gestionar temas y contenidos'));}
 if(base==='temas'){title='Temas y contenidos';html=s.books.map(b=>panel(esc(b.title),`<p>${esc((b.subjects||[]).join(' · '))}</p>${button('ficha/'+b.id,'Ver material')}${can('topics.manage')?form('material.topics',`<input type="hidden" name="id" value="${b.id}"><label>Temas y palabras clave (uno por línea)<textarea name="value">${esc((b.subjects||[]).join('\n'))}</textarea></label>`):''}${can('contents.manage')?form('material.contents',`<input type="hidden" name="id" value="${b.id}"><label>Contenidos internos (uno por línea)<textarea name="value">${esc((b.contents||[]).map(x=>typeof x==='string'?x:x.title).join('\n'))}</textarea></label>`):''}`)).join('')||panel('Temas','Todavía no hay materiales.');}
 if(base==='inventario'){title='Inventario y ejemplares';html=can('holdings.create')?panel('Agregar ejemplares a un material',form('copy.add',select('Material','bookId',s.books.map(b=>[b.id,b.title]))+field('Cantidad','quantity',1,'number','min="1" max="100" required')+field('Ubicación','location'),'Agregar ejemplares')):'';html+=panel('Inventario',s.books.flatMap(b=>b.exemplars.map(e=>'<article class="holding-row"><div><strong>'+esc(e.internalCode)+' · '+esc(b.title)+'</strong><p>'+esc(e.location)+'</p></div>'+button('ejemplar/'+e.id,'Consultar ejemplar')+'</article>')).join('')||'<p>No hay ejemplares.</p>');}
 if(base==='guardados'){title='Materiales guardados';html=panel('Elegí materiales para volver a encontrarlos',s.books.map(b=>`<article class="holding-row"><strong>${esc(b.title)}</strong>${button('ficha/'+b.id,'Ver material')}<button class="button secondary" data-access-command="saved.toggle" data-book-id="${b.id}">${s.saved.some(x=>x.personId===actor.id&&x.bookId===b.id)?'Quitar de guardados':'Guardar material'}</button></article>`).join('')||'<p>Todavía no hay materiales.</p>');}
 if((location.hash.slice(1)||'inicio')!==route)return true;
 document.querySelector('#main').innerHTML=`<div class="page-heading"><h1>${esc(title)}</h1></div><p id="access-feedback" role="status"></p>`+html;for(const input of document.querySelectorAll('[name=customCargo]')){const custom=input.form.querySelector('[name=cargo]').value==='Otro';input.closest('label').hidden=!custom;input.required=custom;}return true;
}
function personForm(p,{invite=false}={}){return form(invite?'person.invite':'person.save',(!p.id?select('Persona local existente (opcional)','existingPerson',[['','Crear una nueva persona'],...knownPeople.map(p=>[p.id,p.name])]):'')+`<input name="id" type="hidden" value="${esc(p.id||'')}">`+field('Nombre y apellido','name',p.name,'text','required maxlength="160"')+field('Correo','email',p.email,'email')+cargo(p.cargo||'Docente')+field('Curso / referencia','course',p.course)+select('Acceso en la plataforma','accessProfile',Object.entries(PROFILES),p.accessProfile||'docente')+(invite?'':select('Estado de vinculación','status',[['active','Activa'],['inactive','Inactiva'],['suspended','Suspendida temporalmente'],['pending','Invitación pendiente']],p.status||'active')+field('Inicio de vinculación o suplencia','startsAt',dt(p.startsAt),'datetime-local')+field('Fin de vinculación / fin de suspensión','expiresAt',dt(p.expiresAt),'datetime-local'))+field('Motivo / referencia','note'),invite?'Agregar persona · invitación pendiente':'Guardar persona');}
