import {requirePermission,hasPermission,isEnabled,validWindow,grantRecord,PROFILES,LIBRARY,RESTRICTED,suggestProfile,legacyProfile,profileRole,canManageTarget} from './permissions.js?v=20261010-1';
import {normalizeLoanPolicy,reservationExpiryFromPolicy} from './loan-policy.js?v=20261010-1';
const text=v=>String(v||'').trim().slice(0,160);
export function logAccess(s,type,actorId,details={}){s.activity.push({id:crypto.randomUUID(),type,actorId,institutionId:s.institutionId||s.institutions[0]?.id,createdAt:new Date().toISOString(),...details});}
export function expireAccess(s,at=Date.now()){for(const g of s.grants)if(g.active!==false&&g.expiresAt&&Date.parse(g.expiresAt)<=at){g.active=false;g.expiredAt=new Date(at).toISOString();logAccess(s,'permission.expired','system',{userId:g.userId,permission:g.permission,startsAt:g.startsAt,expiresAt:g.expiresAt,note:g.note});}for(const m of s.memberships||[])if(['active','suspended'].includes(m.status)&&m.expiresAt&&Date.parse(m.expiresAt)<=at){const suspended=m.status==='suspended';m.status=suspended?'active':'inactive';const ended=m.expiresAt;if(suspended)m.expiresAt='';logAccess(s,suspended?'membership.suspension.ended':'membership.expired','system',{userId:m.personId,expiresAt:m.expiresAt});const p=s.patrons.find(p=>p.id===m.personId);if(p){p.status=m.status;p.active=m.status==='active';p.expiresAt=m.expiresAt;}}}
export function accessCommand(s,actorId,type,d={}){
 const actor=s.patrons.find(p=>p.id===actorId),iid=s.institutionId||s.institutions[0]?.id,require=p=>requirePermission(s,actorId,p),audit=(t,v)=>logAccess(s,t,actorId,v),now=new Date().toISOString();
 if(type==='person.validate'){require('people.validate');const m=s.memberships.find(m=>m.personId===d.id);if(!m||m.status!=='pending')throw new Error('Solo se validan invitaciones pendientes.');if(d.id===actorId)throw new Error('No podés validar tu propio acceso.');if(m.accessProfile==='autoridad'&&!actor.mainAdmin||m.accessProfile==='biblioteca'&&!actor.mainAdmin&&!hasPermission(actor,'profiles.manage',s.grants))throw new Error('La autoridad correspondiente debe validar este perfil de gestión.');m.status='active';for(const invite of s.invitations.filter(i=>i.personId===d.id&&i.status==='pending'))invite.status='validated-local';audit('membership.validated',{userId:d.id});return;}
 if(type==='profile.save'){require('profiles.manage');const m=s.memberships.find(m=>m.personId===d.id);if(!m||!PROFILES[d.accessProfile])throw new Error('Perfil o persona inválidos.');if(d.id===actorId)throw new Error('No podés cambiar tu propio perfil.');const target=s.patrons.find(p=>p.id===d.id);if(!canManageTarget(actor,target))throw new Error('Tu perfil no puede modificar el acceso de esta persona.');if(d.accessProfile==='autoridad'&&!actor.mainAdmin)throw new Error('Solo la administración principal habilita autoridades.');const before=m.accessProfile;m.accessProfile=d.accessProfile;audit('profile.updated',{userId:d.id,before,after:m.accessProfile});return;}
 if(type==='copy.add'){require('holdings.create');const b=s.books.find(b=>b.id===d.bookId);if(!b)throw new Error('Material inexistente.');const quantity=Number(d.quantity);if(!Number.isInteger(quantity)||quantity<1||quantity>100)throw new Error('Indicá de 1 a 100 ejemplares.');for(let n=0;n<quantity;n++){const copy={id:crypto.randomUUID(),location:text(d.location),condition:'Bueno',status:'available',physicalLocation:{},createdAt:now};b.exemplars.push(copy);audit('holding.created',{bookId:b.id,exemplarId:copy.id});}return;}
 if(type==='user.save'||type==='person.save'||type==='person.invite'){
  require(type==='person.invite'?'people.invite':'users.manage');
  const old=s.memberships.find(m=>m.personId===d.id);const person=s.people.find(p=>p.id===d.id);const cargo=text(d.cargo||old?.cargo||d.role);const profile=d.accessProfile??(d.role!==undefined?legacyProfile(d.role):suggestProfile(cargo));
  if(!text(d.name)||!cargo)throw new Error('Completá nombre y cargo.');if(profile&&!PROFILES[profile])throw new Error('Perfil inválido.');validWindow(d.startsAt,d.expiresAt);
  if(d.id===actorId&&old&&(cargo!==old.cargo||profile!==old.accessProfile||d.status&&d.status!==old.status))throw new Error('Otra persona autorizada debe modificar tu propio cargo o acceso.');
  if(old&&!canManageTarget(actor,{...s.patrons.find(p=>p.id===d.id),accessProfile:old.accessProfile,mainAdmin:s.institutions[0]?.mainAdminId===d.id}))throw new Error('Tu perfil no puede modificar a esta persona.');
  if(!old||profile!==old.accessProfile){if(profile==='autoridad'&&!actor.mainAdmin)throw new Error('Solo la administración principal puede asignar Autoridad Institucional.');if(!actor.mainAdmin&&!hasPermission(actor,'profiles.manage',s.grants)&&profile==='biblioteca')throw new Error('La autoridad institucional debe habilitar nuevos responsables.');if(old&&profile!==old.accessProfile)require('profiles.manage');}
  const status=d.status||(d.active===false?'inactive':type==='person.invite'?'pending':'active');if(!['active','inactive','suspended','pending'].includes(status))throw new Error('Estado inválido.');if(status==='active'&&old?.status!=='active')require('people.validate');
  if(s.institutions[0]?.mainAdminId===d.id&&(status!=='active'||d.expiresAt||d.startsAt&&Date.parse(d.startsAt)>Date.now()))throw new Error('Transferí la administración principal antes de desactivar o limitar esta vinculación.');
  const p=person||{id:crypto.randomUUID()};Object.assign(p,{name:text(d.name),email:text(d.email||person?.email)});if(!person)s.people.push(p);
  if(status==='suspended'&&!d.expiresAt)throw new Error('Indicá cuándo termina la suspensión.');
  const m={...old,id:old?.id||crypto.randomUUID(),personId:p.id,institutionId:iid,cargo,accessProfile:profile,status,course:text(d.course),startsAt:d.startsAt||'',expiresAt:d.expiresAt||'',updatedAt:now,updatedBy:actorId};if(old)s.memberships.splice(s.memberships.indexOf(old),1,m);else s.memberships.push(m);
  if(type==='person.invite')s.invitations.push({id:crypto.randomUUID(),personId:p.id,institutionId:iid,status:'pending',simulated:true,createdAt:now,createdBy:actorId});
  if(status==='active')for(const invite of s.invitations.filter(i=>i.personId===p.id&&i.status==='pending'))invite.status='validated-local';
  audit(old?'membership.updated':type==='person.invite'?'invitation.pending':'membership.created',{userId:p.id,before:old||null,after:m,note:text(d.note),startsAt:m.startsAt,expiresAt:m.expiresAt});return {...p,...m,id:p.id,role:profileRole(profile)};
 }
 if(type==='grant.add'||type==='grant.revoke'){
  require(type==='grant.add'?'permissions.manage':'permissions.revoke');const existing=s.grants.find(g=>g.id===d.id);const permission=type==='grant.add'?d.permission:existing?.permission;const target=type==='grant.add'?d.userId:existing?.userId;
  if(!target||!s.patrons.some(p=>p.id===target))throw new Error('Persona inexistente en esta institución.');if(target===actorId)throw new Error('No podés asignarte ni modificar tus propios permisos.');const targetUser=s.patrons.find(p=>p.id===target);if(!canManageTarget(actor,targetUser))throw new Error('Tu perfil no puede administrar los permisos de esta persona.');if(RESTRICTED.includes(permission))throw new Error('Esta responsabilidad no se delega mediante permisos adicionales.');
  if(!actor.mainAdmin&&actor.accessProfile!=='autoridad'&&(!LIBRARY.includes(permission)||['permissions.manage','permissions.revoke','users.manage','people.validate'].includes(permission)))throw new Error('Solo podés delegar permisos operativos de biblioteca.');
  if(!actor.mainAdmin&&actor.accessProfile!=='autoridad'&&!hasPermission(actor,permission,s.grants))throw new Error('No podés delegar un permiso que no tenés.');
  if(type==='grant.add'){if(d.duration==='temporary'&&!d.expiresAt)throw new Error('Indicá fecha y hora de vencimiento.');if(d.expiresAt&&Date.parse(d.expiresAt)<=Date.now())throw new Error('El vencimiento debe estar en el futuro.');const g={...grantRecord(d,actorId),institutionId:iid};s.grants.push(g);audit('permission.granted',{userId:target,permission,grantId:g.id,startsAt:g.startsAt,expiresAt:g.expiresAt,note:g.note});return g;}
  existing.active=false;existing.revokedAt=now;existing.revokedBy=actorId;audit('permission.revoked',{userId:target,permission,note:existing.note});return;
 }
 if(type==='institution.transfer'){require('institution.transfer');const nextAdmin=s.patrons.find(p=>p.id===d.userId&&isEnabled(p)&&!p.expiresAt&&p.accessProfile==='autoridad');if(d.userId===actorId||!nextAdmin)throw new Error('Seleccioná otra Autoridad Institucional activa y con vinculación sin vencimiento.');const inst=s.institutions[0];if(d.confirm!==inst.name)throw new Error('Escribí el nombre de la institución para confirmar.');inst.mainAdminId=d.userId;audit('institution.admin.transferred',{userId:d.userId,before:actorId});return;}
 if(type==='institution.disable'){require('institution.disable');if(d.confirm!==s.institutions[0].name)throw new Error('Escribí el nombre de la institución para confirmar.');s.institutions[0].status='inactive';for(const m of s.memberships)m.status='inactive';audit('institution.disabled',{});return;}
 if(type==='settings.save'||type==='onboarding.library'||type==='onboarding.finish'){
  const c=s.settings.find(x=>x.id==='local');
  if(type==='settings.save'){
   if(d.institutionName!==undefined){require('institution.edit');c.institutionName=text(d.institutionName);s.institutions[0].name=c.institutionName;}
   if(d.libraryName!==undefined){require('library.configure');c.libraryName=text(d.libraryName);}
   if(d.allowRenewals!==undefined){require('policy.configure');c.policy=normalizeLoanPolicy({allowRenewals:d.allowRenewals==='true',allowReservations:d.allowReservations==='true',allowStaffLoans:d.allowStaffLoans==='true',blockNewLoansIfOverdue:d.blockNewLoansIfOverdue==='true',overdueGraceDays:Number(d.overdueGraceDays),renewalRequestWindowDays:Number(d.renewalRequestWindowDays),renewalExtensionDays:Number(d.renewalExtensionDays),reservationPickupDays:Number(d.reservationPickupDays),profiles:{autoridad:{loanDays:d.autoridadLoanDays,maxLoans:d.autoridadMaxLoans},biblioteca:{loanDays:d.bibliotecaLoanDays,maxLoans:d.bibliotecaMaxLoans},docente:{loanDays:d.docenteLoanDays,maxLoans:d.docenteMaxLoans},personal:{loanDays:d.personalLoanDays,maxLoans:d.personalMaxLoans},lector:{loanDays:d.lectorLoanDays,maxLoans:d.lectorMaxLoans}}});}
  }else{if(!actor.mainAdmin)throw new Error('Solo la administración inicial puede completar esta configuración.');if(type==='onboarding.library'){c.libraryName=text(d.libraryName)||'Biblioteca de '+c.institutionName;if(d.responsible==='self'){const m=s.memberships.find(m=>m.personId===actorId);m.accessProfile='biblioteca';}if(d.responsible==='other')accessCommand(s,actorId,'person.invite',{name:d.name,email:d.email,cargo:d.cargo||'Bibliotecario/a',accessProfile:'biblioteca'});c.onboardingStep=2;}else c.onboardingStep=0;}
  audit(type,{});return;
 }
 if(type==='material.topics'||type==='material.contents'){require(type==='material.topics'?'topics.manage':'contents.manage');const b=s.books.find(b=>b.id===d.id);if(!b)throw new Error('Material inexistente.');const key=type==='material.topics'?'subjects':'contents';const values=String(d.value||'').split('\n').map(text).filter(Boolean);for(const other of s.books.filter(x=>x.workId===b.workId))other[key]=values;audit(type,{bookId:b.id});return;}
 if(type==='saved.toggle'){require('catalog.view');if(!s.books.some(b=>b.id===d.bookId))throw new Error('Material inexistente.');const old=s.saved.find(x=>x.personId===actorId&&x.bookId===d.bookId);if(old)s.saved.splice(s.saved.indexOf(old),1);else s.saved.push({id:crypto.randomUUID(),personId:actorId,bookId:d.bookId,institutionId:iid});return;}
 return false;
}
