// Presentation only. Read the institution-scoped state and existing permission checks.
import {PROFILES,isEnabled} from './permissions.js?v=20261009-8';
import {activeLoan,activeReservation,config} from './local-domain.js?v=20261009-8';
import {normalizeLoanPolicy,renewalRequestStatus,overdueLoansForPatron} from './loan-policy.js?v=20261009-8';
import {suggestedQueries} from './search-engine.js?v=20261009-8';
import {libraryAnalytics} from './analytics.js?v=20261009-8';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const action=(route,label,detail,icon)=>`<a class="dashboard-action" href="#${route}"><span class="action-symbol" aria-hidden="true">${icon}</span><span><strong>${label}</strong><small>${detail}</small></span><span aria-hidden="true">↗</span></a>`;
const statistic=(label,n,route)=>`<a href="#${route}" class="dashboard-stat"><strong>${n}</strong><span>${label}</span></a>`;
const eventNames={'book.created':'Material incorporado','book.saved':'Material actualizado','book.deleted':'Material eliminado','material.created':'Material incorporado','material.updated':'Material actualizado','loan.created':'Préstamo registrado','loan.returned':'Devolución registrada','loan.renewal.requested':'Extensión solicitada','loan.renewal.approved':'Extensión autorizada','loan.renewal.rejected':'Extensión rechazada','reservation.created':'Reserva solicitada','reservation.updated':'Reserva actualizada','membership.created':'Persona incorporada','membership.updated':'Vinculación actualizada','profile.updated':'Perfil actualizado','permission.granted':'Permiso habilitado','permission.revoked':'Permiso revocado','institution.created':'Institución registrada','settings.updated':'Configuración actualizada','search.performed':'Búsqueda realizada','search.no_results':'Búsqueda sin resultados','collection.need.created':'Necesidad registrada','collection.need.updated':'Necesidad actualizada','recommendation.created':'Recomendación creada','recommendation.updated':'Recomendación actualizada','recommendation.archived':'Recomendación archivada'};
export function renderDashboard(s,actor,c,can){
 const manager=['biblioteca','autoridad'].includes(actor.accessProfile),own=s.loans.filter(l=>l.patron.id===actor.id&&activeLoan(l)),res=s.reservations.filter(r=>r.patron.id===actor.id&&activeReservation(r)),policy=normalizeLoanPolicy(config(s).policy||{}),renewalPending=s.loans.filter(l=>activeLoan(l)&&l.renewalRequest?.status==='pending'),analytics=libraryAnalytics(s);
 const create=can('catalog.create'),extra=s.grants.find(g=>g.userId===actor.id&&g.permission==='catalog.create'&&isEnabled(g));
 const examples=suggestedQueries(s.books,4);const search=`<form id="home-search" class="home-search dashboard-search"><label for="home-query">Palabras, frases, temas o contenidos</label><div><input id="home-query" name="query" type="search" placeholder="Por ejemplo: cuento de monstruos para quinto"><button class="button primary">Buscar materiales</button></div></form>${examples.length?`<div class="query-examples"><span>Explorar por tema</span>${examples.map(q=>`<button type="button" data-query="${esc(q)}">${esc(q)} ↗</button>`).join('')}</div>`:''}`;
 let html=`<section class="dashboard" data-dashboard="${esc(actor.accessProfile)}"><p class="dashboard-identity">${esc(actor.name)} · ${esc(actor.cargo)} <span>${esc(PROFILES[actor.accessProfile]||'Sin perfil')}</span></p>`;
 if(c.onboardingStep&&actor.mainAdmin)html+=`<aside class="dashboard-onboarding"><span>Terminá de configurar tu institución</span><a class="button secondary" href="#bienvenida/${c.onboardingStep===1?'biblioteca':'equipo'}">Continuar configuración</a></aside>`;
 html+=`<div class="dashboard-heading"><span class="eyebrow">${esc(c.libraryName||'TU BIBLIOTECA')}</span><h2>${manager?'¿Qué necesitás hacer hoy?':'¿Qué necesitás encontrar hoy?'}</h2><p>${manager?'Organizá las tareas de la biblioteca desde un mismo lugar.':'Buscá en los títulos, temas y contenidos de tu colección.'}</p></div>`;
 if(!manager)html+=search;
 html+='<nav class="dashboard-actions" aria-label="Accesos principales">';
 if(manager){if(create)html+=action('agregar','Agregar al catálogo','Reconocer, revisar y completar.','＋');if(can('collection.needs.manage')||can('recommendations.manage'))html+=action('coleccion','Planificar colección','Necesidades y recomendaciones internas.','◇');if(can('circulation.loan')||can('circulation.return'))html+=action('circulacion','Prestar / devolver','Consultar la circulación.','⇄');if(can('reservations.manage'))html+=action('reservas','Reservas pendientes',s.reservations.filter(activeReservation).length+' solicitudes en curso.','◷');if(can('circulation.renew.approve')&&renewalPending.length)html+=action('circulacion','Extensiones pendientes',renewalPending.length+' por autorizar.','↻');html+=action('ejemplares','Buscar ejemplar','Ubicación y disponibilidad.','⌕');if(!create)html+=action('biblioteca','Consultar catálogo','Materiales de la institución.','▥');if(!create&&(can('users.manage')||can('people.invite')))html+=action('usuarios','Personas y accesos','El equipo de tu institución.','◎');}
 else{html+=action('reservas','Mis reservas',res.length+' en curso.','◷')+action('circulacion','Mis préstamos',own.length+' activos.','⇄')+action('temas','Explorar por tema','Palabras y contenidos registrados.','⌕')+'<button class="dashboard-action" type="button" data-dashboard-scroll="inicio-novedades"><span class="action-symbol" aria-hidden="true">↗</span><span><strong>Novedades</strong><small>Últimas incorporaciones al catálogo.</small></span><span aria-hidden="true">↓</span></button>';if(create)html+=action('agregar','Agregar al catálogo',extra?.expiresAt?'Permiso temporal hasta '+new Date(extra.expiresAt).toLocaleString('es-AR'):'Permiso habilitado por tu institución.','＋');}
 html+='</nav>';
 if(manager){html+=`<section class="dashboard-summary"><h3>${actor.accessProfile==='autoridad'?'Resumen institucional':'Resumen de biblioteca'}</h3><div class="dashboard-stats">${statistic('Materiales',s.books.length,'biblioteca')}${statistic('Ejemplares',s.books.reduce((n,b)=>n+b.exemplars.length,0),'ejemplares')}${statistic('Préstamos activos',s.loans.filter(activeLoan).length,'circulacion')}${statistic('Reservas',s.reservations.filter(activeReservation).length,'reservas')}${statistic('Búsquedas sin resultado',s.activity.filter(a=>a.type==='search.no_results').length,'actividad')}</div></section>`+search;
 if(can('reports.view')||can('institution.stats')){
  html+=`<section class="dashboard-insights"><div class="section-heading"><div><span class="eyebrow">USO Y NECESIDADES</span><h3>Qué está pasando en la biblioteca</h3></div><div class="button-row"><a class="button secondary" href="#coleccion">Planificar colección</a><a class="button secondary" href="#actividad">Ver historial</a></div></div><div class="dashboard-stats">${statistic('Nunca prestados',analytics.neverLoaned.length,'biblioteca')}${statistic('Deteriorados',analytics.damaged.length,'ejemplares')}${statistic('Vencidos',analytics.overdue.length,'circulacion')}${statistic('Búsquedas sin resultado',analytics.totals.searchesWithoutResults,'actividad')}</div>${analytics.topLoaned.length?`<div class="insight-list"><h4>Más prestados</h4><ol>${analytics.topLoaned.map(x=>`<li><a href="#ficha/${esc(x.book.id)}"><span>${esc(x.book.title)}</span><strong>${x.count}</strong></a></li>`).join('')}</ol></div>`:''}${analytics.unmetDemand.length?`<div class="insight-list"><h4>Lo que se busca y no aparece</h4><ol>${analytics.unmetDemand.map(x=>`<li><span>${esc(x.query)}</span><strong>${x.count}</strong></li>`).join('')}</ol><p class="muted">Puede servir como señal para adquisiciones o incorporación de materiales.</p></div>`:''}</section>`;
 }
 if(can('reports.view')||can('institution.stats'))html+=`<section class="dashboard-activity"><div class="section-heading"><h3>Actividad reciente</h3><a class="button secondary" href="#actividad">Ver historial</a></div>${s.activity.length?'<ol>'+s.activity.slice().reverse().slice(0,5).map(a=>`<li><span><strong>${esc(eventNames[a.type]||'Actividad de la biblioteca')}</strong><small>${esc(a.title||a.internalCode||s.patrons.find(p=>p.id===a.userId)?.name||'Movimiento registrado en esta institución')}</small></span><time datetime="${esc(a.createdAt)}">${esc(new Date(a.createdAt).toLocaleDateString('es-AR'))}</time></li>`).join('')+'</ol>':'<p class="muted">Todavía no hay movimientos registrados.</p>'}</section>`;
 }else{const eligible=own.filter(l=>renewalRequestStatus(l,policy,{reservations:s.reservations,book:s.books.find(b=>b.id===l.bookId)}).allowed),pending=own.filter(l=>l.renewalRequest?.status==='pending'),overdue=overdueLoansForPatron(s.loans,actor.id,policy),recs=(s.recommendations||[]).filter(r=>r.status==='active'&&s.books.some(b=>b.id===r.bookId)).slice(0,6);html+=`<section class="dashboard-personal"><h3>Mi biblioteca</h3><p>${own.length} préstamos activos · ${res.length} reservas</p>${overdue.length?`<p class="notice">${overdue.length===1?'Tenés un préstamo vencido.':'Tenés '+overdue.length+' préstamos vencidos.'} <a href="#circulacion">Revisar préstamos</a></p>`:''}${eligible.length?`<p class="notice">${eligible.length===1?'Tenés un préstamo próximo a vencer que puede solicitar extensión.':'Tenés '+eligible.length+' préstamos próximos a vencer que pueden solicitar extensión.'} <a href="#circulacion">Revisar préstamos</a></p>`:''}${pending.length?`<p class="muted">${pending.length} solicitud${pending.length===1?'':'es'} de extensión pendiente${pending.length===1?'':'s'} de autorización.</p>`:''}<a class="button secondary" href="#guardados">Materiales guardados</a></section>`;
 if(recs.length)html+=`<section class="dashboard-recommendations"><div class="section-heading"><div><span class="eyebrow">RECOMENDADOS POR LA BIBLIOTECA</span><h3>Para explorar</h3></div></div><div class="recommendation-grid">${recs.map(r=>`<a href="#ficha/${esc(r.bookId)}"><strong>${esc(r.title)}</strong>${r.audience?`<span>${esc(r.audience)}</span>`:''}<p>${esc(r.reason||'Recomendado por la biblioteca.')}</p></a>`).join('')}</div></section>`;}
 const recent=[...s.books].sort((a,b)=>(b.createdAt||'').localeCompare(a.createdAt||'')).slice(0,4);
 html+=`<section id="inicio-novedades" class="dashboard-recent"><div class="section-heading"><h3>Últimas incorporaciones</h3><a class="button secondary" href="#biblioteca">Ver catálogo</a></div>${recent.length?'<div class="recent-grid">'+recent.map(b=>`<a href="#ficha/${esc(b.id)}"><span class="recent-cover" aria-hidden="true">${esc((b.title||'Material').slice(0,1))}</span><span><strong>${esc(b.title)}</strong><small>${esc(b.author||b.publication||'Material de la institución')}</small></span></a>`).join('')+'</div>':'<p class="muted">Los materiales nuevos aparecerán acá cuando se incorporen al catálogo.</p>'}</section></section>`;
 return html;
}
