// Presentation only. Read the institution-scoped state and existing permission checks.
import {PROFILES,isEnabled} from './permissions.js?v=20261006-3';
import {activeLoan,activeReservation} from './local-domain.js?v=20261006-3';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const action=(route,label,detail,icon)=>`<a class="dashboard-action" href="#${route}"><span class="action-symbol" aria-hidden="true">${icon}</span><span><strong>${label}</strong><small>${detail}</small></span><span aria-hidden="true">↗</span></a>`;
const statistic=(label,n,route)=>`<a href="#${route}" class="dashboard-stat"><strong>${n}</strong><span>${label}</span></a>`;
const eventNames={'book.created':'Material incorporado','book.saved':'Material actualizado','book.deleted':'Material eliminado','material.created':'Material incorporado','material.updated':'Material actualizado','loan.created':'Préstamo registrado','loan.returned':'Devolución registrada','reservation.created':'Reserva solicitada','reservation.updated':'Reserva actualizada','membership.created':'Persona incorporada','membership.updated':'Vinculación actualizada','profile.updated':'Perfil actualizado','permission.granted':'Permiso habilitado','permission.revoked':'Permiso revocado','institution.created':'Institución registrada','settings.updated':'Configuración actualizada'};
export function renderDashboard(s,actor,c,can){
 const manager=['biblioteca','autoridad'].includes(actor.accessProfile),own=s.loans.filter(l=>l.patron.id===actor.id&&activeLoan(l)),res=s.reservations.filter(r=>r.patron.id===actor.id&&activeReservation(r));
 const create=can('catalog.create'),extra=s.grants.find(g=>g.userId===actor.id&&g.permission==='catalog.create'&&isEnabled(g));
 const search=`<form id="home-search" class="home-search dashboard-search"><label for="home-query">Palabras, frases, temas o contenidos</label><div><input id="home-query" name="query" type="search" placeholder="Por ejemplo: Segunda Guerra Mundial"><button class="button primary">Buscar materiales</button></div></form>`;
 let html=`<section class="dashboard" data-dashboard="${esc(actor.accessProfile)}"><p class="dashboard-identity">${esc(actor.name)} · ${esc(actor.cargo)} <span>${esc(PROFILES[actor.accessProfile]||'Sin perfil')}</span></p>`;
 if(c.onboardingStep&&actor.mainAdmin)html+=`<aside class="dashboard-onboarding"><span>Terminá de configurar tu institución</span><a class="button secondary" href="#bienvenida/${c.onboardingStep===1?'biblioteca':'equipo'}">Continuar configuración</a></aside>`;
 html+=`<div class="dashboard-heading"><span class="eyebrow">${esc(c.libraryName||'TU BIBLIOTECA')}</span><h2>${manager?'¿Qué necesitás hacer hoy?':'¿Qué necesitás encontrar hoy?'}</h2><p>${manager?'Organizá las tareas de la biblioteca desde un mismo lugar.':'Buscá en los títulos, temas y contenidos de tu colección.'}</p></div>`;
 if(!manager)html+=search;
 html+='<nav class="dashboard-actions" aria-label="Accesos principales">';
 if(manager){if(create)html+=action('agregar','Agregar al catálogo','Reconocer, revisar y completar.','＋');if(can('circulation.loan')||can('circulation.return'))html+=action('circulacion','Prestar / devolver','Consultar la circulación.','⇄');if(can('reservations.manage'))html+=action('reservas','Reservas pendientes',s.reservations.filter(activeReservation).length+' solicitudes en curso.','◷');html+=action('ejemplares','Buscar ejemplar','Ubicación y disponibilidad.','⌕');if(!create)html+=action('biblioteca','Consultar catálogo','Materiales de la institución.','▥');if(!create&&(can('users.manage')||can('people.invite')))html+=action('usuarios','Personas y accesos','El equipo de tu institución.','◎');}
 else{html+=action('reservas','Mis reservas',res.length+' en curso.','◷')+action('circulacion','Mis préstamos',own.length+' activos.','⇄')+action('temas','Explorar por tema','Palabras y contenidos registrados.','⌕')+'<button class="dashboard-action" type="button" data-dashboard-scroll="inicio-novedades"><span class="action-symbol" aria-hidden="true">↗</span><span><strong>Novedades</strong><small>Últimas incorporaciones al catálogo.</small></span><span aria-hidden="true">↓</span></button>';if(create)html+=action('agregar','Agregar al catálogo',extra?.expiresAt?'Permiso temporal hasta '+new Date(extra.expiresAt).toLocaleString('es-AR'):'Permiso habilitado por tu institución.','＋');}
 html+='</nav>';
 if(manager){html+=`<section class="dashboard-summary"><h3>${actor.accessProfile==='autoridad'?'Resumen institucional':'Resumen de biblioteca'}</h3><div class="dashboard-stats">${statistic('Materiales',s.books.length,'biblioteca')}${statistic('Ejemplares',s.books.reduce((n,b)=>n+b.exemplars.length,0),'ejemplares')}${statistic('Préstamos activos',s.loans.filter(activeLoan).length,'circulacion')}${statistic('Reservas',s.reservations.filter(activeReservation).length,'reservas')}</div></section>`+search;
 if(can('reports.view')||can('institution.stats'))html+=`<section class="dashboard-activity"><div class="section-heading"><h3>Actividad reciente</h3><a class="button secondary" href="#actividad">Ver historial</a></div>${s.activity.length?'<ol>'+s.activity.slice().reverse().slice(0,5).map(a=>`<li><span><strong>${esc(eventNames[a.type]||'Actividad de la biblioteca')}</strong><small>${esc(a.title||a.internalCode||s.patrons.find(p=>p.id===a.userId)?.name||'Movimiento registrado en esta institución')}</small></span><time datetime="${esc(a.createdAt)}">${esc(new Date(a.createdAt).toLocaleDateString('es-AR'))}</time></li>`).join('')+'</ol>':'<p class="muted">Todavía no hay movimientos registrados.</p>'}</section>`;
 }else{html+=`<section class="dashboard-personal"><h3>Mi biblioteca</h3><p>${own.length} préstamos activos · ${res.length} reservas</p><a class="button secondary" href="#guardados">Materiales guardados</a></section>`;}
 const recent=[...s.books].sort((a,b)=>(b.createdAt||'').localeCompare(a.createdAt||'')).slice(0,4);
 html+=`<section id="inicio-novedades" class="dashboard-recent"><div class="section-heading"><h3>Últimas incorporaciones</h3><a class="button secondary" href="#biblioteca">Ver catálogo</a></div>${recent.length?'<div class="recent-grid">'+recent.map(b=>`<a href="#ficha/${esc(b.id)}"><span class="recent-cover" aria-hidden="true">${esc((b.title||'Material').slice(0,1))}</span><span><strong>${esc(b.title)}</strong><small>${esc(b.author||b.publication||'Material de la institución')}</small></span></a>`).join('')+'</div>':'<p class="muted">Los materiales nuevos aparecerán acá cuando se incorporen al catálogo.</p>'}</section></section>`;
 return html;
}
