import {parseArchive} from './catalog.js?v=20261006-1';
import {importAguapeyISO} from './marc.js?v=20261006-1';
import {STORES,activeLoan,activeReservation} from './local-domain.js?v=20261006-1';
import {PERMISSIONS,ROLES,isEnabled,validWindow} from './permissions.js?v=20261006-1';
export class ImportProvider{parse(){throw new Error('Implementar parse en el proveedor.');}}
export const AguapeyMarcProvider={id:'aguapey-marc',parse(input){const result=importAguapeyISO(input);if(result.records>10000)throw new Error('El archivo supera 10000 registros.');if(result.skipped)throw new Error('Hay registros sin título. Revisá el archivo para evitar una importación incompleta.');return result;}};
export const JsonBackupProvider={id:'json-backup',parse(text){const data=JSON.parse(text),legacy=parseArchive(text);if(data.version!==4)return legacy;for(const store of STORES){if(!Array.isArray(data[store])||data[store].length>100000)throw new Error('Respaldo incompleto: '+store);if(data[store].some(v=>!v||typeof v.id!=='string'||!v.id)||new Set(data[store].map(v=>v.id)).size!==data[store].length)throw new Error('Identificadores inválidos en '+store);}
 const config=data.settings.find(x=>x.id==='local');if(!config||!Number.isSafeInteger(config.sequence)||config.sequence<1||!config.institutionId||!config.libraryId||!config.collectionId)throw new Error('Configuración de respaldo inválida.');const books=legacy.books,copies=books.flatMap(b=>b.exemplars);if(new Set(copies.map(c=>c.id)).size!==copies.length||new Set(copies.map(c=>c.internalCode)).size!==copies.length||copies.some(c=>!/^AB-\d{6,}$/.test(c.internalCode||'')))throw new Error('Códigos internos inválidos o repetidos.');
 for(const u of data.patrons){if(!u.name||(u.role&&!ROLES[u.role]))throw new Error('Persona inválida en respaldo.');validWindow(u.startsAt,u.expiresAt);}if(!data.patrons.some(u=>isEnabled(u)&&['director','administrador','bibliotecario'].includes(u.role)))throw new Error('El respaldo necesita un perfil de gestión habilitado.');
 for(const g of data.grants){if(!data.patrons.some(u=>u.id===g.userId)||!PERMISSIONS.includes(g.permission))throw new Error('Permiso sin persona o desconocido.');validWindow(g.startsAt,g.expiresAt);}
 const active=new Set();for(const l of data.loans){if(!['loaned','overdue','returned'].includes(l.status)||!l.patron?.id||!Number.isFinite(Date.parse(l.dueAt)))throw new Error('Préstamo inválido.');if(activeLoan(l)){if(active.has(l.exemplarId)||!books.some(b=>b.id===l.bookId&&b.exemplars.some(e=>e.id===l.exemplarId))||!data.patrons.some(u=>u.id===l.patron.id))throw new Error('Préstamo activo duplicado o sin referencia.');active.add(l.exemplarId);}}
 const assigned=new Set();for(const r of data.reservations){if(!['requested','approved','ready','collected','cancelled','expired'].includes(r.status)||!r.patron?.id)throw new Error('Reserva inválida.');if(activeReservation(r)){if(!books.some(b=>b.id===r.bookId)||!data.patrons.some(u=>u.id===r.patron.id))throw new Error('Reserva sin referencia.');if(['approved','ready'].includes(r.status)){if(active.has(r.exemplarId)||assigned.has(r.exemplarId)||!books.some(b=>b.id===r.bookId&&b.exemplars.some(e=>e.id===r.exemplarId)))throw new Error('Ejemplar reservado no válido.');assigned.add(r.exemplarId);}}}
 return {...data,books,photos:legacy.photos};}};
// Marc21ExportProvider is intentionally not implemented until real round-trip files are validated.
