import {parseArchive} from './catalog.js?v=20261009-12';
import {importAguapeyISO} from './marc.js?v=20261009-12';
import {STORES,activeLoan,activeReservation} from './local-domain.js?v=20261009-12';
import {PERMISSIONS,ROLES,PROFILES,isEnabled,validWindow} from './permissions.js?v=20261009-12';
export class ImportProvider{parse(){throw new Error('Implementar parse en el proveedor.');}}
export const AguapeyMarcProvider={id:'aguapey-marc',parse(input){const result=importAguapeyISO(input);if(result.records>10000)throw new Error('El archivo supera 10000 registros.');if(result.skipped)throw new Error('Hay registros sin título. Revisá el archivo para evitar una importación incompleta.');return result;}};
export const JsonBackupProvider={id:'json-backup',parse(text){const data=JSON.parse(text),legacy=parseArchive(text);if(data.version<4)return legacy;if(data.version===4)for(const name of ['people','memberships','invitations','saved','collectionNeeds','recommendations','resourceSharingRequests','libraryLocations','inventorySessions'])data[name]??=[];if(data.version===5)for(const name of ['collectionNeeds','recommendations','resourceSharingRequests','libraryLocations','inventorySessions'])data[name]??=[];for(const store of STORES){if(!Array.isArray(data[store])||data[store].length>100000)throw new Error('Respaldo incompleto: '+store);if(data[store].some(v=>!v||typeof v.id!=='string'||!v.id)||new Set(data[store].map(v=>v.id)).size!==data[store].length)throw new Error('Identificadores inválidos en '+store);}
 const config=data.settings.find(x=>x.id==='local');if(!config||!Number.isSafeInteger(config.sequence)||config.sequence<1||!config.institutionId||!config.libraryId||!config.collectionId)throw new Error('Configuración de respaldo inválida.');const books=legacy.books,copies=books.flatMap(b=>b.exemplars);if(new Set(copies.map(c=>c.id)).size!==copies.length||new Set(copies.map(c=>c.internalCode)).size!==copies.length||copies.some(c=>!/^AB-\d{6,}$/.test(c.internalCode||'')))throw new Error('Códigos internos inválidos o repetidos.');
 for(const u of data.patrons){if(!u.name||(u.role&&!ROLES[u.role]))throw new Error('Persona inválida en respaldo.');validWindow(u.startsAt,u.expiresAt);}if(!data.patrons.some(u=>isEnabled(u)&&(u.mainAdmin||['director','administrador','bibliotecario'].includes(u.role))))throw new Error('El respaldo necesita un perfil de gestión habilitado.');
 for(const g of data.grants){if(!data.patrons.some(u=>u.id===g.userId)||!PERMISSIONS.includes(g.permission))throw new Error('Permiso sin persona o desconocido.');validWindow(g.startsAt,g.expiresAt);}
 for(const need of data.collectionNeeds||[]){if(!need.title||!['detected','reviewing','planned','resolved','dismissed'].includes(need.status))throw new Error('Necesidad de colección inválida.');if(need.resolutionMethod&&!['purchase','donation','existing','digital','interlibrary','exchange','other'].includes(need.resolutionMethod))throw new Error('Método de resolución inválido en respaldo.');if(need.bookId&&!books.some(b=>b.id===need.bookId))need.bookId='';}
 for(const loc of data.libraryLocations||[]){if(!['sector','shelving','shelf'].includes(loc.type)||!loc.name)throw new Error('Ubicación física inválida.');}
 for(const inv of data.inventorySessions||[]){if(!['open','closed'].includes(inv.status)||!inv.scope||!Array.isArray(inv.expectedExemplarIds)||!Array.isArray(inv.findings))throw new Error('Sesión de inventario inválida.');}
 for(const req of data.resourceSharingRequests||[]){if(!['request','offer'].includes(req.direction)||!['draft','prepared','agreed','received','returned','cancelled'].includes(req.status)||!req.title||!req.targetInstitution)throw new Error('Solicitud interbibliotecaria inválida.');if(req.needId&&!data.collectionNeeds.some(n=>n.id===req.needId))req.needId='';if(req.bookId&&!books.some(b=>b.id===req.bookId))req.bookId='';}
 for(const rec of data.recommendations||[]){if(!['active','archived'].includes(rec.status))throw new Error('Recomendación interna inválida.');if(rec.status==='active'&&(!rec.bookId||!books.some(b=>b.id===rec.bookId)))throw new Error('Recomendación activa sin material válido.');if(rec.bookId&&!books.some(b=>b.id===rec.bookId)){rec.linkedMaterialTitle=rec.linkedMaterialTitle||rec.title||'';rec.bookId='';rec.status='archived';}}
 const active=new Set();for(const l of data.loans){if(!['loaned','overdue','returned'].includes(l.status)||!l.patron?.id||!Number.isFinite(Date.parse(l.dueAt)))throw new Error('Préstamo inválido.');if(activeLoan(l)){if(active.has(l.exemplarId)||!books.some(b=>b.id===l.bookId&&b.exemplars.some(e=>e.id===l.exemplarId))||!data.patrons.some(u=>u.id===l.patron.id))throw new Error('Préstamo activo duplicado o sin referencia.');active.add(l.exemplarId);}}
 const assigned=new Set();for(const r of data.reservations){if(!['requested','approved','ready','collected','cancelled','expired'].includes(r.status)||!r.patron?.id)throw new Error('Reserva inválida.');if(activeReservation(r)){if(!books.some(b=>b.id===r.bookId)||!data.patrons.some(u=>u.id===r.patron.id))throw new Error('Reserva sin referencia.');if(['approved','ready'].includes(r.status)){if(active.has(r.exemplarId)||assigned.has(r.exemplarId)||!books.some(b=>b.id===r.bookId&&b.exemplars.some(e=>e.id===r.exemplarId)))throw new Error('Ejemplar reservado no válido.');assigned.add(r.exemplarId);}}}
 if(data.version===5){const iid=config.institutionId;if(data.institutions.length!==1||data.institutions[0].id!==iid||!data.memberships.some(m=>m.personId===data.institutions[0].mainAdminId&&m.status==='active'))throw new Error('Administración principal inválida.');for(const m of data.memberships){if(m.institutionId!==iid||!data.people.some(p=>p.id===m.personId)||!['active','inactive','suspended','pending'].includes(m.status)||(m.accessProfile&&!PROFILES[m.accessProfile]))throw new Error('Vinculación inválida.');validWindow(m.startsAt,m.expiresAt);}if(new Set(data.memberships.map(m=>m.personId)).size!==data.memberships.length)throw new Error('Vinculaciones duplicadas.');for(const name of STORES.filter(n=>!['people','patrons'].includes(n)))if(data[name].some(r=>r.institutionId!==iid))throw new Error('Respaldo con datos de otra institución.');}
 return {...data,books,photos:legacy.photos};}};
// Marc21ExportProvider is intentionally not implemented until real round-trip files are validated.
