// The public site never imports the application or opens its database.
const $=selector=>document.querySelector(selector);
const reduced=matchMedia('(prefers-reduced-motion: reduce)');
document.documentElement.classList.add('js');
const legacy=['inicio','biblioteca','agregar','editar','ficha','configuracion','ejemplares'];
function redirectLegacy(){if(legacy.includes(location.hash.slice(1).split('/')[0]))location.replace('./app.html'+location.hash);}
redirectLegacy();window.addEventListener('hashchange',redirectLegacy);
let savedTheme;try{savedTheme=localStorage.getItem('ab-theme');}catch{}
function setTheme(theme){document.documentElement.dataset.theme=theme;try{localStorage.setItem('ab-theme',theme);}catch{}$('meta[name="theme-color"]').content=theme==='dark'?'#0A112F':'#EBF3FF';$('[data-theme-toggle]').setAttribute('aria-label',theme==='dark'?'Activar tema claro':'Activar tema oscuro');}
setTheme(savedTheme||(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'));
$('[data-theme-toggle]').addEventListener('click',()=>setTheme(document.documentElement.dataset.theme==='dark'?'light':'dark'));

const header=$('.site-header'),mobile=matchMedia('(max-width:1080px)'),mobileToggle=$('#menu-toggle'),backdrop=$('#menu-backdrop');
const triggers=[...document.querySelectorAll('.nav-trigger')],panels=[...document.querySelectorAll('.mega-menu')];
// Menus use hover/focus on a desktop and explicit taps on a phone.
let activeMenu=null,opener=null,previousOverflow='',previousInert=[],closeTimer,closingTimer,restoringFocus=false;
function lockBackground(){if(previousInert.length)return;previousOverflow=document.body.style.overflow;previousInert=[$('main'),$('.site-footer')].map(el=>[el,el.inert]);previousInert.forEach(([el])=>el.inert=true);document.body.style.overflow='hidden';document.body.setAttribute('data-menu-open','');backdrop.hidden=false;}
function closeMenu(restoreFocus=false,animate=true){clearTimeout(closeTimer);clearTimeout(closingTimer);if(!activeMenu)return;const previous=activeMenu;activeMenu=null;triggers.forEach(t=>t.setAttribute('aria-expanded','false'));mobileToggle.setAttribute('aria-expanded','false');$('#site-nav').classList.remove('is-open');if(animate&&!mobile.matches&&!reduced.matches){previous.classList.add('is-closing');closingTimer=setTimeout(()=>{previous.hidden=true;previous.classList.remove('is-closing');},150);}else panels.forEach(p=>{p.hidden=true;p.classList.remove('is-closing');});backdrop.hidden=true;document.body.style.overflow=previousOverflow;document.body.removeAttribute('data-menu-open');for(const [el,value]of previousInert)el.inert=value;previousInert=[];if(restoreFocus&&opener?.getClientRects().length){restoringFocus=true;opener.focus();restoringFocus=false;}}
function showPanel(toggle,{focus=false}={}){clearTimeout(closeTimer);clearTimeout(closingTimer);const panel=document.getElementById(toggle.getAttribute('aria-controls'));panels.forEach(p=>{p.hidden=p!==panel;p.classList.remove('is-closing');});triggers.forEach(t=>t.setAttribute('aria-expanded',String(t===toggle)));opener=mobile.matches?mobileToggle:toggle;activeMenu=mobile.matches?$('#site-nav'):panel;lockBackground();if(focus)panel.querySelector('a')?.focus();}
function openMobile(){clearTimeout(closingTimer);panels.forEach(p=>p.hidden=true);triggers.forEach(t=>t.setAttribute('aria-expanded','false'));activeMenu=$('#site-nav');opener=mobileToggle;lockBackground();activeMenu.classList.add('is-open');mobileToggle.setAttribute('aria-expanded','true');activeMenu.querySelector('button,a')?.focus();}
mobileToggle.addEventListener('click',()=>{if(mobile.matches){if(activeMenu)closeMenu(true,false);else openMobile();}});
for(const toggle of triggers){const panel=document.getElementById(toggle.getAttribute('aria-controls'));toggle.addEventListener('pointerenter',e=>{if(!mobile.matches&&e.pointerType==='mouse')showPanel(toggle);});toggle.addEventListener('focus',()=>{if(!mobile.matches&&!restoringFocus)showPanel(toggle);});toggle.addEventListener('click',()=>{if(mobile.matches&&toggle.getAttribute('aria-expanded')==='true'){toggle.setAttribute('aria-expanded','false');panel.hidden=true;}else showPanel(toggle);});toggle.addEventListener('keydown',e=>{if(e.key==='ArrowDown'){e.preventDefault();showPanel(toggle,{focus:true});}});}
function scheduleClose(){if(!mobile.matches&&activeMenu){clearTimeout(closeTimer);closeTimer=setTimeout(()=>closeMenu(false),230);}}
header.addEventListener('pointerleave',scheduleClose);header.addEventListener('pointerenter',()=>clearTimeout(closeTimer));header.addEventListener('focusout',()=>setTimeout(()=>{if(!mobile.matches&&!header.contains(document.activeElement))closeMenu();},0));
backdrop.addEventListener('click',()=>closeMenu(true));header.addEventListener('click',e=>{if(e.target.closest('a'))closeMenu(false,false);});
document.addEventListener('keydown',e=>{if(!activeMenu)return;if(e.key==='Escape'){e.preventDefault();closeMenu(true,false);}if(e.key==='Tab'&&mobile.matches){const items=[...header.querySelectorAll('a,button')].filter(el=>el.getClientRects().length&&!el.hidden&&!el.disabled);const index=items.indexOf(document.activeElement);e.preventDefault();items[(index+(e.shiftKey?-1:1)+items.length)%items.length]?.focus();}});
function arrangeMenus(){closeMenu(false,false);panels.forEach(p=>{p.hidden=true;p.classList.remove('is-closing');});for(const toggle of triggers){const panel=document.getElementById(toggle.getAttribute('aria-controls'));if(mobile.matches)toggle.parentElement.append(panel);else header.append(panel);}}
mobile.addEventListener('change',arrangeMenus);arrangeMenus();window.addEventListener('hashchange',()=>closeMenu(false,false));
let scrollFrame;function updateHeader(){header.classList.toggle('is-scrolled',scrollY>24);scrollFrame=null;}window.addEventListener('scroll',()=>{if(!scrollFrame)scrollFrame=requestAnimationFrame(updateHeader);},{passive:true});updateHeader();

// Deep links from the footer also open their destination disclosure.
function revealDisclosure(){const id=decodeURIComponent(location.hash.slice(1));const target=document.getElementById(id);if(target?.matches('details'))target.open=true;}
window.addEventListener('hashchange',revealDisclosure);revealDisclosure();
document.addEventListener('click',event=>{const link=event.target.closest('a[href^="#"]');if(!link)return;const target=document.getElementById(link.getAttribute('href').slice(1));if(target?.matches('details'))target.open=true;});

const previewNames={scan:'Reconocimiento y revisión de un material',search:'Búsqueda por temas y contenidos',catalog:'El catálogo de la institución',record:'Ficha y contenidos de un material',holdings:'Ejemplares y ubicaciones',circulation:'Préstamos y reservas',people:'Personas y responsabilidades',mobile:'La plataforma desde el celular'};
const dialog=$('#product-preview-dialog');let previewTrigger;
document.addEventListener('click',event=>{const trigger=event.target.closest('[data-preview]');if(!trigger||!Object.hasOwn(previewNames,trigger.dataset.preview))return;previewTrigger=trigger;const screen=trigger.dataset.preview,theme=document.documentElement.dataset.theme||'light';$('#preview-title').textContent=previewNames[screen];$('#preview-image').src='./assets/product/'+screen+'-'+theme+'.jpg';$('#preview-image').alt=previewNames[screen]+' · Datos de demostración';dialog.showModal();});
$('[data-close-preview]').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',event=>{if(event.target!==dialog)return;const r=dialog.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)dialog.close();});dialog.addEventListener('close',()=>previewTrigger?.focus());

const featureDetails=[...document.querySelectorAll('.feature-list details')];for(const details of featureDetails)details.addEventListener('toggle',()=>{if(!details.open)return;for(const other of featureDetails)if(other!==details)other.open=false;const visual=$('.feature-visual'),screen=details.dataset.screen,title=details.querySelector('.feature-label').textContent.trim();visual.querySelector('[data-preview]').dataset.preview=screen;for(const theme of ['light','dark']){const img=visual.querySelector('.shot-'+theme);img.src='./assets/product/'+screen+'-'+theme+'.jpg';img.alt=title+' · Captura de demostración en tema '+(theme==='dark'?'oscuro':'claro');}$('#feature-caption').textContent=title+' · Captura real con datos de ejemplo';visual.classList.remove('is-changing');requestAnimationFrame(()=>visual.classList.add('is-changing'));});

if('IntersectionObserver'in window){const blocks=[...document.querySelectorAll('[data-reveal]')];if(!reduced.matches)document.documentElement.classList.add('reveal-ready');const observer=new IntersectionObserver(entries=>{for(const entry of entries)if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target);}},{threshold:.08,rootMargin:'0px 0px -25px 0px'});blocks.forEach(el=>observer.observe(el));reduced.addEventListener('change',()=>{if(reduced.matches){document.documentElement.classList.remove('reveal-ready');blocks.forEach(el=>el.classList.add('is-visible'));}});
 const counterObserver=new IntersectionObserver(entries=>{for(const entry of entries){if(!entry.isIntersecting)continue;counterObserver.unobserve(entry.target);const el=entry.target,target=Number(el.dataset.count);if(reduced.matches)continue;const start=performance.now();function tick(now){const progress=reduced.matches?1:Math.min((now-start)/1000,1);el.textContent=String(Math.round(target*(1-Math.pow(1-progress,3))));if(progress<1)requestAnimationFrame(tick);}requestAnimationFrame(tick);}},{threshold:.8});document.querySelectorAll('[data-count]').forEach(el=>counterObserver.observe(el));}
