import {accessCommand,expireAccess} from './access-domain.js?v=20261009-8';
import {requirePermission,isEnabled,userRecord,grantRecord,hasPermission} from './permissions.js?v=20261009-8';
import {normalizeLoanPolicy,policyForPatron,activeLoansForPatron,overdueLoansForPatron,dueDateFromPolicy,reservationExpiryFromPolicy,renewalRequestStatus,renewalDueDate} from './loan-policy.js?v=20261009-8';
import {normalizeLocation,displayLocation} from './domain.js?v=20261009-8';
export const STORES=['books','photos','loans','reservations','patrons','activity','grants','settings','institutions','libraries','collections','works','editions','people','memberships','invitations','saved','collectionNeeds','recommendations'];
export const activeLoan=l=>['loaned','overdue'].includes(l.status)&&!l.returnedAt;
export const activeReservation=r=>['requested','approved','ready'].includes(r.status);
export const dateEnd=value=>/^\d{4}-\d{2}-\d{2}$/.test(value)?new Date(value+'T23:59:59.999').toISOString():new Date(value).toISOString();
export function audit(s,type,actorId,details={}){s.activity.push({id:crypto.randomUUID(),type,actorId,institutionId:s.institutionId||config(s).institutionId,createdAt:new Date().toISOString(),...details});}
export function config(s){let value=s.settings.find(x=>x.id==='local');if(!value){value={id:'local',institutionId:'local-institution',libraryId:'local-library',collectionId:'local-collection',institutionName:'Mi escuela',libraryName:'Biblioteca',sequence:1};s.settings.push(value);}return value;}
export function normalizeHoldings(s){const c=config(s),seen=new Set(),ids=new Set();if(!Number.isSafeInteger(c.sequence)||c.sequence<1)throw new Error('Contador de inventario inválido.');let next=c.sequence;for(const b of s.books)for(const e of b.exemplars||[])if(/^AB-\d+$/.test(e.internalCode||''))next=Math.max(next,Number(e.internalCode.slice(3))+1);
 for(const b of s.books){b.institutionId||=c.institutionId;b.libraryId||=c.libraryId;b.collectionId||=c.collectionId;b.workId||=crypto.randomUUID();b.editionId||=b.id;for(const e of b.exemplars||[]){if(ids.has(e.id))throw new Error('Identificador de ejemplar duplicado.');ids.add(e.id);let code=e.internalCode;if(!/^AB-\d{6,}$/.test(code||'')||seen.has(code))code='AB-'+String(next++).padStart(6,'0');if(!Number.isSafeInteger(next)||next>Number.MAX_SAFE_INTEGER-1)throw new Error('Se agotó el rango de códigos internos.');e.internalCode=code;seen.add(code);e.inventoryCode||=code;e.physicalLocation=normalizeLocation(e.physicalLocation||{});e.status=e.status==='untracked'||!e.status?'available':e.status;e.institutionId=b.institutionId;e.libraryId=b.libraryId;e.collectionId=b.collectionId;e.editionId=b.editionId;}b.copies=(b.exemplars||[]).length;}c.sequence=next;
 s.institutions=[{...s.institutions[0],id:c.institutionId,name:c.institutionName}];s.libraries=[{id:c.libraryId,institutionId:c.institutionId,name:c.libraryName}];
 const collections=new Map([[c.collectionId,{id:c.collectionId,libraryId:c.libraryId,name:'General'}]]),works=new Map(),editions=[];
 for(const b of s.books){works.set(b.workId,{id:b.workId,title:b.title,author:b.author,subjects:b.subjects,contents:b.contents,contentEntries:b.contentEntries,description:b.description,materialType:b.materialType});editions.push({id:b.editionId,workId:b.workId,recordId:b.id,materialType:b.materialType,isbn:b.isbn,issn:b.issn,doi:b.doi,resourceUrl:b.resourceUrl,publisher:b.publisher,year:b.year,pages:b.pages,language:b.language,edition:b.edition,publication:b.publication,publicationDate:b.publicationDate,containerTitle:b.containerTitle,volume:b.volume,issueNumber:b.issueNumber,editionLabel:b.editionLabel,pageRange:b.pageRange,issuingBody:b.issuingBody,documentNumber:b.documentNumber,schoolArea:b.schoolArea,courseLevel:b.courseLevel,digitalFormat:b.digitalFormat,circulationPolicy:b.circulationPolicy});for(const e of b.exemplars){const sector=e.physicalLocation.sector;e.collectionId=sector?c.institutionId+':sector:'+encodeURIComponent(sector):c.collectionId;collections.set(e.collectionId,{id:e.collectionId,libraryId:c.libraryId,name:sector||'General'});}}
 s.collections=[...collections.values()];s.works=[...works.values()];s.editions=editions;
}
export function effectiveState(e,s,at=new Date()){if(['lost','withdrawn'].includes(e.status))return e.status;const loan=s.loans.find(l=>l.exemplarId===e.id&&activeLoan(l));if(loan)return Date.parse(loan.dueAt)<+at?'overdue':'loaned';if(s.reservations.some(r=>r.exemplarId===e.id&&['approved','ready'].includes(r.status)&&(!r.expiresAt||Date.parse(r.expiresAt)>+at)))return 'reserved';if(e.condition==='Deteriorado'||e.status==='damaged')return 'damaged';return 'available';}
export function findCopy(s,id){for(const book of s.books){const copy=book.exemplars?.find(e=>e.id===id||e.internalCode===id);if(copy)return {book,copy};}throw new Error('No encontramos ese ejemplar.');}
export function expireReservations(s,actorId){const at=Date.now();for(const r of s.reservations)if(activeReservation(r)&&r.expiresAt&&Date.parse(r.expiresAt)<=at){r.status='expired';r.updatedAt=new Date().toISOString();audit(s,'reservation.expired',actorId,{reservationId:r.id});}}
export function ensureRemovable(s,ids){if(s.loans.some(l=>ids.includes(l.exemplarId)&&activeLoan(l)))throw new Error('Registrá la devolución antes de eliminar un ejemplar con préstamo activo.');if(s.reservations.some(r=>ids.includes(r.exemplarId)&&activeReservation(r)))throw new Error('Cancelá la reserva asignada antes de eliminar el ejemplar.');}
export function command(s,actorId,type,data={}){
 if(s.memberships?.length){expireAccess(s);if(['copy.add','person.validate','profile.save','user.save','person.save','person.invite','grant.add','grant.revoke','settings.save','institution.transfer','institution.disable','onboarding.library','onboarding.finish','material.topics','material.contents','saved.toggle'].includes(type))return accessCommand(s,actorId,type,data);}
 const permitted=p=>requirePermission(s,actorId,p);const now=new Date().toISOString();expireReservations(s,actorId);
 if(type==='user.save'){permitted('users.manage');const old=s.patrons.find(u=>u.id===data.id);if(!old||old.role!==data.role)permitted('permissions.manage');const user={...userRecord(data,old),updatedAt:now,updatedBy:actorId,enabledBy:old?.active===false&&data.active!==false?actorId:(old?.enabledBy||actorId),roleGrantedBy:old?.role!==data.role?actorId:(old?.roleGrantedBy||actorId)};if(old)s.patrons.splice(s.patrons.indexOf(old),1,user);else s.patrons.push(user);if(!s.patrons.some(u=>isEnabled(u)&&['director','administrador','bibliotecario'].includes(u.role)))throw new Error('Debe quedar al menos un perfil de gestión activo y vigente.');audit(s,!old?'user.created':old.active!==user.active?(user.active?'user.enabled':'user.disabled'):'user.updated',actorId,{userId:user.id,beforeRole:old?.role||'',role:user.role,expiresAt:user.expiresAt});return user;}
 if(type==='grant.add'){permitted('permissions.manage');if(!s.patrons.some(u=>u.id===data.userId))throw new Error('Usuario inexistente.');const g=grantRecord(data,actorId);s.grants.push(g);audit(s,'permission.granted',actorId,{grantId:g.id,userId:g.userId,permission:g.permission});return g;}
 if(type==='grant.revoke'){permitted('permissions.manage');const g=s.grants.find(g=>g.id===data.id);if(!g)throw new Error('Permiso inexistente.');g.active=false;g.revokedBy=actorId;g.revokedAt=now;audit(s,'permission.revoked',actorId,{grantId:g.id,userId:g.userId,permission:g.permission});return g;}
 if(type==='settings.save'){permitted('users.manage');Object.assign(config(s),{institutionName:String(data.institutionName||'Mi escuela').slice(0,80),libraryName:String(data.libraryName||'Biblioteca').slice(0,80)});audit(s,'settings.updated',actorId);return;}
 if(type==='copy.save'){permitted('holdings.edit');const {book,copy}=findCopy(s,data.id);if(!['available','lost','withdrawn','damaged'].includes(data.status))throw new Error('Estado inválido.');if(['lost','withdrawn'].includes(data.status))ensureRemovable(s,[copy.id]);copy.physicalLocation=normalizeLocation(data);copy.location=displayLocation(copy.physicalLocation)||String(data.location||'').slice(0,120);copy.condition=['Bueno','Nuevo','Regular','Deteriorado'].includes(data.condition)?data.condition:'Bueno';copy.status=data.status;copy.inventoryCode=String(data.inventoryCode||copy.inventoryCode||'').slice(0,100);book.updatedAt=now;audit(s,'holding.updated',actorId,{bookId:book.id,exemplarId:copy.id});return copy;}
 if(type==='loan.renew.request'){const actor=permitted('catalog.view'),loan=s.loans.find(l=>l.id===data.id),policy=normalizeLoanPolicy(config(s).policy||{});if(!loan||loan.patron.id!==actor.id)throw new Error('Solo podés pedir una extensión para un préstamo propio.');const book=s.books.find(b=>b.id===loan.bookId),eligibility=renewalRequestStatus(loan,policy,{reservations:s.reservations,book});if(!eligibility.allowed){const reason={pending:'Ya existe una solicitud de extensión pendiente.',overdue:'El préstamo ya está vencido.',reserved:'Otra persona está esperando este material.',material:'Este material no admite renovación.',limit:'Ya usaste la renovación disponible.',disabled:'La institución no habilitó renovaciones.',too-early:'La extensión se puede pedir más cerca de la fecha de devolución.'}[eligibility.reason]||'Este préstamo no admite renovación.';throw new Error(reason);}loan.renewalRequest={status:'pending',requestedAt:now,requestedBy:actorId,previousDueAt:loan.dueAt};audit(s,'loan.renewal.requested',actorId,{loanId:loan.id,bookId:loan.bookId,exemplarId:loan.exemplarId,dueAt:loan.dueAt});return loan;}
 if(type==='loan.renew.approve'||type==='loan.renew.reject'){permitted('circulation.renew.approve');const loan=s.loans.find(l=>l.id===data.id),policy=normalizeLoanPolicy(config(s).policy||{});if(!loan||loan.renewalRequest?.status!=='pending'||!activeLoan(loan))throw new Error('No hay una solicitud de extensión pendiente.');if(type==='loan.renew.reject'){loan.renewalRequest={...loan.renewalRequest,status:'rejected',resolvedAt:now,resolvedBy:actorId};audit(s,'loan.renewal.rejected',actorId,{loanId:loan.id,bookId:loan.bookId,exemplarId:loan.exemplarId});return loan;}const book=s.books.find(b=>b.id===loan.bookId),eligibility=renewalRequestStatus({...loan,renewalRequest:null},policy,{reservations:s.reservations,book});if(!eligibility.allowed)throw new Error('La extensión ya no puede autorizarse porque cambiaron las condiciones del préstamo.');loan.dueAt=renewalDueDate(policy,loan).toISOString();loan.renewals=(loan.renewals||0)+1;loan.renewalRequest={...loan.renewalRequest,status:'approved',resolvedAt:now,resolvedBy:actorId,newDueAt:loan.dueAt};audit(s,'loan.renewal.approved',actorId,{loanId:loan.id,bookId:loan.bookId,exemplarId:loan.exemplarId,dueAt:loan.dueAt});return loan;}
 if(type==='loan.create'){permitted('circulation.loan');const {book,copy}=findCopy(s,data.exemplarId);const patron=s.patrons.find(u=>u.id===data.patronId);if(!isEnabled(patron))throw new Error('Seleccioná una persona activa y con habilitación vigente.');const policy=normalizeLoanPolicy(config(s).policy||{});if(book.circulationPolicy==='room-only')throw new Error('Este material está configurado solo para consulta en sala.');if(patron.accessProfile==='personal'&&!policy.allowStaffLoans)throw new Error('La institución no habilitó préstamos para personal institucional.');const patronPolicy=policyForPatron(policy,patron);if(policy.blockNewLoansIfOverdue&&overdueLoansForPatron(s.loans,patron.id,policy).length)throw new Error('La institución bloquea nuevos préstamos mientras haya devoluciones vencidas.');if(activeLoansForPatron(s.loans,patron.id).length>=patronPolicy.maxLoans)throw new Error('Esta persona alcanzó el máximo de préstamos activos permitido por la institución.');const reservation=data.reservationId?s.reservations.find(r=>r.id===data.reservationId):null;
 if(reservation&&(reservation.status!=='ready'||reservation.exemplarId!==copy.id||reservation.patron.id!==patron.id))throw new Error('La reserva no está lista para este ejemplar y persona.');const state=effectiveState(copy,s);if(state!=='available'&&!(state==='reserved'&&reservation))throw new Error('El ejemplar no está disponible: '+state);const dueAt=data.dueAt?dateEnd(data.dueAt):dueDateFromPolicy(policy,patron,new Date()).toISOString();if(Date.parse(dueAt)<Date.now())throw new Error('La devolución no puede estar en el pasado.');const loan={id:crypto.randomUUID(),bookId:book.id,exemplarId:copy.id,internalCode:copy.internalCode,title:book.title,patron:{id:patron.id,name:patron.name,role:patron.role,course:patron.course||'',accessProfile:patron.accessProfile},loanedAt:now,dueAt,status:'loaned',returnedAt:null,renewals:0,createdBy:actorId};s.loans.push(loan);if(reservation){reservation.status='collected';reservation.updatedAt=now;audit(s,'reservation.collected',actorId,{reservationId:reservation.id,loanId:loan.id});}audit(s,'loan.created',actorId,{loanId:loan.id,bookId:book.id,exemplarId:copy.id,patronId:patron.id,dueAt});return loan;}
 if(type==='loan.return'){permitted('circulation.return');const loan=s.loans.find(l=>l.id===data.id);if(!loan||!activeLoan(loan))throw new Error('Este préstamo no está activo.');const {copy}=findCopy(s,loan.exemplarId);if(!['available','damaged','lost','withdrawn'].includes(data.status||'available'))throw new Error('Estado de devolución inválido.');loan.returnedAt=now;loan.returnedBy=actorId;loan.status='returned';copy.status=data.status||'available';if(copy.status==='damaged')copy.condition='Deteriorado';audit(s,'loan.returned',actorId,{loanId:loan.id,bookId:loan.bookId,exemplarId:copy.id,condition:copy.condition});return loan;}
 if(type==='collection.need.create'){permitted('collection.needs.manage');const title=String(data.title||data.query||'').trim().slice(0,240);if(!title)throw new Error('Ingresá la necesidad o búsqueda que querés registrar.');const normalized=title.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\s+/g,' ').trim();const existing=s.collectionNeeds.find(n=>n.status!=='dismissed'&&n.normalized===normalized);if(existing){existing.demandCount=Math.max(existing.demandCount||1,Number(data.demandCount)||1);existing.updatedAt=now;existing.updatedBy=actorId;if(data.note)existing.note=String(data.note).trim().slice(0,2000);audit(s,'collection.need.updated',actorId,{needId:existing.id,title:existing.title,status:existing.status});return existing;}const need={id:crypto.randomUUID(),title,normalized,source:data.source==='search'?'search':'manual',sourceQuery:String(data.query||'').trim().slice(0,300),demandCount:Math.max(1,Math.min(9999,Number(data.demandCount)||1)),priority:['low','normal','high'].includes(data.priority)?data.priority:'normal',status:'detected',note:String(data.note||'').trim().slice(0,2000),createdAt:now,createdBy:actorId,updatedAt:now,updatedBy:actorId};s.collectionNeeds.push(need);audit(s,'collection.need.created',actorId,{needId:need.id,title:need.title,source:need.source,demandCount:need.demandCount});return need;}
 if(type==='collection.need.update'){permitted('collection.needs.manage');const need=s.collectionNeeds.find(n=>n.id===data.id);if(!need)throw new Error('Necesidad inexistente.');if(data.status&&!['detected','reviewing','planned','resolved','dismissed'].includes(data.status))throw new Error('Estado de necesidad inválido.');if(data.priority&&!['low','normal','high'].includes(data.priority))throw new Error('Prioridad inválida.');if(data.status)need.status=data.status;if(data.priority)need.priority=data.priority;if(data.note!==undefined)need.note=String(data.note||'').trim().slice(0,2000);if(data.resolution!==undefined)need.resolution=String(data.resolution||'').trim().slice(0,2000);if(data.bookId!==undefined){if(data.bookId&&!s.books.some(b=>b.id===data.bookId))throw new Error('Material vinculado inexistente.');need.bookId=data.bookId;}need.updatedAt=now;need.updatedBy=actorId;if(need.status==='resolved')need.resolvedAt=now;audit(s,'collection.need.updated',actorId,{needId:need.id,title:need.title,status:need.status,priority:need.priority,bookId:need.bookId||''});return need;}
 if(type==='recommendation.save'){permitted('recommendations.manage');const book=s.books.find(b=>b.id===data.bookId);if(!book)throw new Error('Seleccioná un material existente.');const old=s.recommendations.find(r=>r.id===data.id)||s.recommendations.find(r=>!data.id&&r.bookId===book.id&&r.status==='active');const rec={...old,id:old?.id||crypto.randomUUID(),bookId:book.id,title:book.title,audience:String(data.audience||old?.audience||'').trim().slice(0,240),reason:String(data.reason||old?.reason||'').trim().slice(0,1200),status:data.status==='archived'?'archived':'active',createdAt:old?.createdAt||now,createdBy:old?.createdBy||actorId,updatedAt:now,updatedBy:actorId};if(old)s.recommendations.splice(s.recommendations.indexOf(old),1,rec);else s.recommendations.push(rec);audit(s,old?'recommendation.updated':'recommendation.created',actorId,{recommendationId:rec.id,bookId:book.id,title:book.title,status:rec.status});return rec;}
 if(type==='recommendation.archive'){permitted('recommendations.manage');const rec=s.recommendations.find(r=>r.id===data.id);if(!rec)throw new Error('Recomendación inexistente.');rec.status='archived';rec.updatedAt=now;rec.updatedBy=actorId;audit(s,'recommendation.archived',actorId,{recommendationId:rec.id,bookId:rec.bookId,title:rec.title});return rec;}
 if(type==='search.record'){const actor=permitted('catalog.view');const q=String(data.query||'').trim().slice(0,300);if(!q)return;const count=Math.max(0,Math.min(100000,Number(data.results)||0));audit(s,count?'search.performed':'search.no_results',actorId,{query:q,resultCount:count,userId:actor.id});return;}
 if(type==='reservation.create'){const actor=permitted('reservations.create');const patron=s.patrons.find(u=>u.id===data.patronId);if(!isEnabled(patron))throw new Error('Seleccioná una persona habilitada.');if(patron.id!==actor.id&&!hasPermission(actor,'reservations.manage',s.grants))throw new Error('Solo podés reservar para tu perfil.');const book=s.books.find(b=>b.id===data.bookId);if(!book)throw new Error('Material inexistente.');if(config(s).policy?.allowReservations===false&&!hasPermission(actor,'reservations.manage',s.grants))throw new Error('Las reservas no están habilitadas por la institución.');if(s.reservations.some(r=>r.bookId===book.id&&r.patron.id===patron.id&&activeReservation(r)))throw new Error('Esta persona ya tiene una reserva pendiente del material.');const r={id:crypto.randomUUID(),bookId:book.id,title:book.title,patron:{id:patron.id,name:patron.name,role:patron.role,course:patron.course},status:'requested',exemplarId:null,requestedAt:now,updatedAt:now,createdBy:actorId};s.reservations.push(r);audit(s,'reservation.requested',actorId,{reservationId:r.id,bookId:book.id,patronId:patron.id});return r;}
 if(type==='reservation.transition'){permitted('reservations.manage');const r=s.reservations.find(r=>r.id===data.id);const allowed={requested:['approved','cancelled','expired'],approved:['ready','cancelled','expired'],ready:['cancelled','expired']};if(!r||!allowed[r.status]?.includes(data.status))throw new Error('Transición de reserva inválida. Retirar requiere confirmar un préstamo.');if(data.status==='approved'||data.status==='ready'){const {book,copy}=findCopy(s,data.exemplarId||r.exemplarId);if(book.id!==r.bookId)throw new Error('El ejemplar pertenece a otra edición.');if(copy.id!==r.exemplarId&&effectiveState(copy,s)!=='available')throw new Error('El ejemplar ya no está disponible.');r.exemplarId=copy.id;if(data.expiresAt){r.expiresAt=dateEnd(data.expiresAt);if(Date.parse(r.expiresAt)<=Date.now())throw new Error('La reserva debe vencer en el futuro.');}else if(data.status==='ready'){r.expiresAt=reservationExpiryFromPolicy(config(s).policy||{},new Date()).toISOString();}}r.status=data.status;r.updatedAt=now;audit(s,'reservation.'+data.status,actorId,{reservationId:r.id,bookId:r.bookId,exemplarId:r.exemplarId});return r;}
 throw new Error('Operación desconocida.');
}
