import {updateInstitutionSelector} from './access-ui.js?v=20261009-8';
import {readState,execute,getActorId,setActorId,expireDueReservations} from './storage.js?v=20261009-8';
import {ROLES,PROFILES,LABELS,PERMISSIONS,hasPermission,isEnabled} from './permissions.js?v=20261009-8';
import {effectiveState,activeLoan,activeReservation,findCopy,config} from './local-domain.js?v=20261009-8';
import {drawLabel,internalDetector,internalFromPhoto} from './labels.js?v=20261009-8';
import {scanISBN} from './scanner.js?v=20261009-8';
import {normalizeLoanPolicy,renewalRequestStatus} from './loan-policy.js?v=20261009-8';
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const STATE_NAMES={available:'Disponible',reserved:'Reservado',loaned:'Prestado',overdue:'Vencido',lost:'Extraviado',damaged:'Deteriorado',withdrawn:'Dado de baja',requested:'Solicitada',approved:'Aprobada',ready:'Lista para retirar',collected:'Retirada',cancelled:'Cancelada',expired:'Vencida'};
let session,refresh,scanner;
const options=(entries,selected='')=>entries.map(([id,name])=>`<option value="${esc(id)}" ${id===selected?'selected':''}>${esc(name)}</option>`).join('');
const field=(title,name,value='',type='text',extra='')=>`<label>${title}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;
const inputDate=v=>{if(!v)return '';const d=new Date(v);return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');};
const EVENT_NAMES={'search.performed':'realizó una búsqueda','search.no_results':'buscó sin encontrar resultados','loan.renewal.requested':'solicitó una extensión','loan.renewal.approved':'autorizó una extensión','loan.renewal.rejected':'rechazó una extensión','permission.granted':'habilitó un permiso','permission.revoked':'revocó un permiso','permission.expired':'registró el vencimiento de un permiso','membership.created':'incorporó una persona','membership.updated':'actualizó una vinculación','membership.validated':'validó una persona','membership.expired':'finalizó una vinculación','membership.suspension.ended':'finalizó una suspensión','invitation.pending':'preparó una invitación local pendiente','profile.updated':'actualizó un perfil de acceso','institution.created':'creó el espacio institucional','institution.admin.transferred':'transfirió la administración principal','institution.disabled':'desactivó la institución'};
const date=v=>v?new Date(v).toLocaleDateString('es-AR'):'Sin vencimiento';
const form=(id,body,button='Guardar')=>`<form id="local-${id}" class="local-form">${body}<p class="error" role="alert"></p><button class="button primary">${button}</button></form>`;
const panel=(title,body)=>`<section class="panel settings-panel local-panel"><h2>${title}</h2>${body}</section>`;
const link=(href,text)=>`<a class="button secondary" href="#${href}">${text}</a>`;
export const can=p=>hasPermission(session?.patrons.find(u=>u.id===getActorId()),p,session?.grants||[]);
export async function refreshSession(){await expireDueReservations();session=await readState();updateInstitutionSelector(session);const select=$('#local-actor');if(select){select.innerHTML=options(session.patrons.map(u=>[u.id,u.name+' · '+(u.cargo||ROLES[u.role]||'Sin cargo')+' · '+(PROFILES[u.accessProfile]||'Sin acceso')+(isEnabled(u)?'':' (sin habilitación)')]),getActorId());}return session;}
export function accessForRoute(route){const rules={agregar:'catalog.create',editar:route==='editar/nuevo'?'catalog.create':'catalog.edit',usuarios:'users.manage',permisos:'permissions.manage',actividad:'reports.view',organizacion:'library.configure',etiquetas:'inventory.manage',interoperabilidad:'catalog.create',ejemplar:'catalog.view'};if(route.startsWith('registro'))return true;if(route.startsWith('usuarios'))return can('users.manage')||can('people.invite')||can('people.validate')||can('profiles.manage');if(route.startsWith('organizacion'))return can('institution.edit')||can('library.configure')||can('policy.configure');if(route.startsWith('coleccion'))return can('collection.needs.manage')||can('recommendations.manage');if(route.startsWith('inventario'))return can('inventory.manage')||can('holdings.create')||can('holdings.edit');if(route.startsWith('actividad'))return can('reports.view')||can('institution.stats');if(route.startsWith('permisos'))return can('permissions.manage')||can('permissions.revoke');return can(rules[route.split('/')[0]]||'catalog.view');}
export const holdingState=copy=>STATE_NAMES[effectiveState(copy,session||{loans:[],reservations:[]})];
export function applyAccess(){if(!session)return;document.querySelectorAll('.copy-editor,[data-photo],#local-copy').forEach(el=>el.hidden=!can('holdings.edit'));for(const el of document.querySelectorAll('a[href^="#"]')){const route=el.getAttribute('href').slice(1);if(el.closest('.wordmark'))continue;el.hidden=!accessForRoute(route);}for(const el of document.querySelectorAll('[data-action=manual],[data-action=clear-catalog],[data-delete],[data-delete-copy],[data-delete-photo],[data-action=export],[data-action=import],[data-action=photo-camera],[data-action=photo-file]')){const permission=el.dataset.delete?'catalog.delete':el.dataset.deleteCopy||el.dataset.deletePhoto?'holdings.edit':el.dataset.action==='manual'?'catalog.create':el.dataset.action==='clear-catalog'?'catalog.clear':el.dataset.action==='export'?'sensitive.export':el.dataset.action==='import'?'catalog.create':'holdings.edit';el.hidden=!can(permission);}for(const group of document.querySelectorAll('.nav-group'))group.hidden=![...group.querySelectorAll('a')].some(a=>!a.hidden);for(const zone of document.querySelectorAll('#main .danger-zone'))zone.hidden=![...zone.querySelectorAll('button')].some(b=>!b.hidden);}
export function initLocalUI(onRefresh){refresh=onRefresh;$('#local-actor').addEventListener('change',async event=>{setActorId(event.target.value);await refreshSession();await refresh(true);});new MutationObserver(applyAccess).observe($('#main'),{childList:true,subtree:true});document.addEventListener('submit',localSubmit);document.addEventListener('click',localClick);document.addEventListener('change',async event=>{if(event.target.id==='internal-photo'&&event.target.files[0]){try{const value=await internalFromPhoto(event.target.files[0]);openCode(value);}catch(e){$('#local-feedback').textContent=e.message;}event.target.value='';}});setInterval(async()=>{if(!document.hidden){await refreshSession();applyAccess();}},30000);window.addEventListener('hashchange',stopInternal);window.addEventListener('pagehide',stopInternal);document.addEventListener('visibilitychange',()=>{if(document.hidden)stopInternal();});}
function stopInternal(){scanner?.abort();scanner=null;}
function openCode(code){findCopy(session,code.trim().toUpperCase());location.hash='#ejemplar/'+encodeURIComponent(code.trim().toUpperCase());}
export async function renderLocal(route){const [base,id]=route.split('/');if(!['usuarios','permisos','circulacion','reservas','etiquetas','actividad','organizacion','ejemplar'].includes(base))return false;await refreshSession();if(location.hash.slice(1)!==route)return true;const actor=session.patrons.find(u=>u.id===getActorId());let html='';const people=session.patrons.filter(u=>isEnabled(u)).map(u=>[u.id,u.name+' · '+(u.course||ROLES[u.role]||'')]);const personSelect=(all=false,name='patronId')=>`<label>Persona<select name="${name}" required><option value="">Seleccionar persona…</option>${options(all||can('reservations.manage')?people:people.filter(([id])=>id===actor.id),actor.id)}</select></label>`;
 if(base==='usuarios'){const user=session.patrons.find(u=>u.id===id)||{};html=panel('Usuarios locales',`<p>Perfiles de prueba de este navegador. Cambiar de perfil no requiere contraseña: no es autenticación real.</p>${session.patrons.map(u=>`<article class="holding-row"><div><strong>${esc(u.name)}</strong><p>${esc(ROLES[u.role]||'Sin rol')} · ${isEnabled(u)?'Habilitado':'Sin habilitación vigente'} · ${esc(u.course)} · ${date(u.expiresAt)}</p><small>Habilitado por: ${esc(session.patrons.find(a=>a.id===u.enabledBy)?.name||'Configuración inicial')}</small></div>${link('usuarios/'+u.id,'Editar usuario')}${can('permissions.manage')?link('permisos/'+u.id,'Permisos'):''}</article>`).join('')}${link('usuarios','Nueva persona')}`)+panel(user.id?'Editar persona':'Nueva persona',form('user',`<input type="hidden" name="id" value="${esc(user.id||'')}">${field('Nombre','name',user.name,'text','required maxlength="160"')}<label>Rol base<select name="role">${options([['','Sin rol (revocado)'],...Object.entries(ROLES)],user.role??'docente')}</select></label>${field('Curso / referencia','course',user.course)}<label>Habilitación<select name="active">${options([['true','Activa'],['false','Inactiva']],String(user.active!==false))}</select></label>${field('Inicio de habilitación','startsAt',inputDate(user.startsAt),'date')}${field('Vence al finalizar el día','expiresAt',inputDate(user.expiresAt),'date')}`));}
 if(base==='permisos'){const user=session.patrons.find(u=>u.id===id)||session.patrons[0];html=panel('Permisos adicionales',`<p>Se suman al rol base, sin convertir a la persona en bibliotecaria. Deshabilitarla o vencer su habilitación invalida también estos permisos.</p>`+form('grant',`<label>Persona<select name="userId">${options(session.patrons.map(u=>[u.id,u.name]),user.id)}</select></label><label>Permiso<select name="permission">${options(PERMISSIONS.map(p=>[p,p]))}</select></label>${field('Inicio','startsAt','','date')}${field('Vencimiento (fin del día)','expiresAt','','date')}${field('Motivo / nota','note','','text','maxlength="1000"')}`,'Otorgar permiso'))+panel('Historial de habilitaciones',session.grants.map(g=>`<article class="holding-row"><div><strong>${esc(session.patrons.find(u=>u.id===g.userId)?.name)} · ${esc(g.permission)}</strong><p>${g.active?'Otorgado':'Revocado'} · Desde ${date(g.startsAt)} · Vence ${date(g.expiresAt)} · Por ${esc(session.patrons.find(u=>u.id===g.grantedBy)?.name||g.grantedBy)}</p><p>${esc(g.note)}</p></div>${g.active?`<button class="button danger" data-local-command="grant.revoke" data-id="${esc(g.id)}">Revocar permiso</button>`:''}</article>`).join('')||'<p>No hay permisos adicionales.</p>');}
 if(base==='circulacion'||base==='reservas'){
 const policy=normalizeLoanPolicy(config(session).policy||{});
 const active=session.loans.filter(activeLoan).filter(l=>!id||l.exemplarId===id).filter(l=>can('circulation.return')||l.patron.id===actor.id||can('circulation.renew.approve'));
 const copies=session.books.flatMap(b=>b.circulationPolicy==='room-only'?[]:b.exemplars.filter(e=>effectiveState(e,session)==='available').map(e=>[e.id,e.internalCode+' · '+b.title]));
 html=panel('Buscar o escanear ejemplar',form('find',`${field('Código interno (también admite lector USB)','code','','text','required placeholder="AB-000001"')}`,'Abrir ejemplar')+`<div class="button-row"><button class="button secondary" data-local-scan>Usar cámara</button><label class="button secondary">Leer foto<input id="internal-photo" type="file" accept="image/*" capture="environment" hidden></label></div><video id="internal-video" hidden playsinline muted></video><button class="button secondary" data-local-stop hidden>Cerrar cámara</button><p id="local-feedback" role="status"></p>`);
 if(can('circulation.loan'))html+=panel('Nuevo préstamo',form('loan',`<label>Ejemplar disponible<select name="exemplarId" required><option value="">Seleccionar…</option>${options(copies,id)}</select></label>${personSelect(true)}${field('Devolver hasta (opcional)','dueAt','','date')}<small>Si lo dejás vacío, se aplica automáticamente la política de préstamo de la institución.</small>`,'Confirmar préstamo'));
 html+=panel(can('circulation.return')||can('circulation.renew.approve')?'Préstamos activos':'Mis préstamos',active.map(l=>{
   const book=session.books.find(b=>b.id===l.bookId);
   const own=l.patron.id===actor.id;
   const renewal=renewalRequestStatus(l,policy,{reservations:session.reservations,book});
   const pending=l.renewalRequest?.status==='pending';
   let actions='';
   if(can('circulation.return'))actions+=form('return',`<input type="hidden" name="id" value="${l.id}"><label>Al devolver<select name="status">${options(['available','damaged','lost','withdrawn'].map(s=>[s,STATE_NAMES[s]]))}</select></label>`,'Registrar devolución');
   if(own&&!can('circulation.return')){
     if(pending)actions+='<p class="notice">Extensión solicitada · pendiente de autorización.</p>';
     else if(renewal.allowed)actions+=`<button class="button secondary" data-local-command="loan.renew.request" data-id="${l.id}">Solicitar extensión</button>`;
     else if(l.renewalRequest?.status==='approved')actions+=`<p class="muted">Extensión aprobada · nueva devolución ${date(l.dueAt)}.</p>`;
   }
   return `<article class="holding-row"><div><strong>${esc(l.title||book?.title)} · ${esc(l.internalCode)}</strong><p>${esc(l.patron.name)} · ${Date.parse(l.dueAt)<Date.now()?'Vencido':'Prestado'} · Devolver ${date(l.dueAt)}</p>${book?.circulationPolicy==='non-renewable'?'<small>Este material no admite renovación.</small>':''}</div><div class="local-actions">${actions}</div></article>`;
 }).join('')||'<p>No hay préstamos activos.</p>');
 if(can('circulation.renew.approve')){
   const requests=session.loans.filter(l=>activeLoan(l)&&l.renewalRequest?.status==='pending');
   html+=panel('Solicitudes de extensión',requests.map(l=>`<article class="holding-row"><div><strong>${esc(l.title)} · ${esc(l.internalCode)}</strong><p>${esc(l.patron.name)} solicita extender el préstamo. Vence ${date(l.dueAt)}.</p><small>Si se autoriza, se suman ${policy.renewalExtensionDays} días.</small></div><div class="button-row"><button class="button primary" data-local-command="loan.renew.approve" data-id="${l.id}">Autorizar extensión</button><button class="button secondary" data-local-command="loan.renew.reject" data-id="${l.id}">Rechazar</button></div></article>`).join('')||'<p>No hay solicitudes pendientes.</p>');
 }
 if(can('reservations.create'))html+=panel('Nueva reserva',form('reserve',`<label>Material<select name="bookId" required><option value="">Seleccionar…</option>${options(session.books.map(b=>[b.id,b.title]),base==='reservas'?id:'')}</select></label>${personSelect()}`,'Solicitar reserva'));
 html+=panel('Reservas',session.reservations.filter(r=>can('reservations.manage')||r.patron.id===actor.id).map(r=>{let actions='';if(can('reservations.manage')&&activeReservation(r)){const b=session.books.find(b=>b.id===r.bookId);if(r.status==='requested')actions+=form('reservation',`<input type="hidden" name="id" value="${r.id}"><input type="hidden" name="status" value="approved"><label>Asignar ejemplar<select name="exemplarId" required><option value="">Seleccionar…</option>${options((b?.exemplars||[]).filter(e=>effectiveState(e,session)==='available').map(e=>[e.id,e.internalCode]))}</select></label>${field('Vencimiento del retiro','expiresAt','','date')}`,'Aprobar y asignar');if(r.status==='approved')actions+=`<button class="button secondary" data-local-command="reservation.transition" data-id="${r.id}" data-status="ready">Lista para retirar</button>`;if(r.status==='ready')actions+=form('loan',`<input type="hidden" name="reservationId" value="${r.id}"><input type="hidden" name="exemplarId" value="${r.exemplarId}"><input type="hidden" name="patronId" value="${r.patron.id}">${field('Devolver hasta (opcional)','dueAt','','date')}<small>Si lo dejás vacío, se aplica automáticamente la política de la institución.</small>`,'Retirar y prestar');actions+=`<button class="button secondary" data-local-command="reservation.transition" data-id="${r.id}" data-status="cancelled">Cancelar reserva</button><button class="button secondary" data-local-command="reservation.transition" data-id="${r.id}" data-status="expired">Marcar vencida</button>`;}return `<article class="holding-row"><div><strong>${esc(r.title||session.books.find(b=>b.id===r.bookId)?.title)}</strong><p>${esc(r.patron.name)} · ${STATE_NAMES[r.status]} · Vence ${date(r.expiresAt)}</p></div><div class="local-actions">${actions}</div></article>`;}).join('')||'<p>No hay reservas.</p>');
} if(base==='ejemplar'){const {book,copy}=findCopy(session,decodeURIComponent(id));const l=copy.physicalLocation||{},history=session.activity.filter(a=>a.exemplarId===copy.id).slice().reverse().slice(0,50);html=panel(esc(copy.internalCode),`<p>${esc(book.title)} · ${STATE_NAMES[effectiveState(copy,session)]}</p><p><small>Circulación: ${esc(({standard:'Préstamo normal','non-renewable':'Préstamo sin renovación','room-only':'Solo consulta en sala'})[book.circulationPolicy||'standard'])}</small></p><div class="button-row">${link('ficha/'+book.id+'/'+copy.id,'Ver ficha bibliográfica')}${link('etiquetas/'+copy.id,'Etiqueta QR y barras')}${link('circulacion/'+copy.id,'Préstamo / devolución')}</div>`+form('copy',`<input type="hidden" name="id" value="${copy.id}">${field('Inventario de origen','inventoryCode',copy.inventoryCode)}${field('Sector','sector',l.sector)}${field('Estantería','shelving',l.shelving)}${field('Estante','shelf',l.shelf)}${field('Ubicación anterior / texto libre','location',copy.location)}<label>Estado físico<select name="condition">${options(['Bueno','Nuevo','Regular','Deteriorado'].map(s=>[s,s]),copy.condition)}</select></label><label>Situación del ejemplar<select name="status">${options(['available','damaged','lost','withdrawn'].map(s=>[s,STATE_NAMES[s]]),['lost','withdrawn','damaged'].includes(copy.status)?copy.status:'available')}</select></label>`))+panel('Historial del ejemplar',history.length?history.map(a=>`<article class="holding-row"><div><strong>${esc(EVENT_NAMES[a.type]||a.type)}</strong><p>${new Date(a.createdAt).toLocaleString('es-AR')} · ${esc(session.patrons.find(u=>u.id===a.actorId)?.name||a.actorId||'Sistema')}</p><small>${esc([a.dueAt,a.condition,a.note].filter(Boolean).join(' · '))}</small></div></article>`).join(''):'<p>Todavía no hay movimientos registrados para este ejemplar.</p>');} if(base==='etiquetas'){const list=session.books.flatMap(b=>b.exemplars.map(e=>({b,e}))).filter(({e})=>!id||e.id===id);html=panel('Etiquetas locales',`<p>El QR y las barras codifican el código AB del ejemplar, nunca el ISBN. Imprimí al 100% y comprobá una etiqueta antes de imprimir el lote.</p><button class="button primary" data-local-print>Imprimir etiquetas</button>`)+`<div class="print-labels">${list.map(({b,e})=>`<article class="print-label" data-code="${e.internalCode}"><strong>${esc(config(session).institutionName)}</strong><span>${esc(b.title.slice(0,70))}</span><div class="label-qr"></div><svg class="label-bars"></svg><b>${e.internalCode}</b></article>`).join('')}</div>`;}
 if(base==='actividad')html=panel('Historial local',`<p>Eventos conservados para estadísticas futuras. No es un registro de seguridad protegido contra cambios desde el dispositivo.</p>${session.activity.slice().reverse().slice(0,300).map(a=>`<article class="holding-row"><div><strong>${esc(EVENT_NAMES[a.type]||a.type)}</strong><p>${new Date(a.createdAt).toLocaleString('es-AR')} · ${esc(session.patrons.find(u=>u.id===a.actorId)?.name||a.actorId||'Migración')}</p><small>${esc([a.title,a.query?('Búsqueda: '+a.query):'',Number.isFinite(a.resultCount)?('Resultados: '+a.resultCount):'',a.internalCode,session.patrons.find(p=>p.id===a.userId)?.name||a.userId,LABELS[a.permission]||a.permission,a.startsAt?'Desde '+new Date(a.startsAt).toLocaleString('es-AR'):'',a.expiresAt?'Hasta '+new Date(a.expiresAt).toLocaleString('es-AR'):'',a.note,a.exemplarId].filter(Boolean).join(' · '))}</small></div></article>`).join('')}`);
 if(base==='organizacion'){const c=config(session);html=panel('Institución y biblioteca',form('settings',`${field('Nombre corto de la institución','institutionName',c.institutionName,'text','required maxlength="80"')}${field('Nombre de la biblioteca','libraryName',c.libraryName,'text','required maxlength="80"')}`)+`<p>Ámbito local: institución → biblioteca → colección/sector. Los sectores se completan al editar cada ejemplar.</p>`);}
 $('#main').innerHTML=`<div class="page-heading"><h1>${({usuarios:'Personas',permisos:'Permisos temporales',circulacion:'Circulación',reservas:'Reservas',etiquetas:'Etiquetas',actividad:'Auditoría',organizacion:'Institución',ejemplar:'Ejemplar físico'})[base]}</h1></div><p id="local-error" class="error" role="alert"></p>`+html;
 if(base==='etiquetas')try{await Promise.all([...document.querySelectorAll('.print-label')].map(el=>drawLabel(el,el.dataset.code)));}catch(error){$('#local-error').textContent=error.message;}
 applyAccess();return true;
}
async function localSubmit(event){const f=event.target;if(!(f.getAttribute('id')||'').startsWith('local-'))return;event.preventDefault();const startedAtRoute=location.hash;const error=f.querySelector('.error'),submit=f.querySelector('button');error.textContent='';submit.disabled=true;try{const d=Object.fromEntries(new FormData(f)),kind=f.getAttribute('id').slice(6);if(kind==='find'){openCode(d.code);return;}if(kind==='user'){d.active=d.active==='true';if(d.startsAt)d.startsAt=new Date(d.startsAt+'T00:00:00').toISOString();if(d.expiresAt)d.expiresAt=new Date(d.expiresAt+'T23:59:59.999').toISOString();}if(kind==='grant'){if(d.startsAt)d.startsAt=new Date(d.startsAt+'T00:00:00').toISOString();if(d.expiresAt)d.expiresAt=new Date(d.expiresAt+'T23:59:59.999').toISOString();}await execute(({user:'user.save',grant:'grant.add',copy:'copy.save',loan:'loan.create',return:'loan.return',reserve:'reservation.create',reservation:'reservation.transition',settings:'settings.save'})[kind],d);await refreshSession();if(location.hash!==startedAtRoute)return;await refresh();$('#local-error')?.append(document.createTextNode('Operación guardada.'));}catch(e){error.textContent=e.message;}finally{submit.disabled=false;}}
async function localClick(event){const b=event.target.closest('button');if(!b)return;try{if(b.dataset.localCommand){b.disabled=true;await execute(b.dataset.localCommand,{id:b.dataset.id,status:b.dataset.status});await refreshSession();await refresh();}if(b.hasAttribute('data-local-print'))window.print();if(b.hasAttribute('data-local-stop')){stopInternal();$('#internal-video').hidden=true;b.hidden=true;}if(b.hasAttribute('data-local-scan')){stopInternal();scanner=new AbortController();const video=$('#internal-video');video.hidden=false;$('[data-local-stop]').hidden=false;await scanISBN(video,{signal:scanner.signal,detectorFactory:internalDetector,accept:v=>/^AB-\d{6,}$/.test(v),onISBN:code=>{try{openCode(code);}catch(e){$('#local-feedback').textContent=e.message;}},onError:e=>$('#local-feedback').textContent=e.message});}}catch(e){($('#local-error')||$('#local-feedback')).textContent=e.message;}finally{b.disabled=false;}}
