export const PROFILES={biblioteca:'Responsable de Biblioteca',autoridad:'Autoridad Institucional',docente:'Docente',personal:'Personal Institucional',lector:'Estudiante / Lector'};
export const PROFILE_LEVELS=Object.freeze({lector:10,personal:20,docente:30,biblioteca:60,autoridad:80});
export const CARGOS=['Director/a','Vicedirector/a','Rector/a','Vicerrector/a','Regente','Secretario/a','Bibliotecario/a','Docente','Preceptor/a','Estudiante','Otro'];
export const LABELS={'catalog.view':'Buscar materiales','catalog.create':'Incorporar materiales','catalog.edit':'Editar materiales','catalog.delete':'Eliminar un material','holdings.create':'Agregar ejemplares','holdings.edit':'Editar ejemplares','contents.manage':'Gestionar contenidos','topics.manage':'Gestionar temas y palabras clave','circulation.loan':'Gestionar préstamos','circulation.return':'Registrar devoluciones','circulation.renew.approve':'Autorizar extensiones de préstamo','reservations.create':'Solicitar reservas','reservations.manage':'Gestionar reservas','inventory.manage':'Realizar inventario','people.invite':'Invitar personas','people.validate':'Validar personas','users.manage':'Editar personas','profiles.manage':'Administrar perfiles de acceso','permissions.manage':'Otorgar permisos','permissions.revoke':'Revocar permisos','institution.edit':'Editar datos institucionales','library.configure':'Configurar biblioteca','policy.configure':'Configurar políticas de préstamo','reports.view':'Ver estadísticas de biblioteca','institution.stats':'Ver estadísticas institucionales','collection.needs.manage':'Gestionar necesidades de colección','recommendations.manage':'Gestionar recomendaciones internas','sensitive.export':'Exportar respaldo completo','catalog.clear':'Vaciar catálogo','institution.transfer':'Transferir administración principal','institution.disable':'Desactivar institución'};
export const PERMISSIONS=Object.freeze(Object.keys(LABELS));
export const RESTRICTED=['sensitive.export','catalog.clear','institution.transfer','institution.disable'];
export const LIBRARY=['catalog.view','catalog.create','catalog.edit','catalog.delete','holdings.create','holdings.edit','contents.manage','topics.manage','circulation.loan','circulation.return','circulation.renew.approve','reservations.create','reservations.manage','inventory.manage','reports.view','collection.needs.manage','recommendations.manage','people.invite','people.validate','users.manage','permissions.manage','permissions.revoke','library.configure','policy.configure'];
const basic=['catalog.view','reservations.create'];
export const PROFILE_PERMISSIONS={biblioteca:LIBRARY,autoridad:['catalog.view','people.invite','people.validate','users.manage','profiles.manage','permissions.manage','permissions.revoke','institution.edit','library.configure','policy.configure','reports.view','institution.stats','circulation.renew.approve','collection.needs.manage','recommendations.manage'],docente:basic,personal:['catalog.view'],lector:basic};
export const ROLES={director:'Director/a',administrador:'Administrador/a institucional',bibliotecario:'Bibliotecario/a',docente:'Docente',alumno:'Alumno/a',personal:'Personal institucional'};
export const legacyProfile=role=>({director:'autoridad',administrador:'autoridad',bibliotecario:'biblioteca',docente:'docente',alumno:'lector',personal:'personal'})[role]||'';
export const profileRole=p=>({biblioteca:'bibliotecario',autoridad:'director',docente:'docente',personal:'personal',lector:'alumno'})[p]||'';
export function suggestProfile(cargo){return /director|rector|regente|secretari/i.test(cargo)?'autoridad':/bibliotec/i.test(cargo)?'biblioteca':/docente|profesor|maestr/i.test(cargo)?'docente':/estudiante|alumn|lector/i.test(cargo)?'lector':'personal';}
// Legacy callers remain supported; migrated records always have an explicit accessProfile.
export const ROLE_PERMISSIONS=Object.fromEntries(Object.keys(ROLES).map(r=>[r,['director','administrador','bibliotecario'].includes(r)?PERMISSIONS:basic]));
export function isEnabled(user,at=new Date()){return Boolean(user&&user.active!==false&&(!user.status||user.status==='active')&&(!user.startsAt||Date.parse(user.startsAt)<=+at)&&(!user.expiresAt||Date.parse(user.expiresAt)>+at));}
export function hasPermission(user,permission,grants=[],at=new Date()){if(!isEnabled(user,at))return false;if(user.mainAdmin)return true;return (user.accessProfile!==undefined?PROFILE_PERMISSIONS[user.accessProfile]||[]:ROLE_PERMISSIONS[user.role]||[]).includes(permission)||grants.some(g=>g.userId===user.id&&(!user.institutionId||g.institutionId===user.institutionId)&&g.permission===permission&&isEnabled(g,at));}
export function requirePermission(state,actorId,permission,at=new Date()){const user=state.patrons.find(u=>u.id===actorId);if(!hasPermission(user,permission,state.grants,at))throw new Error('No tenés permiso vigente para: '+(LABELS[permission]||permission));return user;}
export function validWindow(startsAt,expiresAt){if(startsAt&&!Number.isFinite(Date.parse(startsAt))||expiresAt&&!Number.isFinite(Date.parse(expiresAt)))throw new Error('Fecha de habilitación inválida.');if(startsAt&&expiresAt&&Date.parse(expiresAt)<=Date.parse(startsAt))throw new Error('El vencimiento debe ser posterior al inicio.');}
export function userRecord(raw,old={}){const name=String(raw.name||'').trim().slice(0,160);if(!name)throw new Error('Ingresá el nombre de la persona.');if(raw.role&&!ROLES[raw.role])throw new Error('Rol inválido.');validWindow(raw.startsAt,raw.expiresAt);return {...old,id:old.id||raw.id||crypto.randomUUID(),name,role:raw.role||'',course:String(raw.course||'').slice(0,80),active:raw.active!==false,startsAt:raw.startsAt||'',expiresAt:raw.expiresAt||'',institutionId:old.institutionId||'local-institution'};}
export function grantRecord(raw,actorId){if(!PERMISSIONS.includes(raw.permission))throw new Error('Permiso inválido.');validWindow(raw.startsAt,raw.expiresAt);return {id:crypto.randomUUID(),userId:raw.userId,permission:raw.permission,grantedBy:actorId,startsAt:raw.startsAt||new Date().toISOString(),expiresAt:raw.expiresAt||'',note:String(raw.note||'').slice(0,1000),active:true,createdAt:new Date().toISOString()};}

export function canManageTarget(actor,target){
 if(!actor||!target||actor.id===target.id)return false;
 if(actor.mainAdmin)return true;
 const a=PROFILE_LEVELS[actor.accessProfile]||0,t=PROFILE_LEVELS[target.accessProfile]||0;
 if(actor.accessProfile==='autoridad')return !target.mainAdmin&&t<a;
 if(actor.accessProfile==='biblioteca')return !target.mainAdmin&&t<PROFILE_LEVELS.biblioteca;
 return false;
}
