export const PERMISSIONS=Object.freeze(['catalog.view','catalog.create','catalog.edit','catalog.delete','holdings.create','holdings.edit','circulation.loan','circulation.return','reservations.create','reservations.manage','users.manage','permissions.manage','reports.view']);
export const ROLES=Object.freeze({director:'Director/a',administrador:'Administrador/a institucional',bibliotecario:'Bibliotecario/a',docente:'Docente',alumno:'Alumno/a'});
const basic=['catalog.view','reservations.create'];
export const ROLE_PERMISSIONS=Object.freeze(Object.fromEntries(Object.keys(ROLES).map(role=>[role,['director','administrador','bibliotecario'].includes(role)?[...PERMISSIONS]:[...basic]])));
export function isEnabled(user,at=new Date()){return Boolean(user&&user.active!==false&&(!user.startsAt||Date.parse(user.startsAt)<=+at)&&(!user.expiresAt||Date.parse(user.expiresAt)>+at));}
export function hasPermission(user,permission,grants=[],at=new Date()){if(!isEnabled(user,at))return false;return (ROLE_PERMISSIONS[user.role]||[]).includes(permission)||grants.some(g=>g.userId===user.id&&g.permission===permission&&g.active!==false&&(!g.startsAt||Date.parse(g.startsAt)<=+at)&&(!g.expiresAt||Date.parse(g.expiresAt)>+at));}
export function requirePermission(state,actorId,permission,at=new Date()){const user=state.patrons.find(u=>u.id===actorId);if(!hasPermission(user,permission,state.grants,at))throw new Error('Tu perfil local no tiene permiso vigente para esta acción: '+permission);return user;}
export function validWindow(startsAt,expiresAt){if(startsAt&&!Number.isFinite(Date.parse(startsAt))||expiresAt&&!Number.isFinite(Date.parse(expiresAt)))throw new Error('Fecha de habilitación inválida.');if(startsAt&&expiresAt&&Date.parse(expiresAt)<=Date.parse(startsAt))throw new Error('El vencimiento debe ser posterior al inicio.');}
export function userRecord(raw,old={}){const name=String(raw.name||'').trim().slice(0,160);if(!name)throw new Error('Ingresá el nombre de la persona.');if(raw.role&&!ROLES[raw.role])throw new Error('Rol inválido.');validWindow(raw.startsAt,raw.expiresAt);return {...old,id:old.id||raw.id||crypto.randomUUID(),name,role:raw.role||'',course:String(raw.course||'').slice(0,80),active:raw.active!==false,startsAt:raw.startsAt||'',expiresAt:raw.expiresAt||'',institutionId:'local-institution'};}
export function grantRecord(raw,actorId){if(!PERMISSIONS.includes(raw.permission))throw new Error('Permiso inválido.');validWindow(raw.startsAt,raw.expiresAt);return {id:crypto.randomUUID(),userId:raw.userId,permission:raw.permission,grantedBy:actorId,startsAt:raw.startsAt||new Date().toISOString(),expiresAt:raw.expiresAt||'',note:String(raw.note||'').slice(0,1000),active:true,createdAt:new Date().toISOString()};}
